cometbft/cometbft

- .github/workflows/build.yml
- .github/workflows/check-generated.yml
- .github/workflows/cometbft-docker.yml
- .github/workflows/e2e-manual.yml
- .github/workflows/e2e-nightly-34x.yml
- .github/workflows/e2e-nightly-main.yml
- .github/workflows/e2e.yml
- .github/workflows/govulncheck.yml
- .github/workflows/lint.yml
- .github/workflows/testapp-docker.yml
- .github/workflows/tests.yml
- DOCKER/Dockerfile
- DOCKER/build.sh
- test/e2e/Makefile
- test/e2e/docker/Dockerfile
Partially addresses #158, and manual back-port of #256.
---
> ci: Remove all private repo-related workflow/build config from `v0.37.x`

- .github/workflows/e2e-nightly-34x.yml
- .github/workflows/e2e.yml
- .github/workflows/govulncheck.yml
- .github/workflows/lint.yml
- .github/workflows/testapp-docker.yml
- DOCKER/Dockerfile
- test/e2e/docker/Dockerfile
Partially addresses #158, and manual backport of #256.
---
> ci: Remove all private repo-related workflow/build config from `v0.34.x`

- .github/workflows/build.yml
- .github/workflows/check-generated.yml
- .github/workflows/cometbft-docker.yml
- .github/workflows/e2e-manual-multiversion.yml
- .github/workflows/e2e-manual.yml
- .github/workflows/e2e-nightly-34x.yml
- .github/workflows/e2e-nightly-37x.yml
- .github/workflows/e2e-nightly-main.yml
- .github/workflows/e2e.yml
- .github/workflows/govulncheck.yml
- .github/workflows/lint.yml
- .github/workflows/testapp-docker.yml
- .github/workflows/tests.yml
- DOCKER/Dockerfile
- DOCKER/build.sh
- Makefile
- test/e2e/Makefile
- test/e2e/docker/Dockerfile
Partially addresses #158 (just for `main`). I'll submit per-release-branch backports manually.
Since we're working in public now, this is all no longer necessary.
---
> ci: Remove all private repo-related workflow/build config on `main`

- .github/workflows/check-generated.yml
- .github/workflows/cometbft-docker.yml
- .github/workflows/coverage.yml
- .github/workflows/e2e-manual.yml
- .github/workflows/tests.yml
- DOCKER/build.sh
- Makefile
- test/e2e/Makefile
Follow-up to #258, where it appears as though I missed these instances.
---
> ci: Follow-up to remove all private repo-related workflow/build config

- version/version.go
This is just a version bump to supersede the latest TM release.
---
> Update version to 0.34.27

- docs/qa/method.md
Contributes to cometbft/qa-infra#2
Adapted the text with the new functionality, and the new uses cases we're doing now.
---
> Updated method for running 200 node test

- rpc/openapi/openapi.yaml
close: #304 
fixing wrong version in `v0.37` openapi doc
---
> fixing version information (#304)

- .github/workflows/build.yml
- .github/workflows/docs-toc.yml
- .github/workflows/e2e.yml
- .github/workflows/govulncheck.yml
- .github/workflows/lint.yml
- .github/workflows/linter.yml
- .github/workflows/proto-lint.yml
- .github/workflows/tests.yml
Similar to #310, but for the `v0.37.x` branch.
---
> ci: De-duplicate release workflows for v0.37.x

- docs/core/block-sync.md
- docs/introduction/what-is-cometbft.md
- docs/tutorials/go-built-in.md
> Fix: typos

- docs/qa/README.md
just a quick fix for a merge conflict that was not fixed.
---
> fixed merge conflict issue

- README.md
Thanks @lasarojc for picking this up!
---
> docs: Fix version compatibility notice in readme

- .github/workflows/codeql.yml
Fixes the linter complaints [here](https://github.com/cometbft/cometbft/actions/runs/4295121399/jobs/7485086418).
---
> ci: Fix CodeQL YAML

- spec/abci/abci++_app_requirements.md
- spec/abci/abci++_basic_concepts.md
- spec/abci/abci++_comet_expected_behavior.md
- spec/abci/abci++_methods.md
When PR #421  was merged, the latest push applying the comments from @sergio-mena  was not performend and I missed this. This PR is actually applying those last comments.
> spec/abci2.0 - fix uncommenting vef PR

- docs/tutorials/go-built-in.md
> Revert "Update go-built-in.md"

- .github/workflows/govulncheck.yml
- types/vote.go
- types/vote_test.go
Manual backport of #511
Sequence:
1) write failing UT
2) change prod code to make UT pass
---
> Votes can't have zero height

- .github/workflows/e2e-manual-multiversion.yml
- .github/workflows/e2e-manual.yml
- .github/workflows/e2e-nightly-34x.yml
- .github/workflows/e2e-nightly-37x.yml
- .github/workflows/e2e-nightly-main.yml
- test/e2e/generator/generate.go
- test/e2e/generator/main.go
> e2e: add prometheus flag to Generator CLI

- docs/introduction/README.md
> Fix a typo

- .changelog/unreleased/improvements/475-upgrade-go-schnorrkel.md
- crypto/sr25519/pubkey.go
- go.mod
- go.sum
Updates go-schnorrkel dependency to its latest version (v1.0.0) which includes a security audit and some minor fixes.
Fixes #475.
---
> crypto/sr25519: upgrade to go-schnorrkel@v1.0.0

- .github/workflows/specs.yml
Followup to #641
I'd like to get CI to run on this PR before merging it into @josef-widder's branch, so I can fix any other error here.
---
> Fix CI for "Multi process p2p peer management Quint spec" branch

- docs/core/subscription.md
Updates the docs to fix the subscription wscat command
---
- [na] Tests written/updated
- [na] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
> docs: fix wscat invocation and add TLS note

- docs/core/configuration.md
Update config file generated by running cometbft init. This patch is for 0.34.x and resolves the issue #702
---
> Update config file - 0.34.x

- docs/core/configuration.md
Update config file generated by running cometbft init. This patch is for 0.38.x and resolves issue #702
---
> Update config file - 0.38.x

- docs/core/configuration.md
Update config file generated by running cometbft init. This patch is for 0.37.x and resolves issue #702
---
> Update config file - 0.37.x

- .changelog/unreleased/bug-fixes/771-kvindexer-parsing-big-ints.md
- .changelog/unreleased/bug-fixes/771-pubsub-parsing-big-ints.md
- docs/app-dev/indexing-transactions.md
- docs/core/subscription.md
- libs/pubsub/query/query.go
- libs/pubsub/query/query_test.go
- state/indexer/block/kv/kv.go
- state/indexer/block/kv/kv_test.go
- state/indexer/block/kv/util.go
- state/indexer/query_range.go
- state/txindex/kv/kv.go
- state/txindex/kv/kv_test.go
- state/txindex/kv/utils.go
Closes #726  for 0.34.x
This is a manual backport of #771  because Mergify did not trigger it.
> Backport of PR #771 to 0.34 : big int parsing

- RELEASES.md
This PR includes an update releases.md to specify signing tags.
---
> docs: Update releases.md to sign tags

- mempool/reactor.go
- mempool/reactor_test.go
This PR adds some extra testing to the base one.
> Adding a test for when peers are late

- blocksync/errors.go
- blocksync/msgs.go
- blocksync/reactor.go
---
Contributes: #1140 
Export errors in `blocksync` package. More context: #1140
> blocksync: export errors

- test/e2e/Makefile
- test/e2e/docker/Dockerfile.fast
- test/e2e/docker/entrypoint-fast
- test/e2e/fast-prototyping/README.md
> Merge main into feature/bw-improvements-30

- .changelog/unreleased/improvements/1210-close-evidence-db.md
- node/node.go
> Close evidence.db OnStop

- config/config.go
- state/pruner.go
- state/store.go
This PR addresses comments from @sergio-mena  after the original PR #1150 was merged. 
---
> ADR-101: Pruning mechanism minor fixes

- test/e2e/scripts/README.md
- test/e2e/scripts/gen_manifest.py
- test/e2e/scripts/graph.py
- test/e2e/scripts/plot.py
- test/e2e/scripts/topology.py
Scripts for generating random topologies. See README.md.
---
> e2e: Scripts for random network topology generator

- p2p/conn/connection.go
> lint:fixed memory aliasing in for loop 

- .changelog/unreleased/bug-fixes/1017-remove-genesis-persistence-in-state-db.md
- blocksync/reactor_test.go
- consensus/byzantine_test.go
- consensus/common_test.go
- consensus/reactor_test.go
- consensus/replay_test.go
- node/node.go
- node/node_test.go
- node/setup.go
- state/mocks/store.go
- state/state_test.go
- state/store.go
- state/store_test.go
- state/tx_filter_test.go
- store/store_test.go
Update the feature branch and resolve conflicts.
---
> Merge latest changes from `main` into `feature/adr101-pull-companion`

- evidence/errors.go
- evidence/pool.go
- evidence/pool_test.go
- evidence/reactor.go
- evidence/verify.go
- node/node.go
- state/errors.go
- types/evidence.go
Contributes to: https://github.com/cometbft/cometbft/issues/1140
Export errors in evidence. More context: https://github.com/cometbft/cometbft/issues/1140.
> evidence: export errors

- .changelog/unreleased/breaking-changes/1287-genesis-doc-hash-from-file.md
- node/setup.go
> node: verify genesis doc hash against the file contents rather than remarshalled JSON

- .changelog/unreleased/features/1234-pruning-metrics.md
Added changelog for PR #1234 .
---
> Added changelog for pruning metrics

- rpc/openapi/openapi.yaml
Begin block events and end block events are merged into Finalizeblock events.
---
> rpc: add finalize_block_events to rpc doc

- state/txindex/indexer_service.go
Closes: https://github.com/cometbft/cometbft/issues/1328
Tiny typo fix.
> Fix typo: exent -> event

- README.md
> Update Go version specified in root README on main for `v0.34.x`

- test/grafana/README.md
- test/grafana/datasource.sh
Added a few additional or missing steps while going through the README. This is testing on a Linux machine. Feel free to merge if it makes sense, if not it's OK to close the PR.
> PR1348: some minor updates and suggestions for instructions

- .changelog/unreleased/breaking-changes/1324-load-state-from-gen-file-api.md
- .changelog/unreleased/improvements/1324-cli-genesis-hash-checked-on-load.md
- .gitignore
- README.md
- cmd/cometbft/commands/run_node.go
- config/config.go
- config/toml.go
- node/node.go
- node/node_test.go
- node/setup.go
> adr101:merge main into feature branch

- .github/workflows/cometbft-docker.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/testapp-docker.yml
> ADR101: merge changes from main into feature branch

- mempool/reactor.go
Proposal to address synchronization issues of #1119:
1. A `broadcastTxRoutine` is started for every peer added to the reactor, regardless the output of `WaitSync()`
2. The `broadcastTxRoutine` starts by checking the output of `WaitSync()`. If it is true, it blocks on a new `waitSyncCh` channel until the node is allowed to broadcast transactions.
3. The `EnableInOutTxs()` method does not start `broadcastTxRoutine` instances any longer, as they are started by `AddPeer()`. It instead unblocks every blocked routine by closing the  `waitSyncCh` channel.
> mempool: waitSync channel to block broadcast routines

- docs/guides/go-built-in.md
- docs/guides/go.md
This PR closes the issue #1376
---
> Max byte check

- rpc/openapi/openapi.yaml
> Update to string

- state/txindex/indexer_service.go
Backport of #1329 to v0.34.x.
---
> backport: Fix typo: exent -> event (#1329)

- light/example_test.go
- light/provider/http/http_test.go
- rpc/client/examples_test.go
- rpc/client/main_test.go
- rpc/test/helpers.go
> Renames Tendermint to CometBFT in the RPC related test code

- state/pruner.go
Closes #1489 
This should be backported to `v0.38.x-experimental`
---
> state/pruner: Notify observer only when retain height changes

- state/pruner.go
> state: v0.38. backport of #1490

- .changelog/unreleased/bug-fixes/1529-indexer-respect-height-params-on-query.md
- state/indexer/query_range.go
- state/txindex/kv/kv_test.go
- test/e2e/pkg/infra/docker/docker.go
> indexer-respect-height-params-on-query

- .changelog/unreleased/bug-fixes/1529-indexer-respect-height-params-on-query.md
- .github/workflows/janitor.yml
- .github/workflows/proto-lint.yml
- .golangci.yml
- crypto/merkle/tree_test.go
- docs/core/configuration.md
- libs/protoio/io.go
- p2p/netaddress.go
- scripts/qa/reporting/requirements.txt
- state/execution.go
- state/indexer/query_range.go
- state/indexer/sink/psql/psql.go
- state/txindex/kv/kv_test.go
- types/vote_set.go
> Merging v0.38.x into the experimental branch 

- test/e2e/scripts/plot.py
Use pyviz to visualize and interact with the topology.
---
> add interactive visualization of graph

- .changelog/unreleased/improvements/1579-e2e-disable-pex-reactor.md
- test/e2e/pkg/manifest.go
- test/e2e/pkg/testnet.go
- test/e2e/runner/setup.go
> e2e: Allow disabling the PEX reactor on all nodes in the testnet

- .github/workflows/build.yml
- .github/workflows/check-generated.yml
- .github/workflows/e2e-manual-multiversion.yml
- .github/workflows/e2e-manual.yml
- .github/workflows/e2e-nightly-37x.yml
- .github/workflows/e2e-nightly-main.yml
- .github/workflows/e2e.yml
- .github/workflows/fuzz-nightly.yml
- .github/workflows/govulncheck.yml
- .github/workflows/lint.yml
- .github/workflows/pre-release.yml
- .github/workflows/release-version.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- DOCKER/Dockerfile
- go.mod
- go.sum
- test/e2e/docker/Dockerfile
- test/fuzz/README.md
- test/fuzz/tests/mempool_test.go
- test/fuzz/tests/p2p_secretconnection_test.go
- test/fuzz/tests/rpc_jsonrpc_server_test.go
> v0.38.x: Bump Go version to v1.21

- .github/workflows/build.yml
- .github/workflows/check-generated.yml
- .github/workflows/e2e-long-37x.yml
- .github/workflows/e2e-manual-multiversion.yml
- .github/workflows/e2e-manual.yml
- .github/workflows/e2e-nightly-37x.yml
- .github/workflows/e2e-nightly-main.yml
- .github/workflows/e2e.yml
- .github/workflows/fuzz-nightly.yml
- .github/workflows/govulncheck.yml
- .github/workflows/lint.yml
- .github/workflows/pre-release.yml
- .github/workflows/release-version.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- DOCKER/Dockerfile
- go.mod
- go.sum
- test/e2e/docker/Dockerfile
> v0.37.x: Bump Go version to v1.21

- .changelog/unreleased/improvements/1558-experimental-gossip-limiting.md
- config/config.go
- config/toml.go
> Comment that experimental mempool only applies to v0

- proto/buf.lock
- proto/buf.yaml
Partially addresses #1402.
---
> proto: Prepare for publishing v0.34.x protos to Buf registry

- proto/buf.lock
- proto/buf.yaml
Partially addresses #1402.
---
> proto: Prepare for publishing v0.37.x protos to Buf registry

- proto/buf.lock
- proto/buf.yaml
Partially addresses #1402.
---
> proto: Prepare for publishing v0.38.x protos to Buf registry

- docs/architecture/adr-111-nop-mempool.md
regarding the possibility of reusing CometBFT's P2P network by the ABCI app once it's possible.
Also, added a tracking issue.
> ADR-111: Addressed Ethan's comment

- internal/state/mocks/store.go
Updates the generated mock code on the `feature/proto-upgrade` branch.
---
> feature/proto-upgrade: Fix generated mock code

- .changelog/v0.34.31/bug-fixes/1654-semaphore-wait.md
- .changelog/v0.34.31/summary.md
- .changelog/v0.37.4/bug-fixes/1654-semaphore-wait.md
- .changelog/v0.37.4/features/1643-nop-mempool.md
- .changelog/v0.37.4/summary.md
- .changelog/v0.38.2/bug-fixes/1654-semaphore-wait.md
- .changelog/v0.38.2/features/1643-nop-mempool.md
- .changelog/v0.38.2/summary.md
- CHANGELOG.md
Include changelogs from v0.3* updates
---
> chore: Update CHANGELOG.md

- .github/mergify.yml
I should've done this in #1714 but forgot, my apologies for that.
---
> Enable Mergify backports for `v1.x` branch

- .changelog/unreleased/improvements/1715-validate-validator-address.md
already released in v1.alpha1. introduced by mistake in https://github.com/cometbft/cometbft/pull/1761
> changelog: remove already released entry

- .changelog/unreleased/bug-fixes/1754-no-oversized-blocks.md
- test/e2e/app/app.go
> [e2e] Fixes prepareProposal not to return oversized set of transactions

- docs/networks/docker-compose.md
<Description>
Fix only minor typos in the documents
No test required
> Fix: Fix minor typos

- types/validation.go
- types/validation_test.go
> Small improvements in #1806 not present in #1750

- .changelog/unreleased/bug-fixes/1749-light-client-attack-verify-all-sigs.md
As per title. Backporting to all branches
---
> Add changelog for #1749

- .codespellrc
- .github/workflows/codespell.yml
- .github/workflows/ignore-words.txt
- Makefile
- p2p/switch.go
- rpc/client/rpc_test.go
- spec/light-client/detection/draft-functions.md
Port of https://github.com/osmosis-labs/osmosis/pull/7088
---
> add GH workflow for linting code using codespell

- .github/workflows/lint.yml
- .golangci.yml
- Makefile
- consensus/reactor_test.go
was failing for me in https://github.com/cometbft/cometbft/pull/1782
---
> ci: fix failing golangci-lint action

- .changelog/unreleased/bug-fixes/1825-false-on-nil-key.md
- crypto/batch/batch.go
- types/validation.go
- types/validation_test.go
- types/validator_set_test.go
> Adds checks for nil keys and signatures

- README.md
[Rendered](https://github.com/cometbft/cometbft/blob/thane/fix-discord-link/README.md#releases)
Thanks to @Frierened for the suggestion in #1836!
---
> docs: Fix Discord links in README

- types/vote.go
Added an extra check for empty vote extension signature that makes sense, and may improve info in case of troubleshooting (I felt the need to add it while debugging a failing UT)
Not backporting to `v0.38.x` as it touches prod code and is not strictly needed there.
---
> Extra check in `VerifyExtension`

- DOCKER/README.md
> doc:fix broken link in DOCKER/README.md

- .golangci.yml
- docs/tools/README.md
- go.mod
- go.sum
- test/loadtime/README.md
- test/loadtime/cmd/load/main.go
> chore(test/loadtime): replace tm-load-test w/ cometbft-load-test

- .changelog/unreleased/bug-fixes/642-clist-mempool-data-races.md
- mempool/clist_mempool.go
- mempool/clist_mempool_test.go
> mempool: Fix data races in CListMempool's height and notifiedTxsAvailable

- .golangci.yml
- go.mod
- go.sum
> chore(test/loadtime): cleanup go.sum and golangci.yml

- codecov.yml
- go.mod
- go.sum
- tools/tools.go
> misc(go.mod): remove unused peg dependency

- .changelog/unreleased/bug-fixes/0000-asa-2024-001-fix-validate.md
- types/params.go
- types/params_test.go
Manual backport of fix and UTs of advisory ASA-2024-001
---
> Backport ASA-2024-001

- networks/local/localnode/Dockerfile
Nit: upgrade alpine linux in localnode Dockerfile
> deps(localnode): bump alpine version

- internal/consensus/metrics.go
- scripts/metricsgen/metricsgen.go
- scripts/metricsgen/metricsgen_test.go
> scripts: metricsgen parses '// metrics:' pattern

- .changelog/unreleased/improvements/2093-metric-chain-size-bytes.md
- internal/consensus/metrics.gen.go
- internal/consensus/metrics.go
- internal/consensus/state.go
This metric measures the total size of the chain in bytes.
---
> consensus: Add `chain_size_bytes` metric

- .github/workflows/conventional-pr-title.yml
> ci: fix permissions for "Conventional PR Title"

- .github/workflows/conventional-pr-title.yml
> ci: add `spec` type in conventional-pr-title

- docs/references/qa/method.md
An additional configuration step has been added to the README
in the qa-infra repository
(https://github.com/cometbft/qa-infra/pull/35).
> docs: update QA method steps for qa-infra changes

- README.md
Current link is broken, thought of fixing it myself instead of opening an Issue, less time wasted.
> chore: updated doc link

- node/node.go
> fix(node): Forward compaction config params to blockstore constructor 

- types/params_test.go
Removing variable creation and assignment because it is never read.
---
> chore(pbts): Removes useless code

- docs/references/qa/CometBFT-QA-34.md
Fixed a few minor spelling mistakes which were also included in the celestia repo in order to pull the change to there.
> chore: typo fixes

- test/monitoring/config-grafana/provisioning/dashboards-data/storage.json
Grafana dashboard fixes for storage testing. Also removed experimental entries. Used by `localnet` monitoring.
---
> fix(localnet): Grafana dashboards for storage tests - removed experimental metrics

- README.md
It removes Terra from the readme file
> docs(README): remove Terra

- docs/references/architecture/adr-108-e2e-abci++.md
---
Closes #353. This PR updates ADR-108 to account for the new grammar with vote extensions and the latest changes in the code.
> docs(ADR): ADR-108 updated to account for the new changes in the grammar and code.

- .changelog/unreleased/improvements/2467-decrease-n-of-requested-blocks.md
- blocksync/pool.go
- blocksync/pool_test.go
- blocksync/reactor.go
Manual backport of https://github.com/cometbft/cometbft/pull/2467
> feat(blocksync): set the max number of (concurrently) downloaded blocks (backport #2467)

- internal/consensus/metrics.gen.go
- internal/consensus/metrics.go
- types/params.go
> feat(pbts): Adjusts PBTS metrics buckets

- spec/abci/abci++_methods.md
> docs: format error in ABCI++ specs under commit and listsnapshots section

- docs/explanation/core/configuration.md
> docs: Copy description of section on compaction to docs

- test/e2e/runner/perturb.go
When a node restarts and there's no state on disk to restore (because of `persist_interval = 0`), the application takes some time to replay blocks before starting. During this time, the RPC endpoints are still disabled, so the e2e's waiting function cannot check the nodes' status.
---
> fix(e2e): Increase waiting timeout when killing, pausing, or restarting a node

- RELEASES.md
As per title.
Mostly, explaining how to deal if the (new) `api` module.
---
> docs: some fixes to `RELEASES.md`

- rpc/openapi/openapi.yaml
> fix: typo in openapi schema

- .codespellrc
> feat(lint): disable codespell for Quint (*.qnt) files

- spec/consensus/gossip/README.md
- spec/consensus/gossip/crdt.md
- spec/consensus/gossip/crdt.qnt
- spec/consensus/gossip/gossip.md
- spec/consensus/gossip/sse.qnt
> spec: Makes some small fixes on the spec and documents some TODOs

- .changelog/unreleased/breaking-changes/2692-privval-sign-bytes.md
- CHANGELOG.md
> chore: move changelog entry

- rpc/jsonrpc/client/ws_client.go
> refactor(rpc): miss stop PingPongLatencyTimer

- docs/references/qa/method.md
Editing file `method.md` with up-to-date instructions on how to run the rotating node test.
---
> docs(qa): changes to `method.md` after running rotating node for `v1.x`

- rpc/jsonrpc/client/ws_client.go
Followup to #2792 which closed #2771.
#2792 does not handle the case where Start is never called. If Start is not called, Stop returns an error, thus with #2792's implementation the only way to ensure that PingPongLatencyTimer is cleaned up is to call Start and Stop, even when not using any of the features provided by Start (i.e. events).
This PR moves initialization of PingPongLatencyTimer into OnStart so that it is only initialized if it is going to be used. This PR also moves cleanup of PingPongLatencyTimer into readRoutine's defer statement to align it with other cleanup (i.e. closing the connection).
> refactor(rpc): allocate PingPongLatencyTimer on start

- state/doc.go
- store/doc.go
Please note that I didn't use the `Deprecated` keyword because doing this would result in many warnings for us and our users.
Follow-up to https://github.com/cometbft/cometbft/pull/2709
---
> chore: mark state and store packages as deprecated

- spec/abci/abci++_client_server.md
> spec: remove old abci servers and fix links

- abci/client/socket_client_test.go
- abci/server/socket_server.go
- cmd/cometbft/commands/debug/io.go
---
fix function name in comment
> chore: fix function name in comment

- internal/bits/bit_array.go
- internal/bits/bit_array_test.go
> fix(bits): handle last element in PickRandom

- .changelog/unreleased/improvements/2924-consensus-cache-block-hash.md
- types/block.go
Closes #2923 
Caches the block hash to ensure we only compute it once in consensus execution.
---
> perf(state): Cache the block hash

- crypto/merkle/tree.go
- internal/events/events_test.go
- libs/math/fraction.go
> chore: fix function names

- spec/abci/abci++_basic_concepts.md
- spec/abci/abci++_comet_expected_behavior.md
- spec/abci/abci++_methods.md
> spec(abci): slight improvements to ABCI spec (@angrav's feedback from Anoma)

- p2p/conn/connection.go
Fully compatible refactor to the `sendSomePacketMsgs` loop, that I think makes it easier to:
1) Understand the code
2) See how we improve it for serial time performance
3) Puts my notes for how to improve some consensus gossip bottlenecks.
---
> refactor(p2p/connection): Slight refactor to sendManyPackets that helps highlight performance improvements

- docs/references/architecture/README.md
- docs/references/architecture/adr-114-undo-109.md
> docs(ADR-114): Partly Undo ADR 109 (Reduce Go API Surface)

- .changelog/unreleased/improvements/2988-flush-throttle-timeout.md
- config/config.go
- docs/references/config/config.toml.md
- p2p/conn/connection.go
- spec/p2p/implementation/configuration.md
> perf(p2p): lower `flush_throttle_timeout`

- docs/tutorials/go-built-in.md
> docs: add missing param for NewNode

- spec/abci/abci.md
> spec: fix broken link

- docs/tutorials/go-built-in.md
"Fenced code blocks should be surrounded with blank lines"
---
> docs: lint markdown

- internal/consensus/state.go
- internal/consensus/state_test.go
- mempool/reactor_test.go
> chore: remove repetitive words

- crypto/bls12381/key_bls12381.go
- go.mod
- go.sum
> chore(deps): remove `minio/sha256-simd`

- config/config.go
- internal/consensus/pbts_test.go
> chore: fix function names in comment

- .changelog/unreleased/improvements/3087-use-signal-notify-context.md
- cmd/cometbft/commands/inspect.go
> refactor(cmd): use `signal.NotifyContext`

- .changelog/unreleased/breaking-changes/2892-remove-skip-timeout-commit.md
- UPGRADING.md
- config/config.go
- config/config.toml.tpl
- docs/references/config/config.toml.md
- internal/consensus/reactor_test.go
- internal/consensus/state.go
- internal/consensus/state_test.go
instead of removing it
Refs #2926
https://github.com/cometbft/cometbft/issues/2873#issuecomment-2117172714
---
> feat(config): deprecate skip_timeout_commit

- test/e2e/pkg/latency/latency-setter.py
> chore: Add detailed comments explaining traffic control commands

- docs/references/rfc/tendermint-core/rfc-013-abci++.md
- docs/references/rfc/tendermint-core/rfc-015-abci++-tx-mutation.md
- scripts/qa/reporting/README.md
- spec/abci/abci++_methods.md
- spec/consensus/proposer-based-timestamp/v1/pbts-sysmodel_001_draft.md
> chore: remove duplicated words

- privval/signer_server.go
Refer to [comment](https://github.com/cometbft/cometbft/pull/3104#discussion_r1616324957) from @sergio-mena
> refactor: use closure and defer to ensure unlock in case of panic

- docs/references/architecture/adr-113-mempool-lanes.md
Partially addresses #3110
Added subsection in "Alternative approaches" section describing transaction priorities in Solana, and how they compare to the present Mempool QoS design.
---
- ~~[ ] Tests written/updated~~
- ~~[ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)~~
> docs(mempool): comparison with Solana's Gulf Stream

- types/validator_test.go
Adds an additional test on `types/validator_test` to ensure the `Copy()` method is performing the copy properly
> test(types): add a test for the validator `Copy()` method

- test/e2e/app/app.go
Recently introduces TTL mechanism in e2e's kvstore app (#3201) is not concurrent safe when accessed from different ABCI connections.
---
> fix(e2e): make TTL's `sentTxs` atomic on kvstore

- config/config.go
- config/config_test.go
- proxy/client.go
- test/e2e/runner/setup.go
Closes https://github.com/cometbft/cometbft/issues/2719
---
> feat(config): validate `proxy_app`

- docs/references/architecture/README.md
- docs/references/architecture/adr-115-predictable-block-times.md
small changes based on Daniel's internal comments
---
> docs(adr-115): mark as accepted

- config/config.go
- config/config.toml.tpl
- config/config_test.go
> feat(config)!: remove unused `mempool.wal_dir`

- docs/references/architecture/adr-106-grpc-api.md
This PR simply aligns the status of ADR 106 with what is in the README.
---
> docs(adr-106): mark as accepted

- test/e2e/tests/grpc_test.go
This pull request resolves the intermittent failures of the gRPC test for GetBlockResults, which were caused by non-deterministic pruning logic.
> test(e2e): remove flaky logic in test for GetBlockResults

- abci/types/types.go
- api/cometbft/rpc/grpc/v1beta1/types.pb.go
- internal/consensus/replay_stubs.go
- libs/cli/setup.go
- privval/signer_endpoint.go
- proto/cometbft/rpc/grpc/v1beta1/types.proto
- test/e2e/pkg/infra/docker/docker.go
---
fix function and type names in comments to provide better reading experience.
> chore: fix function name in comments

- privval/signer_requestHandler.go
> fix(privval): eliminate dead code

- crypto/merkle/proof.go
- state/indexer/block/kv/kv.go
- test/e2e/runner/load.go
> chore: correctly break from for loops

- light/store/db/db.go
- node/errors.go
- state/indexer/block/indexer.go
- state/indexer/block/kv/kv.go
- state/state_test.go
> chore: fix comments

- internal/evidence/pool.go
- privval/signer_endpoint.go
---
update the comment to be consistent with code.
> chore: fix comment

- rpc/openapi/openapi.yaml
> docs(rpc): update /abci_info return parameters

- spec/README.md
> spec: fix broken link in README

- docs/guides/app-dev/indexing-transactions.md
- rpc/openapi/openapi.yaml
> docs: remove not existing key from block search query

- .gitignore
> chore: add test/e2e/networks_regressions/*/ to gitignore

- .changelog/unreleased/bug-fixes/3002-invalid-txs-results.md
> docs(changelog): fix changelog entry formatting

- README.md
- Fixed the go.dev badge
- Separated the Discord badge from the technical badges
- Added the link tree
**No need to backport these changes.**
---
> docs: Update README.md with more links and fixed badge

- Makefile
- tests.mk
As per our internal discussion today, here are some changes I think we should have.
Feel free to comment on further changes you may want to have in `tests.mk`
---
> fix(tests): fix obvious things in `tests.mk`

- .changelog/unreleased/improvements/2855-fix-txsearch-performance.md
- inspect/inspect_test.go
- rpc/core/blocks.go
- rpc/core/errors.go
- rpc/core/tx.go
- state/indexer/sink/psql/backport.go
- state/pruner_test.go
- state/txindex/indexer.go
- state/txindex/kv/kv.go
- state/txindex/kv/kv_bench_test.go
- state/txindex/kv/kv_test.go
- state/txindex/mocks/tx_indexer.go
- state/txindex/null/null.go
See #2855 or #2910 for a detailed description
---
> perf: TxSearch pagination (manual backport #2910)

- internal/consensus/metrics.gen.go
- internal/consensus/metrics.go
---
fix some comments
fix some comments
> chore: fix some comments

- Makefile
- docs/guides/networks/docker-compose.md
- test/e2e/pkg/infra/docker/docker.go
- test/monitoring/README.md
Refs https://github.com/actions/runner-images/issues/10384
---
> fix(e2e): replace docker-compose w/ docker compose

- .changelog/unreleased/features/3622-e2e-mempool-lanes.md
- .changelog/unreleased/features/3622-kvstore-mempool-lanes.md
> chore: fix changelog links 

- types/params.go
Closes #3643.
Unfortunately, we don't have an automatic way to include every crypto key added to here, or at least to check that all are included.
---
> fix(types): add and ABCIPubKeyType for sr25519 key

- api/cometbft/abci/v1/service.pb.go
- api/cometbft/abci/v1beta1/types.pb.go
- api/cometbft/abci/v1beta2/types.pb.go
- api/cometbft/abci/v1beta3/types.pb.go
- api/cometbft/rpc/grpc/v1beta1/types.pb.go
- api/cometbft/rpc/grpc/v1beta2/types.pb.go
- api/cometbft/rpc/grpc/v1beta3/types.pb.go
- api/cometbft/services/block/v1/block_service.pb.go
- api/cometbft/services/block_results/v1/block_results_service.pb.go
- api/cometbft/services/pruning/v1/service.pb.go
- api/cometbft/services/version/v1/version_service.pb.go
Thanks @sergio-mena for figuring it out (https://github.com/cometbft/cometbft/pull/3565#issuecomment-2276291505)
---
> chore: update auto-generated proto files

- .changelog/unreleased/breaking-changes/3659-mempool-add-contains-method.md
- internal/consensus/replay_stubs.go
- mempool/clist_mempool.go
- mempool/mempool.go
- mempool/mocks/mempool.go
- mempool/nop_mempool.go
> feat(mempool)!: Add new `Contains` method to `Mempool` interface

- cmd/cometbft/commands/inspect.go
- cmd/cometbft/commands/run_node.go
- common.mk
- config/config.go
- config/config.toml.tpl
- docs/references/config/config.toml.md
- mempool/reactor_test.go
- node/node.go
- p2p/pex/pex_reactor_test.go
- test/e2e/Makefile
- test/e2e/docker/Dockerfile
- test/e2e/generator/generate.go
- test/e2e/pkg/manifest.go
- test/e2e/pkg/testnet.go
> feat!: remove cleveldb and boltdb

- crypto/encoding/codec.go
- crypto/encoding/codec_test.go
- types/validator.go
> fix(crypto): panic: encoding: unsupported key {0xc015dcc0c0}

- abci/tutorials/abci-v2-forum-app/test/find_user_test.go
This version of linter was failing for the test in the forum demo app. 
---
> fix(abci/tutorials): Refactored test to appease linter

- .github/mergify.yml
because mergify can't approve its own PRs
> chore(mergify): remove APPROVE

- mempool/reactor_test.go
- p2p/pex/pex_reactor_test.go
> chore(tests): uncomment mempool & p2p reactor tests

- docs/explanation/core/metrics.md
- p2p/metrics.gen.go
- p2p/metrics.go
> feat(p2p/metrics)!: removed unused `p2p_num_txs` metric

- go.mod
- go.sum
> chore(deps): force update runc and viper

- rpc/grpc/server/privileged/privileged.go
- state/execution_test.go
> chore: fix some function names

- .github/workflows/e2e-nightly-34x.yml
> ci: use go 1.21 for v0.34.x branch

- .changelog/unreleased/features/3819-e2e-log-level.md
- test/e2e/pkg/manifest.go
- test/e2e/pkg/testnet.go
- test/e2e/runner/setup.go
> feat(e2e): Allow setting `log_level` in manifest

- mempool/clist_mempool.go
- mempool/reactor.go
Also, capitalise all first letters of logging messages.
---
> fix(mempool): Log tx hashes as hex instead of bytes

- go.mod
- go.sum
which contains updated dependencies
Refs https://github.com/informalsystems/afero/pull/1 Refs https://github.com/spf13/afero/pull/425
---
> build(deps): replace afero with our fork

- .codespellrc
- .github/workflows/ignore-words.txt
- .golangci.yml
- .pre-commit-config.yaml
- docs/references/architecture/tendermint-core/adr-026-general-merkle-proof.md
- docs/references/rfc/rfc-101-p2p-bad-peers-checktx.md
- docs/references/rfc/tendermint-core/rfc-026-p2p-bad-peers-checktx.md
- internal/autofile/group.go
- internal/consensus/state.go
- internal/os/os.go
- libs/bytes/bytes.go
- rpc/grpc/server/services/blockservice/service.go
- rpc/grpc/server/services/pruningservice/service.go
- scripts/metricsgen/metricsgen.go
- spec/abci/README.md
- spec/consensus/proposer-selection.md
- spec/light-client/detection/draft-functions.md
- types/validator_set_test.go
> ci: upgrade pre-commit hooks versions

- abci/example/kvstore/kvstore.go
- abci/example/kvstore/kvstore_test.go
Original PR was #3762, which was merged to incorrect an branch.
> feat(lanes): Change lane selection algorithm in kvstore app

- .github/mergify.yml
> ci: change Mergify merge method to squash

- docs/tutorials/go-built-in.md
- docs/tutorials/go.md
- scripts/proto-gen.sh
> chore(docs): update Go version

- docs/explanation/core/running-in-production.md
with text description
Refs https://github.com/cometbft/cometbft/issues/3436
---
> docs(running-in-production): replace external link

- abci/example/kvstore/kvstore.go
This is in preparation for testing applications that use and don't use lanes.
> test(mempool/lanes): Add initialisation functions to kvstore that don't use lanes

- config/config.go
- config/config_test.go
- types/errors/sanity.go
> feat(config): disallow flood mempool w/ 0 capacity

- mempool/iterators_test.go
> feat(mempool/test): Add test to check order when lanes are disabled

- docs/explanation/core/light-client.md
- docs/explanation/core/proposer-based-timestamps.md
- docs/explanation/core/running-in-production.md
- Fixed several typos in the documentation
> docs: Fix several minor typos

- .github/workflows/build.yml
- .github/workflows/e2e.yml
- .github/workflows/govulncheck.yml
- .github/workflows/tests.yml
- docs/references/architecture/adr-111-nop-mempool.md
- docs/references/architecture/adr-118-mempool-lanes.md
Posting against `main` (rather than the feature branch) as we had agreed (ADR's and the like make no sense in feature branches)
---
> docs(mempool): Ethereum pre-confirmations section

- test/e2e/app/app.go
- test/e2e/tests/app_test.go
close: #4119 
Updating values as described in the problem statement and resolution on the issue above.
---
> test(e2e): increase `txTTL` and `waitTime` to avoid testing failures

- .changelog/unreleased/improvements/3658-mempool-dont-send-removed-tx.md
fix for wrong URL on changelog entry
> fix(changelog): add 's' to the issues path

- libs/metrics/prometheus/prometheus_test.go
- libs/metrics/teststat/teststat.go
TestCounter: retry 5 times to get the data from prometheus
TestSummary: exclude 95 percentile because prometheus doesn't have it
Closes #4133
> test(metrics/prometheus): fix TestCounter and TestSummary

- libs/metrics/prometheus/prometheus_test.go
> test(metrics/prometheus): refactor scrape in prometheus test

- test/e2e/generator/generate.go
- test/e2e/pkg/manifest.go
- test/e2e/pkg/testnet.go
- test/e2e/runner/setup.go
- test/e2e/tests/validator_test.go
> feat(e2e): `Manifest.Validators` is not a pointer to a map, but a map

- docs/references/architecture/adr-118-mempool-lanes.md
Closes #4120 
- [Allow different lanes to the same priority](https://github.com/cometbft/cometbft/commit/73603656d5ef27223531f00b37b0fc4a9d9bf325)
- [Limits on lane capacities](https://github.com/cometbft/cometbft/commit/2de8f077dbb11ba9fdde9b676808f8d56b2fd1ed)
> docs(mempool/lanes): Update ADR with latest design changes

- README.md
Together with these other artifacts:
- https://github.com/cometbft/cometbft/discussions/590#discussioncomment-10669600
- the community call [discussion on Aug 1 '24](https://docs.google.com/document/d/1mcyccy-GaMMn3QVWYry5xhRORObnJTq37Dg6kViqpeA/edit#bookmark=id.17c2nidqrme5)
- the [announcements & reminders on X ](https://x.com/cometbft/status/1824058973924081984)
Closes #2697
No need to backport this.
---
> docs(readme): linked the support policy from the main readme file

- types/block.go
> chore: remove duplicate assignment of height in HeaderFromProto

- .golangci.yml
- test/e2e/pkg/manifest.go
- test/e2e/pkg/testnet.go
- test/e2e/runner/setup.go
Closes #3961.
Similarly to #3967, introduces a new `genesis` field for manifest files. The format is `key = value` and multiple entries can be provided. For example,
```
genesis = [ 
"consensus_params.evidence.max_bytes = 1000", 
"chain_id = pr3969" 
]
```
After the genesis document is produced by the `setup` implementation of the runner, the provided genesis customized configurations are applied to the generated genesis file. The solution also uses `viper`, as it allows setting only some specific keys, leaving the pre-produced content untouched.
Note: this PR is based atop
https://github.com/cometbft/cometbft/pull/3964 for simplicity, but it does not need to.
---
This is an manual backport of pull request https://github.com/cometbft/cometbft/pull/3969.
---------
---
> feat(e2e): allow customizing genesis parameters on the manifest (backport #3969)

- abci/tutorials/abci-v2-forum-app/forum.go
- cmd/cometbft/commands/gen_node_key.go
- cmd/cometbft/commands/init.go
- cmd/cometbft/commands/show_node_id.go
- cmd/cometbft/commands/testnet.go
- node/node_test.go
- node/setup.go
- p2p/nodekey/nodekey.go
- p2p/nodekey/nodekey_test.go
- rpc/test/helpers.go
- test/e2e/node/main.go
Refs #4302
**Important: no logic has been changed; just moving stuff and updating interfaces.**
> refactor(p2p/nodekey)!: remove NodeKey suffix

- node/node.go
- node/node_test.go
- p2p/handshake.go
- p2p/mock/peer.go
- p2p/nodeinfo/nodeinfo.go
- p2p/nodeinfo/nodeinfo_test.go
- p2p/peer.go
- p2p/peer_set_test.go
- p2p/test_util.go
- rpc/core/net.go
- rpc/core/status.go
- rpc/core/types/responses.go
- rpc/core/types/responses_test.go
Refs https://github.com/cometbft/cometbft/issues/4302
**Important: no logic has been changed; just moving stuff and updating interfaces.**
> refactor(p2p/nodeinfo)!: remove NodeInfo suffix

- .github/workflows/gobenchdata-base.yml
- .github/workflows/gobenchdata-current.yml
against `main` branch
https://github.com/bobheadxi/gobenchdata
> ci: use gobenchdata to benchmark each Go PR

- .changelog/unreleased/features/4338-e2e-monitoring.md
- .changelog/unreleased/improvements/2848-reduce-blockID-marshalling.md
- .github/workflows/gobenchdata-base.yml
- .github/workflows/gobenchdata-current.yml
- test/e2e/.gitignore
- test/e2e/README.md
- test/e2e/monitoring/README.md
- test/e2e/monitoring/compose.yaml
- test/e2e/monitoring/config-grafana/grafana.ini
- test/e2e/monitoring/config-grafana/provisioning/dashboards-data/main.json
- test/e2e/monitoring/config-grafana/provisioning/dashboards-data/mempool_compact.json
- test/e2e/monitoring/config-grafana/provisioning/dashboards/default.yml
- test/e2e/monitoring/config-grafana/provisioning/datasources/prometheus.yml
- test/e2e/networks/simple.toml
- test/e2e/pkg/infra/docker/docker.go
- test/e2e/pkg/testnet.go
- test/e2e/runner/cleanup.go
- test/e2e/runner/main.go
- test/e2e/runner/setup.go
- test/e2e/runner/templates/prometheus-yml.tmpl
- types/vote_set.go
- types/vote_set_test.go
> chore: Merge main into feature branch

- Makefile
> fix(makefile): re-added `build-linux`

- p2p/transport/tcp/conn/secret_connection.go
> docs(p2p/conn): fixed links and comments regarding our STS protocol implementation

- .changelog/unreleased/bug-fixes/0021-abc-panic-precommit-validator-index.md
- consensus/errors.go
- consensus/reactor_test.go
- consensus/state.go
- consensus/state_test.go
Cherry-pick of security advisory https://github.com/cometbft/cometbft/security/advisories/GHSA-p7mv-53f2-4cwj.
> merge commit from fork

- .changelog/v0.38.15/summary.md
- CHANGELOG.md
- version/version.go
[CHANGELOG](https://github.com/cometbft/cometbft/blob/release/v0.38.15/CHANGELOG.md#v03815).
Part of #4444.
> Release v0.38.15

- DOCKER/Dockerfile
See https://docs.docker.com/reference/build-checks/from-as-casing/
---
> build(docker): use upper case for keyword `as`

- spec/abci/abci++_methods.md
To be merged against #4460.
Fixed some markdown tables as well.
---
> fix(spec/abci): `VoteInfo` description updated from proto definition

- .changelog/unreleased/improvements/4484-v1keylayout-sprintf.md
- .changelog/unreleased/improvements/4490-state-v1LegacyLayout.md
- .changelog/unreleased/improvements/4490-v1LegacyLayout.md
- light/store/db/db_key_layout.go
- light/store/db/db_test.go
- state/store.go
- state/store_db_key_layout_test.go
- store/db_key_layout.go
This PR refactors the `v1LegacyLayout` key creation to improve its speed and reduce its memory usage.
Follow up to #4484.
---
> refactor(storage): Optimized `v1LegacyLayout` key creation.

- scripts/mockery_generate.sh
This is no the final fix and has to be followed up with #4521 .
Merging this will make all the PRs currently open against main pass. 
---
> fix(mockery): Temporary fixing the version of mockery to unblock main

- .changelog/unreleased/improvements/4484-v1keylayout-sprintf.md
- .changelog/unreleased/improvements/4490-v1LegacyLayout.md
- .changelog/unreleased/summary.md
- .github/workflows/e2e-long-main.yml
- .github/workflows/e2e-nightly-1x.yml
- .github/workflows/e2e-nightly-34x.yml
- .github/workflows/e2e-nightly-37x.yml
- .github/workflows/e2e-nightly-38x.yml
- .github/workflows/e2e-nightly-main.yml
- .github/workflows/fuzz-nightly.yml
- .github/workflows/notify-about-breaking-changes.yml
- .github/workflows/pre-release.yml
- .github/workflows/proto-lint.yml
- .github/workflows/release.yml
- docs/tutorials/forum-application/9.run-app.md
- go.mod
- go.sum
- light/store/db/db_key_layout.go
- light/store/db/db_test.go
- scripts/mockery_generate.sh
- spec/core/data_structures.md
- state/store.go
- state/store_db_key_layout_test.go
- store/db_key_layout.go
This PR merges branch `main` into the feature branch `feature/remove-cometbftdb` to keep it up-to-date.
> chore(storage): merge `main` into `feature/remove-cometbftdb`.

- .changelog/unreleased/bug-fixes/4521-fixes-breaking-mock.md
Adding changelog for #4521 
---
> fix(changelog): Add changelog for #4521

- .github/workflows/test-slack-notification.yml
> fix: add a new manual slack notification workflow for testing

- .github/workflows/fuzz-nightly.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
> fix: Slack notifications Templates for GitHub Actions workflows (`v0.38.x`)

- docs/explanation/core/block-sync.md
Small PR - Commit 10fa8d1016d98f8395be47cd2a9c40f2ae03e7bd moved the `pool.go` file. This PR adjusts sources to changes.
> docs: update `pool.go` reference

- .changelog/unreleased/features/4481-e2e-perturb-interval.md
- test/e2e/pkg/manifest.go
- test/e2e/pkg/testnet.go
- test/e2e/runner/main.go
- test/e2e/runner/perturb.go
> feat(e2e): Add perturbation interval to manifest and as command option

- abci/client/mocks/client.go
- crypto/mocks/batch_verifier.go
- crypto/mocks/pub_key.go
- internal/evidence/mocks/block_store.go
- light/rpc/mocks/light_client.go
- mempool/mocks/mempool.go
- p2p/mocks/peer.go
- proxy/mocks/app_conn_consensus.go
- proxy/mocks/app_conn_mempool.go
- proxy/mocks/app_conn_query.go
- proxy/mocks/app_conn_snapshot.go
- proxy/mocks/client_creator.go
- state/indexer/mocks/block_indexer.go
- state/mocks/block_store.go
- state/mocks/store.go
- state/txindex/mocks/tx_indexer.go
- types/time/mocks/source.go
> chore(mocks): regenerate mocks

- mempool/clist_mempool_test.go
> fix(mempool/tests): Fixes flakiness in a test related to mempool lanes. 

- mempool/reactor.go
I discovered this while profiling my P2P refactoring.
> perf(mempool): free memory immediately after calculating max

- test/e2e/pkg/manifest.go
- test/e2e/pkg/testnet.go
- test/loadtime/README.md
- test/loadtime/cmd/report/main.go
> feat(test): change default database to pebbledb

- mempool/reactor.go
- mempool/reactor_test.go
---
Use mutex
```
BenchmarkCurrentRedundancy
BenchmarkCurrentRedundancy/CurrentRedundancy
BenchmarkCurrentRedundancy/CurrentRedundancy-11             172358114            6.857 ns/op
BenchmarkCurrentRedundancy/IncFirstTimeTxs
BenchmarkCurrentRedundancy/IncFirstTimeTxs-11               227235248            5.264 ns/op
BenchmarkCurrentRedundancy/IncDuplicateTxs
BenchmarkCurrentRedundancy/IncDuplicateTxs-11               227110046            5.264 ns/op
```
Use atomic
```
BenchmarkCurrentRedundancy
BenchmarkCurrentRedundancy/CurrentRedundancy
BenchmarkCurrentRedundancy/CurrentRedundancy-11             1000000000           0.4400 ns/op
BenchmarkCurrentRedundancy/IncFirstTimeTxs
BenchmarkCurrentRedundancy/IncFirstTimeTxs-11               592631368            1.848 ns/op …
```
> perf(mempool): use atomic instead of mutex to improve perf

- CHANGELOG.md
Remove a paragraph on release candidates from CHANGELOG.md.
> fix(changelog): Remove paragraph on release candidates

- README.md
> docs(readme): update main README.md to accurately reflect maintenance team

- docs/guides/app-dev/indexing-transactions.md
- docs/references/config/genesis.json.md
- docs/tutorials/forum-application/3.send-message.md
> docs: fix typos

- CHANGELOG.md
---
Fix ASA-2025-002 name in changelog
> chore: fix security issue number in changelog

- .changelog/unreleased/bug-fixes/2025-002-block-part-validation.md
- types/part_set.go
- types/part_set_test.go
https://github.com/cometbft/cometbft/security/advisories/GHSA-r3r4-g7hq-pq4f
> fix(types): ASA-2025-002

- .changelog/unreleased/bug-fixes/2025-001-malicious-peer-can-make-node-stuck-in-blocksync.md
- internal/blocksync/pool.go
- internal/blocksync/pool_test.go
https://github.com/cometbft/cometbft/security/advisories/GHSA-22qq-3xwm-r5x4
> fix(blocksync): ASA-2025-001

- .github/workflows/cometbft-docker.yml
- .github/workflows/testapp-docker.yml
- DOCKER/Dockerfile
> fix(ci): Fix docker builds

- rpc/core/blocks.go
- rpc/core/blocks_test.go
- rpc/openapi/openapi.yaml
> docs(rpc): expand doc for `/blockchain` RPC

- .changelog/unreleased/bug-fixes/5028-e2e-testapp-tx.md
- test/e2e/app/app.go
- test/e2e/tests/app_test.go
> fix(test/e2e): fix TestApp_Tx

- docs/explanation/data-companion/intro.md
> docs: fixed broken link in data companion's intro section

- test/e2e/generator/random.go
- test/e2e/pkg/grammar/grammar-auto/parser/parser.go
> refactor(test): simplify map.copy

- config/config.go
---
Sets DOGProtocolEnabled from true to false. Future issue needs to be created to look into buggy behavior from DOG.
> chore: change default value of DOGProtocolEnabled from true to false

- .github/workflows/testapp-docker.yml
---
Adds dispatch-workflow to e2e image build to help debug why it's failing to build arm image on v0.38.x branch
> chore: add dispatch-workflow to e2e image build

- libs/strings/string.go
- libs/strings/string_test.go
> chore: restore strings package and mark deprecated

- test/e2e/docker/Dockerfile
- test/e2e/docker/Dockerfile.debug
> fix: e2e-node dockerfile install snappy and gflags libs

- test/e2e/docker/Dockerfile
> fix: add libs to e2e tests v0.38.x

- test/e2e/docker/Dockerfile
- test/e2e/docker/Dockerfile.debug
> fix: add libraries to e2e

- .changelog/v0.38.18/improvements/5251-precommit-metrics.md
- .changelog/v0.38.18/summary.md
- CHANGELOG.md
> chore: prep release for v0.38.18

- DOCKER/README.md
- rpc/core/blocks.go
- rpc/core/mempool.go
- rpc/core/tx.go
1. broken https://docs.cometbft.com/v0.38.x/introduction/quick-start.html
correct https://docs.cometbft.com/v0.38/guides/quick-start
2. broken https://docs.cometbft.com/v0.38.x/rpc/#/Info/blockchain 
correct https://docs.cometbft.com/v0.38/spec/rpc/#info-blockchain
3. broken https://docs.cometbft.com/v0.38.x/rpc/#/Info/header
correct https://docs.cometbft.com/v0.38/spec/rpc/#block
4. broken https://docs.cometbft.com/v0.38.x/rpc/#/Info/commit
correct https://docs.cometbft.com/v0.38/spec/rpc/#info-commit
5. broken https://docs.cometbft.com/v0.38.x/rpc/#/Info/block_results
correct https://docs.cometbft.com/v0.38/spec/rpc/#blockresults
6. broken https://docs.cometbft.com/v0.38.x/rpc/#/Tx/broadcast_tx_async
correct https://docs.cometbft.com/v0.38/spec/rpc/#unconfirmedtxs
7. broken …
> docs: update documentation links
