cometbft/cometbft

.github/workflows/coverage.yml
.github/workflows/e2e.yml
.github/workflows/govulncheck.yml
.github/workflows/lint.yml
.github/workflows/tests.yml

De-duplicates workflows on `release/*` branches in a similar way to https://github.com/informalsystems/tendermint/pull/13, but tailored to the current state of the branch.
---

ci: De-duplicate release workflows for v0.34.x

---

.changelog/unreleased/improvements/314-prio-mempool-badtxlog.md
.github/workflows/pre-release.yml
.github/workflows/release.yml
.goreleaser.yml
CHANGELOG.md
version/version.go

We're cutting an alpha of v0.34.27 in order to help facilitate integration with this release series.
Once we have confirmed that our QA is done, we will cut v0.34.27.
Also includes some of the changes from #317 in order to slightly improve the pre-release/release processes.
---

Release v0.34.27-alpha.1

---

.github/workflows/pre-release.yml
.github/workflows/release.yml
.goreleaser.yml
RELEASES.md

This updates the release and pre-release workflows to simplify, fix and clarify them. It also updates the `RELEASES.md` file to refer to unclog when building the changelog.
Needs to be backported to v0.37.x, since I'm updating this for the v0.34.x branch in #316.
---

ci: Update release and pre-release workflows and process

---

.changelog/unreleased/breaking-changes/230-p2p-peer-msg-type-and-metric.md
.changelog/unreleased/bug-fixes/9500-p2p-prevent-adding-errored-peers.md
.changelog/unreleased/improvements/230-p2p-peer-msg-type-and-metric.md
.changelog/unreleased/improvements/9171-cli-add-hard-flag.md
CHANGELOG.md
RELEASES.md
version/version.go

This PR is in preparation to cut pre-release `Release v0.37.0-alpha.3`.
* This is the version that will be used for the second iteration of QA on the `v0.37.0` branch. This QA iteration will be complementary to the one run in October 2022 (which was performed on Tendermint Core)
* As this is the first pre-release in the CometBFT `v0.37.x` branch, it can be used by other teams to integrate with it.
N.B.: Manually ran `e2e-nightly` on this branch [here](https://github.com/cometbft/cometbft/actions/runs/4228759518/jobs/7355172792).
---

Release v0.37.0-alpha.3

---

version/version.go

Cutting an additional alpha release to facilitate integration with the SDK.
The go package name changes have been rolled back (#351).
N.B.: Manually ran e2e-nightly on this branch [here](https://github.com/cometbft/cometbft/actions/runs/4228794979/jobs/7354951621).
---

Release v0.34.27-alpha.2

---

config/config.go
mempool/v1/mempool.go
mempool/v1/mempool_test.go

The priority mempool was marked as deprecated for v0.37.x in #259. The mempool config fields `TTLDuration` and `TTLNumBlocks` are only used by the priority mempool and will be deleted in v0.38.x, but we forgot to marked them as deprecated. This PR fixes it.

Mark priority mempool config fields as deprecated

---

.github/workflows/proto-lint.yml
proto/README.md

Attempts to fix the current failing proto lint test in CI.
---

ci: Remove Buf tokens from workflow

---

.changelog/unreleased/bug-fixes/383-txindexer-fix-slash-parsing.md
state/txindex/kv/kv.go
state/txindex/kv/kv_test.go

The transaction indexer indexes transaction events by creating a custom key containing the following: 
- event attribute key
- event attribute value
- txresult
- height
- event sequence
These elements are separated with a '/'. This however causes problems when the value (over which we have no control), contains a '/' . This PR fixes this by making sure to isolate the element containing the value.
The code was tested for backwards compatibility, making sure we can parse events indexed with older versions of Tendermint (without this fix). 
---

txindexer v0.34.x: Enable the indexer to parse slashes in query 

---

.github/workflows/e2e-manual.yml

Trying to run the manual E2E tests on `v0.34.x` results in this: https://github.com/cometbft/cometbft/actions/runs/4285915271
This PR fixes that (as evidenced in https://github.com/cometbft/cometbft/actions/runs/4286035807). This also shows that our nightly E2Es work for the current `v0.34.x` branch, from which I'll be cutting v0.34.27 shortly.
---

ci: Fix manual E2E test on v0.34.x

---

README.md

As of #419, we now use Go 1.20 on the `v0.37.x` branch.
This is already up-to-date on the `v0.37.x` branch itself: https://github.com/cometbft/cometbft/tree/v0.37.x#minimum-requirements
---

docs: Bump Go version for v0.37.x in readme on main

---

.github/workflows/pre-release.yml
.github/workflows/release-version.yml
.github/workflows/release.yml

Follow-up to #427. The workflow in #427 is merely informational, which is helpful, but can be bypassed. It's probably best to enforce this check when we push tags.
If the check fails, it will prevent the cutting of a release, meaning we'll have to delete the tag, fix the version number, and tag again.
---

ci: Enforce release version check when pushing tags

---

.github/workflows/e2e-long-main.yml

Contributes to #283
PR #375 introduces a new long-running manifest, used as part of the renaming-related QA for `v0.37.x`.
This adds a (preliminary) workflow to run this on `main` on a weekly basis (on Wed to Thu).
---

(preliminarily) add long-running weekly e2e workflow

---

.changelog/unreleased/bug-fixes/430-e2e-builting-commit-hash.md
Makefile
common.mk
test/e2e/Makefile

Closes #430
Extracted some Makefile logic into a common file (rather than copy-pasting) so that the e2e node is built with the flags allowing it to have a commit hash.
---

e2e: fix Makefile to produce commit_hash for builtin

---

docs/rfc/README.md
docs/rfc/rfc-100-abci-vote-extension-propag.md

Contributes to #444 
This PR is the first step to finishing the RFC containing vote extension propagation.
This first step simply consists in copying RFC017 over to RFC100 and updating all the references to Tendermint Core, retracted/unreleased versions (`v0.35.x`, `v0.36.x`) and links to the repo.
**IMPORTANT** Note for reviewers: when switching to the "Files changed" tab to review, please review the _last commit_ only. The first commit represents text already reviewed and approved last year, so I don't it is worth going through it again.
---

Migrate RFC 017 to RFC 100

---

docs/rfc/rfc-100-abci-vote-extension-propag.md
docs/rfc/tendermint-core/rfc-017-abci++-vote-extension-propag.md

Closes #444 
[Rendered](https://github.com/cometbft/cometbft/blob/sergio/444-rfc100-upgrade-path/docs/rfc/rfc-100-abci-vote-extension-propag.md)
In this PR:
* I retrieved the text from tendermint/tendermint#8484 and adapted it (new version names, new repo, etc.)
* I extended the "Upgrade Path" section to explain the changes needed in the main solutions/implementations described earlier in the document so that they work in blockchains that upgrade from ABCI 1.0 to ABCI 2.0.
---

RFC100: Upgrade path section

---

spec/abci/abci++_methods.md

Related to #97
This is a manual backport of #98
---

Backport small fix to ABCI 1.0 spec

---

consensus/metrics.gen.go
consensus/metrics.go
consensus/state.go
docs/core/metrics.md
state/metrics.gen.go
state/metrics.go

Contributes to #10
Partial cherry-pick of #8480
The rest of #8480 was backported for `v0.37.x`.
---

Backport vote extension metrics

---

.changelog/unreleased/breaking-changes/8664-move-app-hash-to-commit.md
UPGRADING.md
abci/tests/test_cli/ex1.abci
abci/tests/test_cli/ex1.abci.out
abci/tests/test_cli/test.sh
consensus/mempool_test.go
docs/app-dev/abci-cli.md
spec/abci/abci++_methods.md
state/execution.go

Contributes to #10
Partial cherry-pick of tendermint/tendermint#8664
The changes in this PR are the leftovers from backporting this functionality manually late last year.
---

Move `apphash`from `Commit`to `FinalizeBlock` (leftovers)

---

consensus/metrics.go

Related to #10
This is a leftover from backporting tendermint/tendermint#8480 prior to creating branch `v0.37.x` (in tendermint/tendermint#9168)
---

Backport resetting of vote metrics upon new round

---

.changelog/unreleased/bug-fixes/496-error-on-applyblock-should-panic.md
.github/workflows/govulncheck.yml
consensus/state.go
state/execution.go

Closes #490
Followed the call hierarchy of ABCI methods to make sure that reporting an error ultimately results in a crash/exit (also followed new methods in branch `feature/abci++vef`).
Found one blind spot that should be considered a bug, and should probably be backported. Hence, I'm opening this against `main` and not `feature/abci++vef`
---

ABCI calls should crash/exit in all cases when the call itself reports and error

---

state/execution.go
test/e2e/app/app.go

Contributes to #485
The current checks on vote extensions in the e2e app take vote extensions as something always optional. This is OK, but we can leverage the app to more thoroughly test several cases:
* upgrade path: make sure extensions are present _iff_ they are active
* test the subtleties of the upgrade height: `PrepareProposal`/`ProcessProposal` don't have extensions, `ExtendVote`/`VerifyVoteExtension` do.
* Decide what to do with `Nil` votes in a commit
---

Tighten the checks we do on vote extensions in e2e app

---

spec/core/data_structures.md

1. `InitialHeight` is specified twice
2. The contents of `Execute` refer to the parameter `state` not `s`

docs: improve Execute code block

---

consensus/metrics.gen.go
consensus/metrics.go
proxy/app_conn.go
scripts/qa/reporting/latency_plotter.py
scripts/qa/reporting/prometheus_plotter.py
test/e2e/networks/ci.toml

Contributes to #10
When testing in prometheus-enabled testnets, we caught two places where the metrics gathering were causing a panic.
This PR also includes adjustments to e2e `ci.toml` config that is able to trigger these bugs.
Finally (not important, but for the record), I have included the time window I used to extract metrics from the 200-node test.
---

Fixed two bugs related to metrics

---

spec/abci/abci++_methods.md
spec/core/data_structures.md
spec/p2p/messages/block-sync.md

Closes #544
With the changes to various protobufs in this branch, parts of the documentation had fallen out of sync.
This PR updates those spots to match the current protobufs.
---

Update description of profobuf definitions in the doc

---

.changelog/unreleased/breaking-changes/260-remove-priority-mempool-config.md
.changelog/unreleased/breaking-changes/260-remove-priority-mempool-proto.md
.changelog/unreleased/breaking-changes/6498-signerharness-set-home-dir.md
.changelog/unreleased/breaking-changes/8664-move-app-hash-to-commit.md
.changelog/unreleased/breaking-changes/9468-finalize-block.md
.changelog/unreleased/bug-fixes/386-quick-fix-needproofblock.md
CHANGELOG.md
UPGRADING.md
version/version.go

Prepares for our first alpha release of v0.38.0 with ABCI 2.0:
- [CHANGELOG rendered](https://github.com/cometbft/cometbft/blob/release/v0.38.0-alpha.1/CHANGELOG.md)
- [Upgrading guidelines rendered](https://github.com/cometbft/cometbft/blob/release/v0.38.0-alpha.1/UPGRADING.md)
- [Manual E2E run](https://github.com/cometbft/cometbft/actions/runs/4547643615) (for the `release/v0.38.0-alpha.1` branch) :heavy_check_mark: 
---

Release v0.38.0-alpha.1

---

.github/workflows/specs.yml

Closes https://github.com/informalsystems/quint/pull/768
As per conversation with @josef-widder today, this adds CI tests to run against the p2p quint spec. In fact, it adds a one-liner to run quint on any specs in the `/spec/` directory.
:warning: This PR is into PR #616 
---

Add GH workflows to test quint specs

---

spec/p2p/p2p.qnt

This PR into #616 serves two purposes:
1. Demonstrate that with our latest quint release, the CI test for spec fails when a test does. See https://github.com/cometbft/cometbft/actions/runs/4611928328/jobs/8152229802#step:5:59
2. Fix the failing test from #616.
@josef-widder This is fine to merge if you are happy with it! :) Thanks!
---

Fix failing P2P spec test

---

node/node.go
proto/tendermint/rpc/grpc/types.proto
rpc/grpc/client_server.go
rpc/test/helpers.go
test/app/grpc_client.go

Partially addresses #650.
Changelog entry will be added to the v0.38.x backport.
---

Mark the gRPC broadcast API as deprecated

---

.github/workflows/govulncheck.yml

Fixes the failing govulncheck workflows until such time that GitHub's runners catch up with the latest security release.
---

ci: Bump Go version for govulncheck to v1.20.3

---

.github/workflows/govulncheck.yml

Similar to #661, but for our `v0.34.x` branch.
---

ci: Bump Go version for govulncheck to v1.19.8

---

cmd/cometbft/commands/compact.go
cmd/cometbft/commands/gen_node_key.go
cmd/cometbft/commands/gen_validator.go
cmd/cometbft/commands/probe_upnp.go
cmd/cometbft/commands/reindex_event.go
cmd/cometbft/commands/replay.go
cmd/cometbft/commands/reset.go
cmd/cometbft/commands/root.go
cmd/cometbft/commands/show_node_id.go
cmd/cometbft/commands/show_validator.go

While working on #625 I discovered this. We have aliases for both types of commands, so I don't think there's any need to issue a warning here.
---

cmd: Remove snake case deprecation warning

---

CONTRIBUTING.md

Make explicit the team's policy for expected feedback on draft PRs.

Update contributing to draft PRS

---

consensus/reactor.go
test/e2e/Makefile
test/e2e/docker/Dockerfile

Closes #674
This PR contains changes in the test infra to repro #674, and the the fix needed to avoid the race condition.
Similarly to #673 I have pushed the commits that make up this PR one by one, so that those interested can track how I repro'ed the race condition using e2e tests, and how the fix prevents the race from happening again. To do so, click on the little ❌ or ✅ next to the relevant commits.
* Commit#1: Add race option to e2e tests for builtin app. We also activate "halt on error", so e2e tests are able to catch this (otherwise it just shows up in the logs, but the tests pass).
* Commit#2 (pushed together with Commit#1): Added a for loop to increase the probability of the race condition happening.
* Commit#3: Commit#2 was enough to repro the race locally, but e2e tests passed …

Fix race condition in `gossipVotesRoutine`

---

state/execution.go
state/execution_test.go
state/helpers_test.go

Closes #687 
Field `Time` was not being filled by `ApplyBlock`, and no UT was catching this.
---

Fill time in `FinalizeBlock`

---

light/provider/http/http.go
types/light.go

Closes #575.
This at least addresses the panic in the light client, instead turning it into a temporary error (i.e. that the node does not yet have the signed header for the requisite height, which is true here).
I've tested this patch on the `v0.34.x` branch and it prevents the panic, but instead causes the E2E tests to hang indefinitely. As such, I've logged #576.
The code change is identical across `main`, `v0.37.x` and `v0.34.x`, so backports should be clean. I'll add changelog entries on the backport branches prior to merging them.
---

light client: Address panic in response to empty signed header

---

.changelog/unreleased/breaking-changes/558-tm10011-B.md
crypto/merkle/proof.go

Closes #557, complementing the work done in #558.
---

Removes the public ComputeRootHash

---

test/e2e/app/app.go
test/e2e/app/snapshots.go
test/e2e/app/state.go

Attempts to close #712.
It appears as though a race condition has been triggered in the E2E app itself due to directly accessing application state inner variables.
Make the application state variables private to remove the temptation to access them directly from outside of the package and to highlight their use, and provide thread-safe getters to access the application state properties.
Running the full set of nightlies manually here: https://github.com/cometbft/cometbft/actions/runs/4698777347 :heavy_check_mark: 
---

e2e: Add thread-safe getters to app state

---

mempool/clist_mempool.go
state/execution.go
state/execution_test.go

Closes #739
Similar to #687, `ExecCommitBlock` is not filling the `time` field. Further, there was no UT catching this.
This PR add logic to an existing test case to check for that field. The test case is initially failing. When added the production fix (and fixing the test case logic), the test case passes.
---

Fill `time` field in `ExecCommitBlock`

---

.changelog/unreleased/breaking-changes/286-node.md
.changelog/unreleased/breaking-changes/286-p2p.md
CHANGELOG.md

Closes #747
Documents all the public methods removed from `Node` and modified in `Switch`, as part of #286.
---

Updated changelog with API changes in #286

---

rpc/jsonrpc/client/http_json_client.go

This addresses a [warning](https://github.com/cometbft/cometbft/security/code-scanning/1) from CodeQL
Struct `Client` defined [here](https://github.com/cometbft/cometbft/blob/feac56b62/rpc/jsonrpc/client/http_json_client.go#L124-L133) is used in some print/log functions.
As it contains a "password" field, we need to make sure it is not printed. This PR addresses that problem by having `Client` implement `fmt.Stringer`.
---

Struct `Client` exposes sensitive data

---

cmd/cometbft/commands/debug/kill.go

This addresses a [warning](https://github.com/cometbft/cometbft/security/code-scanning/2) from CodeQL
---

Unsafe int cast in `kill` command

---

docs/architecture/README.md
docs/architecture/adr-103-proto-versioning.md

Relates to #95.
Since we have had some relatively nuanced discussions around the Protobuf versioning, I thought it would be valuable to capture a summary of them in an ADR.
I've tried to keep this ADR as simple and focused as possible on the versioning aspect of the Protobuf changes, without mention of the package name change from `tendermint` -> `cometbft`, the generation of Go code into its own new module, the idea of switching from gogoproto to Google's Go code generator (this perhaps deserves its own ADR), or switching from Google's gRPC implementation to [Connect](https://connect.build/).
[Rendered](https://github.com/cometbft/cometbft/blob/thane/adr-protobuf-versioning/docs/architecture/adr-103-proto-versioning.md)
@mzabaluev has already been working on implementing this on the …

ADR-103: Protobuf definition versioning

---

docs/architecture/README.md
docs/architecture/adr-103-proto-versioning.md

Port of #772 to `main`.
If we don't reserve the numbers we may end up with clashes in future. If for some unlikely reason we decide not to version our protos, we can just mark this as rejected.
---

ADR-103: Protobuf definition versioning (#772)

---

test/e2e/pkg/infra/digitalocean/digitalocean.go

Contributes to #55
This PR is completing #796 (and tendermint/tendermint#9801) with the implementation of methods `StartNodes` and `StopTestnet` for the Digital Ocean infrastructure provider.
It uses ansible, matching the infra used in `cometbft/qa-infra`.
See how this will be used by the pre-release QA logic in cometbft/qa-infra#16
---

Digital Ocean implementation of `StartNodes` and `StopTestnet`

---

.changelog/unreleased/breaking-changes/774-state-indexerevent-remove-function-type.md
CHANGELOG.md
version/version.go

Changes in preparation for our second alpha release of v0.38.0:
- [CHANGELOG rendered](https://github.com/cometbft/cometbft/blob/release/v0.38.0-alpha.2/CHANGELOG.md)
- [Manual E2E run](https://github.com/cometbft/cometbft/actions/runs/5006380514) (for the `release/v0.38.0-alpha.2` branch)
---

Release `v0.38.0-alpha.2`

---

mempool/clist_mempool.go
mempool/mempoolTx.go
mempool/reactor.go

- Move `mempoolTx` struct to its own file and add methods `isSender` and `addSender` for handling the field `senders`.
- The content of the data structures `txs` and `txsMap` should be consistent.  
- We add new methods `getCElement`, `getMemTx`, and `removeAllTxs` to handle transactions that affect both this data structures.
-  We move all the logic of removing a tx to `RemoveTxByKey`.
- Some functions pass as argument the individual fields of `TxInfo` separately; we change these functions to pass `TxInfo` instead.
This PR is the first step to #895

mempool: slight refactor for improving readability

---

.golangci.yml
consensus/state.go
p2p/conn/secret_connection.go
p2p/upnp/probe.go
p2p/upnp/upnp.go

add config for depguard and fix nakedret error, for more [info](https://github.com/cometbft/cometbft/pull/865#discussion_r1215620869)
---

fix: lint fail when golangci-lint bump from v1.52.2 to v1.53.x

---

.golangci.yml
consensus/state.go
p2p/conn/secret_connection.go
p2p/upnp/probe.go
p2p/upnp/upnp.go

Backport of #908 to `v0.38.x`
---

backport: Fix lint failures on `v0.38.x`

---

.changelog/unreleased/bug-fixes/890-mempool-fix-cache.md
mempool/clist_mempool.go
mempool/clist_mempool_test.go

**Summary**
A transaction might appear twice in the mempool, i.e., it is present more than once in `txs`, while `txsMap` only links a single of these occurrences.  The bug happens when the cache overflows. 
**Context**
The bug is related to issues [#3865](https://github.com/tendermint/tendermint/issues/3865) and [#5281](https://github.com/tendermint/tendermint/issues/5281) in Tendermint. Both issues are closed with this fix. One may reproduce them easily in e2e, e.g.,
```
./build/generator -m v0.37.1:1 -d networks/generated/
./build/runner -f networks/generated/gen-0003.toml setup
find networks/generated/gen-0003/ -iname "config.toml" | xargs sed -i s,"cache_size = 10000","cache_size = 100", 
find networks/generated/gen-0003/ -iname "config.toml" | xargs sed -i s,"prepare_proposal_delay = …
```

Prevent a transaction to appear twice in the mempool

---

test/e2e/pkg/infrastructure.go
test/e2e/pkg/testnet.go
test/e2e/runner/test.go
test/e2e/tests/e2e_test.go

Closes #929
This PR fixes three problems:
* When there is a problem in env variables `INFRASTRUCTURE_FILE` and `INFRASTRUCTURE_TYPE`, we shouldn't _skip_ but fail. Otherwise we just hide a problem we should fix
* The code introducing `INFRASTRUCTURE_FILE` and `INFRASTRUCTURE_TYPE` (#796) had a couple of typos and so, didn't work (we didn't see this because of the first bullet, and so, e2e tests were not run)
* There was an ordering inconsistency problem in manifest- and testnet-related code, which caused the e2e tests to fail
---

e2e tests are being skipped; `INFRASTRUCTURE-*` bug; portGen inconsistency bug

---

.changelog/unreleased/improvements/955-lightclient-spec.md
spec/light-client/verification/Blockchain_003_draft.tla
spec/light-client/verification/LCVerificationApi_003_draft.tla
spec/light-client/verification/Lightclient_003_draft.tla
spec/light-client/verification/MC4_3_correct.tla
spec/light-client/verification/MC4_3_faulty.tla
spec/light-client/verification/MC4_4_correct.tla
spec/light-client/verification/MC4_4_correct_drifted.tla
spec/light-client/verification/MC4_4_faulty.tla
spec/light-client/verification/MC4_4_faulty_drifted.tla
spec/light-client/verification/MC4_5_correct.tla
spec/light-client/verification/MC4_5_faulty.tla
spec/light-client/verification/MC4_6_faulty.tla
spec/light-client/verification/MC4_7_faulty.tla
spec/light-client/verification/MC5_5_correct.tla
spec/light-client/verification/MC5_5_correct_peer_two_thirds_faulty.tla
spec/light-client/verification/MC5_7_faulty.tla
spec/light-client/verification/MC7_5_faulty.tla
spec/light-client/verification/MC7_7_faulty.tla
spec/light-client/verification/typedefs.tla

This PR updates the type annotations in the TLA+ specification of the light client, so it works with the latest version of Apalache v0.40.2. I did not open any issue, as this is simply about updating the annotations.

Update the type annotations in the light client spec

---

test/e2e/docker/Dockerfile

Explicitly sets the base image to Debian Bullseye for now to get the E2E Docker image building again.
Builds have been failing on `main` and `v0.38.x` as a result of the recent base image change for the `golang:1.20` image from Debian Bullseye to Bookworm. This has already been fixed on `v0.37.x` and `v0.34.x` in #972 and #973.
---

test/e2e: Fix Docker image build

---

abci/types/types.go
types/block.go
types/results.go

Closes #889
Remove one implementation of `deterministicExecTxResult` by deleting one copy and rendering the other visible outside its package.
---

Remove duplicate function `deterministicExecTxResult`

---

.changelog/unreleased/improvements/857-make-handshake-cancelable.md
consensus/replay.go
node/node.go
node/setup.go

it'll make the handshake work with graceful shutdown(see: https://github.com/cosmos/cosmos-sdk/issues/16202)
handshake could be a long running process if there are many local blocks to replay, for example we use it to do profiling.
this one can be backport to 0.37 and 0.34.
---
---

feat: make handshake cancelable (backport #857)

---

.changelog/unreleased/improvements/1022-log-invalid-vote-extension.md
consensus/state.go

When vote validation errors are processed and "swallowed" without adding the vote, it's important to report them in the logs at level that is normally enabled by operators. This also helps troubleshooting e2e test failures.
---

Bump logs on non-fatal vote validation failures to Info level

---

.github/CODEOWNERS

I noticed that we hadn't added the DevRel team to our CODEOWNERS file yet. This PR updates it.
Also, our org name was changed from "CometBFT" to "cometbft" some time ago, and while this is a purely cosmetic change it probably makes sense to keep it consistent.
---

Update codeowners to include DevRel team

---

CHANGELOG.md
version/version.go

Changes in preparation for the second release candidate (RC) of v0.38.0:
:book: [CHANGELOG rendered](https://github.com/cometbft/cometbft/blob/release/v0.38.0-rc2/CHANGELOG.md)
[Manual E2E Run](https://github.com/cometbft/cometbft/actions/runs/5375383841)
---

Release `v0.38.0-rc2`

---

abci/client/mocks/client.go
abci/types/mocks/application.go
evidence/mocks/block_store.go
go.mod
go.sum
light/rpc/mocks/light_client.go
mempool/mocks/mempool.go
p2p/mocks/peer.go
proxy/mocks/app_conn_consensus.go
proxy/mocks/app_conn_mempool.go
proxy/mocks/app_conn_query.go
proxy/mocks/app_conn_snapshot.go
proxy/mocks/client_creator.go
state/indexer/mocks/block_indexer.go
state/mocks/block_store.go
state/mocks/evidence_pool.go
state/mocks/store.go
state/txindex/mocks/tx_indexer.go
statesync/mocks/state_provider.go

Supersedes #995.
We have to do this manually because the code that the new version of mockery generates is subtly (but not meaningfully, afaict) different.
---

deps: Manually bump github.com/vektra/mockery/v2 from 2.29.0 to 2.30.1

---

types/part_set.go

Hi, I'm looking at the cometBFT code and came across the annotation that I found awkward.
In `types/params.go`, the value of BlockPartSizeBytes is 65536 (about 64kB). 
In the function ```func NewPartSetFromData(data []byte, partSize uint32) *PartSet``` in `types/part_set.go`, the function uses the parameter `partSize` which is the value of BlockPartSizeBytes.
However, the annotation says it's 4kB, so I'm doing a pull request to fix to 64kB.

Update the annotation of part_set.go

---

.github/workflows/build.yml
.github/workflows/check-generated.yml
.github/workflows/codeql.yml
.github/workflows/e2e.yml
.github/workflows/govulncheck.yml
.github/workflows/lint.yml
.github/workflows/proto-lint.yml
.github/workflows/tests.yml

In order to enable merge queues on `main`, we first need to add the `merge_group` workflow trigger.
---

ci: Trigger workflows on merge group

---

UPGRADING.md
cmd/cometbft/commands/run_node.go
config/config.go
config/toml.go
docs/core/configuration.md
node/node.go
spec/p2p/legacy-docs/config.md

This reverts commit f12588aab1f1b52ffa82ed143676d69e2fab7bf4.
This configuration parameter was first introduced in the `v0.35.x` branch (https://github.com/tendermint/tendermint/pull/6372), then forward-ported to `main` after the retraction of this release (https://github.com/tendermint/tendermint/pull/9680).
More recently, users have requested its inclusion on the `v0.37.x` release branch (https://github.com/cometbft/cometbft/issues/1016). However, when backporting this commit from main (https://github.com/cometbft/cometbft/pull/1019), the reviewers have observed a number of minor issues both in the code and in the documentation of the introduced parameter: 
- The documentation of the introduced configuration parameter is imprecise and it is not following the proper naming adopted for …

Revert "config: add bootstrap peers (#9680)"

---

.changelog/unreleased/breaking-changes/1120-node-api-cleanup.md
node/node.go
node/setup.go
p2p/switch.go

Reverts #286 to reintroduce access to reactors via the `Node`.
To be backported to v0.38.
---

node: Revert removal of public reactor accessors

---

.github/workflows/codeql.yml

Seems as though the CodeQL checks are failing on `merge_group` for some reason: https://github.com/cometbft/cometbft/actions/runs/5555159575/jobs/10145922428 - seems like it can't find the code it's supposed to check.
I'm not sure if that check's compatible with merge queues, so I'll disable this check for now. It still gets run on pull requests and pushes to `main` as it always was.
---

ci: Disable CodeQL check in merge queues

---

.changelog/unreleased/features/9680-config-introduce-bootstrappeers.md
CHANGELOG.md
version/version.go

:book: [CHANGELOG rendered](https://github.com/cometbft/cometbft/blob/release/v0.38.0-rc3/CHANGELOG.md)
Applies two reverts:
- #1120 
- #1121 
E2E nightlies manual run for this branch: https://github.com/cometbft/cometbft/actions/runs/5555876254
---

Release v0.38.0-rc3

---

docs/architecture/README.md
docs/architecture/adr-107-betaize-proto-versions.md

Improvement proposal for #95 to make protobuf versioning cleaner on the way to the 1.0 release.
[Rendered](https://github.com/cometbft/cometbft/blob/mikhail/adr-betaize-proto-versions/docs/architecture/adr-107-betaize-proto-versions.md)

ADR 107: Rename proto versions to pre-v1 betas

---

docs/rfc/README.md
docs/rfc/rfc-104-actor-model.md

:book: [Rendered](https://github.com/cometbft/cometbft/blob/thane/rfc-internal-messaging/docs/rfc/rfc-104-actor-model.md)
I'm submitting this as an RFC as part of a broader effort to consider different options in simplifying Comet's internal concurrency model (which is unnecessarily complex right now). The actor model is only one possible option, and I thought it would be worth capturing some of my past explorations on employing the model somewhere.
Again, this is an _RFC_ and not an ADR because it's merely exploring the solution space as opposed to proposing a concrete course of action. The conclusion of the RFC is that adopting an actor framework is _not_ desirable for a whole host of reasons, and neither is adopting a full-blown actor model. We can, however, extract some principles or …

RFC 104: Internal messaging using the actor model

---

.github/mergify.yml

Mergify's automerge functionality clashes with merge queues and automatic Dependabot updates sometimes, which is particularly annoying. We don't need it on `main` any more.
---

ci: Remove Mergify automerge

---

.changelog/unreleased/bug-fixes/1175-consensus-remove-unlock-behavior.md
consensus/common_test.go
consensus/state.go
consensus/state_test.go
internal/test/block.go
spec/consensus/signing.md
types/block.go
types/canonical.go
types/event_bus.go
types/event_bus_test.go
types/events.go
types/vote.go
types/vote_set_test.go

- Fixes part of https://github.com/cometbft/cometbft/issues/1171 by implementing [this logic](https://github.com/cometbft/cometbft/blob/127d2fb78b271847de4dc0aaca7825bca98a2cb9/docs/introduction/README.md?plain=1#L305-L306)
- Largely copies logic from https://github.com/tendermint/tendermint/pull/6954
-  (-) Doesn't include the renaming change of `blockID.IsZero()` to `blockID.IsNil()`
- (-) Doesn't rename tests to include underscores.
---

consensus: remove logic to unlock block on +2/3 prevote for nil

---

consensus/state.go
consensus/state_test.go

Closes #1207 
Small change, suggested [here](https://github.com/tendermint/tendermint/pull/6954/files/51db3f86c5ef40c9988255913a3de32211d2e5b6#r713821738), that makes the correctness of `enterCommit` independent from its (only ATM) callsite.
---

Add check for non-`nil` in `enterCommit`

---

consensus/state.go
state/execution.go

Contributes to #907 
While troubleshooting today, a key info we needed was missing in our Info logs
Tested via e2e:
```
full02       | I[2023-07-04|14:27:28.059] received proposal                            module=consensus proposal="Proposal{1059/1 (2DF98F8362C45180CEF86031DA7C5CBA7AAA2DBD52FF889DC80C508DFEC5CDC7:1:77AEA1FD157
2, -1) 24AD3C5810DE @ 2023-07-04T14:27:27.804019764Z}" proposer=07EB27AE0D0607DB338F1F102B3C25049FE04C68
```
---

Log proposer's address when correctly accepting a proposal

---

.changelog/unreleased/bug-fixes/1175-consensus-prevote-improve-logic.md
.changelog/unreleased/bug-fixes/1175-consensus-remove-unlock-behavior.md
consensus/state.go
consensus/state_test.go
types/vote_set_test.go

Contributes to #1171
Mechanical forward-port. For a thorough explanation of the contents (and context) of this PR, please check the original PR (tendermint/tendermint#6986) and original issue (tendermint/tendermint#6850).
N.B. The PR is currently open on a temporary base branch to only display the changes proper to the forward-port. When #1175 is merged, the base branch is to be changed to `main` (@BrendanChou)
---

Forward-port: update state to prevote `nil` when proposal block does not match locked block

---

.changelog/unreleased/minimum-go-version/1244-bump-go-version.md
.github/workflows/build.yml
.github/workflows/check-generated.yml
.github/workflows/e2e-long-main.yml
.github/workflows/e2e-manual-multiversion.yml
.github/workflows/e2e-manual.yml
.github/workflows/e2e-nightly-37x.yml
.github/workflows/e2e-nightly-38x.yml
.github/workflows/e2e-nightly-main.yml
.github/workflows/e2e.yml
.github/workflows/fuzz-nightly.yml
.github/workflows/govulncheck.yml
.github/workflows/lint.yml
.github/workflows/pre-release.yml
.github/workflows/release-version.yml
.github/workflows/release.yml
.github/workflows/tests.yml
DOCKER/Dockerfile
README.md
UPGRADING.md
docs/guides/go-built-in.md
docs/guides/go.md
go.mod
go.sum
test/e2e/docker/Dockerfile
test/e2e/docker/Dockerfile.debug

Partially addresses #1245.
---

chore: Bump minimum Go version on `main` to v1.21

---

rpc/grpc/client/client.go
rpc/grpc/client/privileged/privileged.go
test/e2e/tests/grpc_test.go

As @glnro pointed out, this was an oversight on my part. Should fix it now.
---

ADR 101: Add `Close` method to gRPC client

---

CONTRIBUTING.md

Closes #1249.
Adds some lightweight/simple logging guidelines to the contributing guidelines.
:book: [Rendered](https://github.com/cometbft/cometbft/blob/thane/1249-logging-guidelines/CONTRIBUTING.md#logging)
---

docs: Add logging guide to contributing guidelines

---

.changelog/unreleased/improvements/1264-log-app-hash-as-hex.md
state/execution.go

chore: log `app_hash` as hex

---

node/node.go
rpc/grpc/server/services/pruningservice/service.go
state/errors.go
state/execution.go
state/export_test.go
state/pruner.go
state/store_test.go
store/store_test.go
test/e2e/generator/generate.go
test/e2e/networks/ci.toml
test/e2e/pkg/manifest.go
test/e2e/pkg/testnet.go
test/e2e/runner/setup.go
test/e2e/runner/test.go
test/e2e/tests/block_test.go
test/e2e/tests/grpc_test.go

Alternative to #1261.
When we make the assumption that the retain heights will be available in the state store, and the pruner knows whether or not the data companion is enabled, we can simplify the code to a certain degree.
I've tried to structure this PR such that it can be reviewed commit by commit, but it may be easier to just review it in one go. I'm happy to also walk folks through it.
~The CI E2E test has been failing for me locally, so I'll mark this as ready to review once it passes.~
---

ADR 101: Refactor height check-related logic and tests

---

.changelog/unreleased/bug-fixes/1017-remove-genesis-persistence-in-state-db.md
blocksync/reactor_test.go
consensus/byzantine_test.go
consensus/common_test.go
consensus/reactor_test.go
consensus/replay_test.go
node/node.go
node/node_test.go
node/setup.go
state/mocks/store.go
state/state_test.go
state/store.go
state/store_test.go
state/tx_filter_test.go
store/store_test.go

This avoids saving the genesisDoc to database. When using goleveldb and ~4GiB+ genesis files, it causes a panic during snappy encoding (`panic: snappy: decoded block is too large`). We run into this with a large Ethermint state in our mainnet exports.
The main file to review is `node/setup.go`, with changes mostly from https://github.com/tendermint/tendermint/pull/6554
Contributes to #1037
---

Remove genesis persistence in state db

---

.changelog/unreleased/bug-fixes/1017-remove-genesis-persistence-in-state-db.md
blocksync/reactor_test.go
consensus/byzantine_test.go
consensus/common_test.go
consensus/reactor_test.go
consensus/replay_test.go
node/node.go
node/node_test.go
node/setup.go
state/mocks/store.go
state/state_test.go
state/store.go
state/store_test.go
state/tx_filter_test.go
store/store_test.go

PR #1017  was failing our e2e tests. The fix was not trivial hence reverting this PR. A fix will follow this revert.
This reverts commit ae9826ed75ee411c0d809797ce209ee770c15c4f.
---

genesis:revert removing the genesis file out of the DB

---

.changelog/unreleased/improvements/1017-remove-genesis-persistence-in-state-db.md
node/node_test.go
node/setup.go

Contributes to #1037
This is a more self-contained implementation of #1017.
No API changes, it keeps the old logic when retrieving the genDoc at star-up time.
This is passing the e2e nightly tests that were failing in #1017.
---

Re-implement removal of genesis persistence in state db

---

consensus/state_test.go

This PR adds a unit test that highlights and documents a corner case in the operation of the consensus protocol.
Considering the abstract description of Tendermint consensus algorithm ([here](https://arxiv.org/pdf/1807.04938.pdf)), the conditions for a node to issue a `Precommit` for a value (block) and update its locked value to this value are:
```
36:  upon 〈PROPOSAL, h_p , round_p, v, ∗〉 from proposer(hp , round_p) AND 2f + 1 〈PREVOTE, hp, round_p , id(v)〉 while valid(v) ∧ step_p ≥ prevote for the first time do
```
This means that for issuing a `Precommit` and locking a value in a round, the node needs to receive a matching `PROPOSAL` message from the round's proposer. In terms of the implementation, this means that the node has to receive a `Proposal` message proposing the `BlockID` …

consensus: test for precommit/locking corner case

---

.changelog/unreleased/features/1334-metrics-for-index-pruning.md
state/metrics.gen.go
state/metrics.go
state/pruner.go

TxIndexer and BlockIndexer pruning metrics

---

.gitignore

~~`.gitignore` includes `test/p2p/data` but this directory is never created.~~ What is needed is an entry for `test/e2e/data` which  occurs when running e2e networks.
The line for `test/p2p/data` [was added](https://github.com/tendermint/tendermint/pull/5918) with the fuzz tests. I run the fuzz tests and they don't create this directory.

Add test/e2e/data to gitignore

---

mempool/mempool.go
mempool/reactor_test.go

Constants `UnknownPeerID` and `MaxActiveIDs` are leftovers from #1146.
---

mempool: Remove unused peerID-related constants

---

.changelog/unreleased/build/1351-bump-go-120.md
.github/workflows/check-generated.yml
.github/workflows/coverage.yml
.github/workflows/e2e-manual.yml
.github/workflows/e2e-nightly-34x.yml
.github/workflows/e2e.yml
.github/workflows/fuzz-nightly.yml
.github/workflows/govulncheck.yml
.github/workflows/lint.yml
.github/workflows/pre-release.yml
.github/workflows/release-version.yml
.github/workflows/release.yml
.github/workflows/tests.yml
.golangci.yml
DOCKER/Dockerfile
Makefile
README.md
UPGRADING.md
docs/guides/upgrading-from-tm.md
go.mod
go.sum
p2p/conn/connection.go
test/docker/Dockerfile
test/e2e/docker/Dockerfile

Follows from the govulncheck failure in #1342, since Go v1.19 has reached EOL.
---

Bump Go version used in `v0.34.x` to v1.20

---

spec/abci/abci++_app_requirements.md

Additions to the description of the `BlockParams.MaxBytes` consensus parameter on the ABCI documentation.
Rendered: https://github.com/cometbft/cometbft/blob/cason/doc-maxbytes-param/spec/abci/abci%2B%2B_app_requirements.md

doc: improve documentation of BlockParams.MaxBytes

---

spec/abci/apps.md

This is a manual backport #1405.
Rendered: https://github.com/cometbft/cometbft/blob/cason/doc-maxbytes-param-v0.34.x/spec/abci/apps.md
---

doc: improve documentation of BlockParams.MaxBytes (backport of #1405)

---

.changelog/unreleased/breaking-changes/1411-bump-p2p-version.md
version/version.go

Related to #26
#904 introduced a new p2p message: `HasProposalBlockPartMessage`. This will require a coordinated upgrade (not a big deal, this has been the norm from `v0.34.x` to `v0.37.x`, and from `v0.37.x` to `v0.38.x`).
In addition, for safety (to avoid misunderstandings during node handshake), we need to bump the p2p version.
This is usually done as part of the [release process](https://github.com/cometbft/cometbft/blob/86c07f20f/RELEASES.md?plain=1#L205), but, as suggested [here](https://github.com/cometbft/cometbft/pull/904#issuecomment-1738812069), let's do it now to make sure we don't forget.
---

Bump p2p version following introduction of `HasProposalBlockPartMessage`

---

crypto/armor/armor.go
crypto/armor/armor_test.go
crypto/ed25519/ed25519.go
crypto/encoding/codec.go
crypto/merkle/proof.go
crypto/merkle/proof_key_path.go
crypto/merkle/proof_op.go
crypto/merkle/proof_test.go
crypto/merkle/proof_value.go
crypto/sr25519/batch.go
crypto/sr25519/privkey.go
crypto/xchacha20poly1305/xchachapoly.go
crypto/xsalsa20symmetric/symmetric.go
p2p/conn/secret_connection_test.go

Exports errors from the `crypto` module per #1140 for the following submodules:
On an unrelated note: I noticed that the following `break` statement is [ineffectual if the intention is to break out of the outer loop](https://go.dev/ref/spec#Break_statements). I am not sure if this posses a problem.
https://github.com/cometbft/cometbft/blob/77fa8a00c524474a055d95bd5d522491c3bdbea3/crypto/merkle/proof.go#L207-L217
---

crypto: export errors

---

rpc/grpc/client/client.go
rpc/grpc/client/privileged/privileged.go
test/e2e/tests/grpc_test.go

Partially addresses #1419:
Should not conflict with #1473, so they can be merged in any order.
---

grpc: backport Add `Close` method to gRPC client (#1251) to v0.38.x-experimental

---

state/execution.go
state/state.go

Makes the BuildExtendedCommitInfo and BuildLastCommitInfo functions public,
and makes them take a validator set instead of the store as an input.
These functions are useful to also call from outside of CometBFT if one has a need to obtain the CommitInfo structs,
in particular I am using them in a mock for cometbft.
---

Make BuildLastCommitInfo and BuildExtendedCommitInfo public

---

test/e2e/pkg/infra/docker/docker.go

After adding new gRPC endpoints in ADR-101, we introduced different aliases for the docker ports. This change was not reflected in the docker template for images with upgraded versions (`_u`) .
This change needs to be backported to `v0.38.x-experimental` . 
---

e2e:Fix docker port alias

---

.changelog/unreleased/improvements/904-gossip-sleep-had-block-part.md
CHANGELOG.md
docs/rfc/tendermint-core/rfc-017-abci++-vote-extension-propag.md

It's currently written "bandwith" in 3 places
Guessing this doesn't need a changelog entry?

fix spelling of bandwidth

---

docs/rfc/README.md
docs/rfc/rfc-106-separate-stateful-methods.md

On added drag of some "convenience" methods in the data companion API.
[Rendered](https://github.com/cometbft/cometbft/blob/mikhail/rfc-separate-stateful-methods/docs/rfc/rfc-106-separate-stateful-methods.md)

RFC 106: non-idempotent methods in data companion

---

test/e2e/tests/grpc_test.go

Manual backport of #1492
* Initial attempt to decrease the flakiness
* Remove loop over blocks from archive nodes
* Removed needless loop through blocks
* removed the first block test (#1492)
---------
---

e2e-v0.38-experimental: Fix flakiness in grpc tests due to pruning (#1492)

---

consensus/reactor_test.go

Simple test improvement. Failure reporting prints the numbers.
---

use assert.Greater instead of Equal for better failure reporting

---

.changelog/unreleased/features/1512-metric-mempool-size-bytes.md
mempool/clist_mempool.go
mempool/metrics.gen.go
mempool/metrics.go

Relates to #1061.
This PR exposes a new metric `SizeBytes` for the total size of the mempool in bytes. We already keep track of this value internally, in the variable `txsBytes`. Currently there is the metric `Size` for the size of the mempool in number of transactions.
---

mempool: Add metric size of pool in bytes

---

proto/tendermint/services/block/v1/block.proto
proto/tendermint/services/block/v1/block_service.proto
proto/tendermint/services/block_results/v1/block_results.proto
proto/tendermint/services/block_results/v1/block_results_service.proto
proto/tendermint/services/version/v1/version.proto
proto/tendermint/services/version/v1/version_service.proto
spec/abci/README.md
spec/abci/abci++_basic_concepts.md
spec/abci/abci++_client_server.md
spec/abci/abci++_comet_expected_behavior.md

Documentation and proto file fix ups for #1330:
* Change the URL to the ABCI proto file on GitHub in documentation
to point to the latest versioned package.
* Remove the `go_package` directives from the legacy `tendermint.*` proto files.

Update proto file references to follow renaming/versioning

---

.changelog/unreleased/improvements/1558-experimental-gossip-limiting.md
config/config.go
config/toml.go
mempool/metrics.go
mempool/reactor.go
mempool/reactor_test.go
test/e2e/pkg/manifest.go
test/e2e/pkg/testnet.go
test/e2e/runner/setup.go

Closes #1058
Complements the work done in #1558: adds two independent configuration values for limiting outbound gossip connections, for persistent peers and non-persistent peers. Unconditional peers are not affected by this feature.
---

mempool: Limit gossip connections to persistent and non-persistent peers (experimental)

---

docs/guides/go-built-in.md

Small correction of the guide to setup a built-in cometbft application. Current example code gave me an error (DefaultDBProvider does not exist in nm/node), I believe this should be cfg/config instead. The code bellow is working for me.
I did not add anything to the changelog as that seems kinda unnecessary for such a small change to just the docs.
---

fix: docs: default db provider moved from node to config

---

go.mod
test/e2e/app/go.mod
test/e2e/go.mod
test/loadtime/go.mod

CodeQL seems to be complaining about some recent changes that `go mod tidy` produces.
Seems to be fixed after removing the patch version numbers in the go.mod files: https://github.com/cometbft/cometbft/actions/runs/6852623623/job/18631585336
---

chore: ADR 109: go mod tidy

---

go.mod
go.sum

Companion to https://github.com/cometbft/cometbft/pull/1603
Fixes the following compilation error:
```
../../../go/pkg/mod/github.com/cosmos/gogoproto@v1.4.6/proto/merge.go:123:28:
type func(x *descriptorpb.FileDescriptorProto, y
*descriptorpb.FileDescriptorProto) bool of func(x, y
*descriptorpb.FileDescriptorProto) bool {…} does not match inferred type
func(a *descriptorpb.FileDescriptorProto, b
*descriptorpb.FileDescriptorProto) int for func(a E, b E) int
```
go: go1.21.3 darwin/amd64
cometbft: v0.38.0
---

deps: upgrade gogoproto to 1.4.11

---

light/provider/http/http_test.go

Closes: #1582 
This PR removes the wrong assertion and decreases likelihood of a block expected to be from the future to have actually been already created and causing another assertion to fail.
---

Fixes assertion in failing test

---

.changelog/unreleased/improvements/1558-experimental-gossip-limiting.md
abci/example/kvstore/helpers.go
config/config.go
config/toml.go
mempool/metrics.gen.go
mempool/metrics.go
mempool/v0/clist_mempool_test.go
mempool/v0/reactor.go
mempool/v0/reactor_test.go
test/e2e/pkg/manifest.go
test/e2e/pkg/testnet.go
test/e2e/runner/setup.go

* Experimental - Reduce # of connections effectively used to gossip transactions out (#1558)
* maxpeers for mempool
* mempool: fix max_peers bcast routine active flag
* Use semaphore to limit concurrency
* Rename MaxPeers to MaxOutboundPeers
* Add max_outbound_peers to config toml template
* Rename in error message
* Renams the parameter to highlight its experimental nature. Extend the AddPeer method to return an error. Moves the semaphone to outside the broadcast routine
* reverting the addition of error to AddPeer. It fails if the context is done and handling this case will be done some other time, when an actual context is passed into acquire.
* reverting the addition of error to AddPeer. It fails if the context is done and handling this case will be done some other time, when an …

Backports #1558 and #1584 to 0.37.x (#1592)

---

mempool/reactor_test.go

Contributes to #1620 
This commit makes the test in 0.38 be the same as in main, that is, to ignore the order of transactions in the receiving reactor.
#1620 is not fixed by this PR. Once #1620 is fixed, it needs to be back ported.
#1629 does the same work as this PR, but for 0.37
---

Fixes back port of test in 0.38

---

mempool/v0/reactor_test.go

Contributes to #1620
This commit makes the test in 0.37 be the same as in main, that is, to ignore the order of transactions in the receiving reactor.
#1620 is not fixed by this PR. Once #1620 is fixed, it needs to be back ported as well.
#1627 does the same work as this PR, but for 0.38
---

Fixes back port of test in 0.37

---

.changelog/unreleased/improvements/1558-experimental-gossip-limiting.md
abci/example/kvstore/helpers.go
config/config.go
config/toml.go
mempool/metrics.go
mempool/v0/clist_mempool_test.go
mempool/v0/reactor.go
mempool/v0/reactor_test.go
test/e2e/pkg/manifest.go
test/e2e/pkg/testnet.go
test/e2e/runner/setup.go

Backport #1558 and #1584 to v0.34.x
Cheery-picked from the backport to v0.37.x (#1611)
* mempool: Limit gossip connections to persistent and non-persistent peers (experimental) (#1584)
* Experimental - Reduce # of connections effectively used to gossip transactions out (#1558)
---

experimental mempool: Backport #1558 and #1584 to 0.34.x

---

mempool/metrics.go

Running the nightlies on #1641 picked up a segmentation fault which I traced to the fact that we're not constructing a gauge related to the `size_bytes` metric (from #1568). In the v0.34 line, we need to manually construct these gauges.
Running the E2E nightlies manually on this branch to validate that this fixes the problem: https://github.com/cometbft/cometbft/actions/runs/6897189522
---

mempool: Add missing gauge constructor for `size_bytes` metric

---

.changelog/v0.34.30/build/1351-bump-go-120.md
.changelog/v0.34.30/features/1512-metric-mempool-size-bytes.md
.changelog/v0.34.30/improvements/1210-close-evidence-db.md
.changelog/v0.34.30/improvements/1558-experimental-gossip-limiting.md
.changelog/v0.34.30/improvements/857-make-handshake-cancelable.md
.changelog/v0.34.30/summary.md
.changelog/v0.37.3/breaking-changes/1113-rm-upnp.md
.changelog/v0.37.3/bug-fixes/1529-indexer-respect-height-params-on-query.md
.changelog/v0.37.3/features/1057-bootstrap-state-api.md
.changelog/v0.37.3/features/1512-metric-mempool-size-bytes.md
.changelog/v0.37.3/improvements/1210-close-evidence-db.md
.changelog/v0.37.3/improvements/1558-experimental-gossip-limiting.md
.changelog/v0.37.3/improvements/475-upgrade-go-schnorrkel.md
.changelog/v0.37.3/improvements/857-make-handshake-cancelable.md
.changelog/v0.37.3/summary.md
.changelog/v0.38.1/bug-fixes/1529-indexer-respect-height-params-on-query.md
.changelog/v0.38.1/features/1512-metric-mempool-size-bytes.md
.changelog/v0.38.1/improvements/1558-experimental-gossip-limiting.md
.changelog/v0.38.1/summary.md
CHANGELOG.md

Pulls the changelog entries into `main` from #1639, #1640 and #1641.
[Rendered](https://github.com/cometbft/cometbft/blob/thane/update-changelog/CHANGELOG.md)
---

Update changelog on `main` with new releases

---

proto/README.md

Updates the `proto/README.md` file such that it makes more sense when published to the Buf registry.
This currently refers to v0.38.x and will be backported to all the major release branches. The corresponding changes for v1 should be included on the `feature/proto-upgrade` branch such that they update this README when the feature branch is merged.
[Rendered](https://github.com/cometbft/cometbft/blob/thane/update-protos-readme/proto/README.md)
---

proto: Update README

---

.github/workflows/e2e-nightly-34x.yml

The v0.34.x nightly build has been failing for a few days now, and it seems like it's because we're using the wrong version of Go to build it.
The workflow on the `main` branch is the one that's executed nightly.
---

ci: Fix v0.34 nightly build

---

go.mod
go.sum

After chatting with @julienrbrt, it seems a better idea to not bump our `go.mod` minimum required version for the lifespan of a release series. We are, however, free to use the latest version of Go in building and testing our software (as we currently do for the v0.37.x line).
I'll follow up with a PR/discussion around how we should go about updating Go versions.
---

v0.37.x: Restore minimum Go version

---

.changelog/unreleased/improvements/1715-validate-validator-address
internal/state/store_test.go
internal/store/store_test.go
types/validator.go
types/validator_set_test.go
types/validator_test.go

Manual backport of #1715 to `v1.x`, since I forgot to add the Mergify config until #1724.
---

backport to v1.x: types: validate Validator#Address field (#1715)

---

go.mod
go.sum
test/e2e/docker/Dockerfile
test/e2e/docker/Dockerfile.debug

Should hopefully address the failing Docker E2E image build: https://github.com/cometbft/cometbft/actions/runs/7088345111/job/19290619890
See also https://hub.docker.com/r/cometbft/cometbft-db-testing/tags - cometbft-db-testing v0.9.1 is now built for both `linux/amd64` and `linux/arm64`, where previous versions were only built for `linux/amd64`.
---

deps: Bump cometbft-db to v0.9.1

---

proto/README.md

Clean up for #1733
The Markdown processor used on the Buf Schema Registry is more
strict than GitHub Flavored Markdown and renders HTML comments
visible as text.
Use the link label syntax to hide comment text.

proto: make comment in README more Markdowny

---

spec/core/encoding.md

function "emptyHash" in the example was written "empthHash"

Fix typo in encoding.md

---

blocksync/reactor.go
evidence/pool.go
evidence/verify.go
test/e2e/app/app.go
test/e2e/runner/evidence.go
types/validator_set.go
types/validator_set_test.go

The problem fixed by #1750 on`main`, `v1.x`, and `v0.38.x` also exists in previous release branches: when verifying an evidence of misbehavior, not all signatures are checked, opening the door to tampering with validators' signatures and identities.
This PR addresses this problem and also fixes a condition in `VerifyCommitLight` & `VerifyCommitLightTrusting` so that signatures of `nil` votes are also verified if we are "counting all signatures".
As I forgot to add a changelog in #1750 (apologies for that), I will create another PR with the changelog and backport it all the way to `v0.34.x` (EDIT: PR is #1807).
---

Introduce `countAllSignatures` in `VerifyCommitLight` & `VerifyCommitLightTrusting`

---

blockchain/v0/reactor.go
blockchain/v1/reactor.go
blockchain/v2/processor_context.go
evidence/pool.go
evidence/verify.go
test/e2e/app/app.go
types/validator_set.go
types/validator_set_test.go

Manual backport of #1806
I added the corresponding changes to `v1` and `v2` of blocksync, which are still present in this version.
I could not adapt the e2e-repro changes, as this version's e2e code only checks for double-voting. Nevertheless the changes to unit tests, which could be backported, are still testing the code changes.
---

Introduce `countAllSignatures` in `VerifyCommitLight` & `VerifyCommitLightTrusting` (backport of #1806)

---

consensus/replay_stubs.go

Otherwise, the events from app's BeginBlock won't be fired.
Closes #1468
---

fix(consensus): return last saved BeginBlock, not a empty one

---

go.mod
go.sum

Fixes vulnerability reported on version v0.16.0.
https://pkg.go.dev/vuln/GO-2023-2402
---

Updates go crypto package to v0.17.0

---

internal/blocksync/reactor.go

Following [this comment](https://github.com/cometbft/cometbft/pull/1750#discussion_r1431035852) in #1750, we are allowing blocksync to follow its pre-#1749 behavior: it won't verify all signatures unconditionally, but will exit the loop when enough voting power is verified.
---

Allow blocksync to not verify all signatures

---

abci/example/kvstore/README.md
abci/example/kvstore/helpers.go
abci/example/kvstore/kvstore.go

The kvstore in examples is only able to deal with `ed25519` key types. This PR allows devs to play around with other key types.
---

Extend kvstore example add with with key types

---

.changelog/unreleased/improvements/1921-crypto-merkle-innerHash.md
crypto/merkle/bench_test.go
crypto/merkle/hash.go
crypto/tmhash/bench_test.go
crypto/tmhash/hash.go

This change adds a more efficient API in tmhash with "SumMany" whose job is to produce the SHA256 sum of multiple byteslices. It is used inside crypto/merkle.innerHash which used a naive and inefficient way of hashing multiple byteslices. Benchmark results reflect these improvements:
```shell
$ benchstat before.txt after.txt
name         old time/op    new time/op    delta
InnerHash-8     161µs ± 1%     160µs ± 5%     ~     (p=0.143 n=10+10)
name         old alloc/op   new alloc/op   delta
InnerHash-8    69.1kB ± 0%    60.1kB ± 0%  -12.98%  (p=0.000 n=10+9)
name         old allocs/op  new allocs/op  delta
InnerHash-8      24.0 ± 0%      23.0 ± 0%   -4.17%  (p=0.000 n=10+10)
```
Fixes #1881

perf(crypto/merkle, crypto/tmhash): simplify+optimize SHA256 hashing of multiple byteslices

---

networks/local/Makefile

This is yet another small infrastructure-related fix that does not impact current developers but makes life easier for newcomers. It is not part of the mainstream source code, so I didn't add it to unclog.
Situation:
- I'm building on an Apple M1 computer (darwin/arm64).
- I want to set up a localnet using the provided scripts (`make localnet-start`)
- I cross-compile the binary to linux/amd64 as the docker image instructs.
- The `localnode` docker container still fails.
Problem:
The `localnode` docker container is built using the host's architecture but expects x86_64 libraries within. This works perfectly fine on an older Intel Mac or a Linux host. But in my case Apple M1 is an arm64 architecture and localnode is built with that in mind. Then it expects to run x86_64 binaries. …

Update localnet-start Makefile

---

.changelog/unreleased/bug-fixes/1879-blocksync-wait-for-pool-routine.md
internal/blocksync/reactor.go

Resolves https://github.com/cometbft/cometbft/issues/1878
```
blocksync: wait for poolRoutine to stop in (*Reactor).OnStop
blocksync.(*Reactor).poolRoutine goroutine lifetime was not supervised,
so OnStop returning did not provide a guarantee that it was done.  As a
result, the other services could be stopped and a subsequent call to
bcR.blockExec.ApplyBlock would cause a panic, typically a leveldb
closed error.
This change uses a sync.WaitGroup to ensure that OnStop returns after
poolRoutine has returned.
This also triggers the poolRoutine method to return on a signal from
bcR.pool.Quit() instead of just bcR.Quit(), which seems to be important
as (*Reactor).OnStop itself can only stop the BlockPool (bcR.pool), while
the BaseReactor.BaseService's quit channel will only be closed _after_ …
```

blocksync: wait for poolRoutine to stop in (*Reactor).OnStop

---

internal/blocksync/metrics.go
internal/consensus/metrics.go
internal/state/metrics.go
internal/statesync/metrics.go

Some paths to the script `metricsgen` were broken when the files were moved to `internal/`.
---

Fix paths to scripts/metricsgen in go:generate commands

---

light/doc.go

Came accross a deprecated link while reading the docs, figured I would update it in a quick PR instead of opening an issue or else.
Doesn't require testing or changelog entry.

docs(light): fix broken link to spec

---

.github/workflows/e2e.yml

There's no `tests` target in the Makefile. The command outputs `make: Nothing to be done for 'tests'`.

ci: Remove unused `tests` target when compiling e2e

---

spec/core/encoding.md

this is a trivial commit, fixing a typo i found while reading through the encoding specification.

spec: fix typo in `encoding.md`

---

config/config.go
config/toml.go
docs/core/configuration.md

This configuration is not used anymore; it's a leftover of batching txs in the mempool, which was deprecated (https://github.com/tendermint/tendermint/pull/5800)

config: Remove unused `max_batch_bytes`

---

Makefile

This pr added a new `make help` function for displaying which commonly used commands that the Makefile supported. This is useful when a new developer goes to find a helpful tool for testing or building etc.
----

misc(Makefile): add `help` target to display the help msg

---

.changelog/unreleased/improvements/2065-e2e-vote-ext-activation.md
test/e2e/app/app.go
test/e2e/generator/generate.go
test/e2e/networks/ci.toml
test/e2e/node/config.go
test/e2e/pkg/manifest.go
test/e2e/pkg/testnet.go
test/e2e/runner/setup.go

Backport of #2066, addressing #2065 on branch `v0.38.x`
The reason for the back to be manual is the many conflicts (which have already been solved).
---

Manual backport of #2066 to `v0.38.x`

---

store/store.go
store/store_test.go

Closes #2085
Added `SaveBlockStoreStateBatch` with the new functionality, while leaving `SaveBlockStoreState` with the same signature as in `v0.38.2`
---

Fix `SaveBlockStoreState` signature on `v0.38.x`

---

go.mod
spec/abci/abci++_app_requirements.md
types/params.go
types/params_test.go

Closes #2109
In `v0.38.2`, when the App was setting `VoteExtensionsEnableHeight` to a value that was the same as the current one, even if is useless as a ConsensusParams update, we were accepting it because it doesn't do any harm.
When we released `v0.38.3` we refactored function `ValidateUpdate` and we started rejecting those (useless but harmless) cases.
Since `v0.38.3` is a point release, we shouldn't add restrictions on inputs to a function without a good reason for it. This PR is adding a rule to `ValidateUpdate` so re-allow all cases where the app is not really updating the value of `VoteExtensionsEnableHeight`, regardless of which height we are currently in.
Apart form CI tasks, we carried out the following extra (manual) activities:
* We reproduced the error reported (#2109) using …

fix: `ValidateUpdate`: allow no-change updates regardless of current height

---

privval/file.go

This change applies the refactoring method of reverse conditional and using early returns for more idiomatic code which makes the code much more direct and less nested.
Fixes #2154

refactor(privval): reverse conditional + more idiomatic Go code with early returns

---

test/e2e/pkg/infra/digitalocean/digitalocean.go

Running testnets with latency emulation in DO is failing because of we are looking for the script files in the wrong location.
Related to #1587
---

fix(e2e): path to latency script files in DO

---

.github/workflows/conventional-pr-title.yml

The `conventional-pr-title.yml` workflow configuration is broken.

fix(.github/workflows): correct parameters to lint_pr_title

---

.changelog/unreleased/fix/2215.md
abci/example/kvstore/kvstore.go
internal/blocksync/pool.go
internal/consensus/types/height_vote_set.go
internal/flowrate/io.go
internal/store/store.go
light/client.go
privval/signer_dialer_endpoint.go
rpc/jsonrpc/client/decode.go
rpc/jsonrpc/client/ws_client.go
rpc/jsonrpc/server/http_uri_handler.go
test/e2e/app/state.go
test/e2e/pkg/infra/docker/docker.go

This is cherry-picked from:
* #1907
There were a number of opportunities to simplify code in comet by using revive's if-return and early-return linters.  This PR does not enable the linters as default, but instead just applies the fixes suggested by them.
There are two cases where I've marked conditionals with //nolint -- they're both a little bit odd and it may make sense to look deeper into weather it is possible to benefit from early returns. 
As we've seen in the break statements in #1907 using a linter can help to enforce good practices across the entire repository and uncover issues.
* #2156 
---

fix: if-return and early-return

---

Makefile

It looks like `go generate -run="./scripts/mockery_generate.sh" ./...` produces correctly formatted (from `gofumpt` perspective) output.
Closes #2212

fix(Makefile): gofumpt no longer needed

---

mempool/clist_mempool_test.go

The test `TestMempoolUpdateDoesNotPanicWhenApplicationMissedTx` has two problems:
- First, the test calls `reqRes.InvokeCallback()` on every CheckTx request-response, but there's no callback set on `reqRes` so the tx are not really added to the mempool at this point.
- Near the end, it makes two calls to `callback` on requests of type `CHECK_TX_TYPE_CHECK` when they should be of type `CHECK_TX_TYPE_RECHECK`. The intention here was to process the recheck responses; instead, the two txs are added to the mempool.

test(mempool): fix TestMempoolUpdateDoesNotPanicWhenApplicationMissedTx

---

mempool/clist_mempool.go
mempool/clist_mempool_test.go
mempool/reactor.go

- Do not print the whole transaction in log messages. In particular, `TestMempool_CheckTxChecksTxSize` sometimes timeouts because it logs the whole transaction, which can be huge in this test.
- Decrease the timeouts of some tests that are unnecessarily high.
- Remove verbose or redundant debug log messages.
---

fix(mempool/tests): Reduce tests duration

---

mempool/clist_mempool.go
mempool/clist_mempool_test.go

The main change is for improving readability by changing the parameters of the functions, from 
```
resCbFirstTime(tx []byte, res *abci.Response)
resCbRecheck(req *abci.Request, res *abci.Response)
```
to
```
resCbFirstTime(tx types.Tx, res *abci.CheckTxResponse)
resCbRecheck(tx types.Tx, res *abci.CheckTxResponse) 
```
---

refactor(mempool): simplify parameters of resCbFirstTime and resCbRecheck

---

docs/references/qa/method.md

Instead of hardcoded step numbers from qa-infra which are prone to falling out of date (as is the case now), refer to section anchors with the step "routines" in the reorganized README.
Requires https://github.com/cometbft/qa-infra/pull/38

docs: symbolic references to steps in the qa-infra README

---

.changelog/unreleased/improvements/2328-e2e-log-sent-txs
test/e2e/runner/load.go

When we run e2e's `load` command there is no message telling if the txs were sent or not, and if not, for what reason (eg. mempool is full, txs is too large, wrong endpoint, etc.). This PR will log a message every ~1 second with the number of successfully sent and failed transactions.
---

feat(e2e): Log number of sent txs (success and failed)

---

.changelog/unreleased/features/2362-e2e-block-max-bytes.md
test/e2e/pkg/manifest.go
test/e2e/pkg/testnet.go
test/e2e/runner/setup.go

Add `block_max_bytes` option to manifest to allow setting the maximum size of a block of all nodes on the testnet.
---

feat(e2e): Option to set max block size in bytes at genesis

---

CONTRIBUTING.md
test/e2e/tests/block_test.go
test/e2e/tests/grpc_test.go
test/e2e/tests/validator_test.go

The test is failing often due to the fact that it asks for the first block via RPC Status then waits to be notified about the latest height via gRPC and then requests block results at the first and last heights. If pruning is happening fast enough, there is a high chance the results will be pruned at the time of asking.
This fix is not making the behaviour fully deterministic but increases the chances the block is still around because it sets the first height to be the last reported first height + retain blocks. 
---

fix(e2e): Reduce flakiness of TestGRPC_GetBlockResults

---

spec/consensus/proposer-based-timestamp/README.md
spec/consensus/proposer-based-timestamp/pbts-algorithm.md
spec/consensus/proposer-based-timestamp/pbts-sysmodel.md

Part of #2184.
The changes are relatively small and should not affect the formal validation of this spec.
Essentially, when it was read `MSGDELAY`, the consensus parameter, now it should be read `MSGDELAY(r)`, where `r` is the round number. We assume that the original `MSGDELAY = MSGDELAY(0)` and that the value for the parameter increases over rounds (it does not matter here how), i.e., `MSGDELAY(r+1) > MSGDELAY(r)`
Entry point of the spec [rendered](https://github.com/cometbft/cometbft/blob/cason/pbts-spec-adpative/spec/consensus/proposer-based-timestamp/README.md).
---

spec: adaptive MSGDELAY parameter included in PBTS spec

---

docker-compose.yml

Error:
```
ERROR: invalid network config:
invalid subnet 192.167.10.0/16: it should be 192.167.0.0/16
```
OS: Ubuntu
Closes #2381
---

fix(docker-compose): fix subnet

---

.changelog/unreleased/features/2433-e2e-testnet-dir.md
test/e2e/README.md
test/e2e/generator/generate_test.go
test/e2e/pkg/testnet.go
test/e2e/runner/cleanup.go
test/e2e/runner/load.go
test/e2e/runner/main.go
test/e2e/runner/setup.go
test/e2e/runner/test.go
test/e2e/tests/e2e_test.go

Add the optional parameter `--testnet-dir` to `test/e2e/runner`.
---

feat(e2e): add parameter to set a custom output directory for testnet files

---

.changelog/unreleased/improvements/2434-jsonrpc-websocket-basic-auth.md
rpc/jsonrpc/client/ws_client.go

Hello,
I noticed that the JSON-RPC client is compatible with URLs containing **HTTP basic auth**, but not on the WebSocket side.
For instance:
```golang
client, err := http.New("https://foo:bar@example.org:443", "/websocket")
client.Block(ctx, nil) // works
client.Start() // websocket error: the client doesn't forward auth headers
```
The HTTP client handle the username/password from the given endpoint correctly:
- https://github.com/cometbft/cometbft/blob/v0.38.5/rpc/jsonrpc/client/http_json_client.go#L140-L141
- https://github.com/cometbft/cometbft/blob/v0.38.5/rpc/jsonrpc/client/http_json_client.go#L184-L185
So this PR brings the same logic for the WS client.
---

fix(jsonrpc): enable HTTP basic auth in WS client

---

internal/consensus/common_test.go
internal/consensus/pbts_test.go

Adds a test unit to attest the proper operation, from consensus' point of view, of the changes introduced by #2431.
Addresses  #2432.
---

test: untimely proposals must be decided after multiple rounds

---

test/e2e/pkg/grammar/checker.go
test/e2e/pkg/grammar/checker_test.go

---
Closes #2466.
The abci e2e tests were returning that the execution: `prepare_proposal process_proposal process_proposal` is not correct. The bug was in the part of the code that is filtering the last incomplete execution. 
The code was not working properly in case the first instance is already incomplete, and that is exactly what has happened here. The proposed fix should address this. Moreover, we modified the unit tests to capture the modifications.

fix(e2e): Fixing the bug in ABCI e2e tests

---

test/monitoring/compose.yml

This change adds the grafana image renderer plugin to the monitoring of localnet.
It adds a link to the sharing page of each dashboard graph that says "Direct link rendered image". This link is a simple way to copy images off the page.
I expect we will need graphs for our v1 QA testing and this way we can easily save them, even programmatically, if we want.
Tested locally.
---

feat(localnet): Grafana PNG rendering for easier graph exports

---

internal/consensus/metrics.go

Contributes to #2323.
Add several buckets to better track `ProposalTimestampDifference` in QA experiments.
Buckets:  `-Inf, -1.5, -1.0, -0.5, 0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 6.0, 8.0, 10.0, +Inf`
If they are too much, let me know.
---

feat(metrics): more buckets for ProposalTimestampDifference

---

internal/consensus/metrics.gen.go
internal/consensus/metrics.go

#2479 didn't actually updated the metrics. Running `make metrics` now.
---

fix(metrics): more buckets for ProposalTimestampDifference

---

internal/consensus/state.go

Addresses  #2320.
For instance, the new logging of timely/untimely messages is:
```
$ go test -v -run TestPBTSEnableHeight | grep timely
I[2024-03-01|13:36:37.072] prevote step: Proposal is not timely; prevoting nil module=consensus height=4 round=0 timestamp=2024-03-01T12:36:38.071256Z receive_time=2024-03-01T12:36:37.072355Z timestamp_difference=-998.901ms lower_bound=-500ms upper_bound=2.5s
D[2024-03-01|13:36:37.998] prevote step: Proposal is timely             module=consensus height=4 round=1 timestamp=2024-03-01T12:36:37.997463Z receive_time=2024-03-01T12:36:37.997737Z timestamp_difference=274µs
D[2024-03-01|13:36:38.014] prevote step: Proposal is timely             module=consensus height=5 round=0 timestamp=2024-03-01T12:36:38.014012Z receive_time=2024-03-01T12:36:38.01419Z …
```

feat(consensus): improve logging for timely and untimely messages

---

internal/consensus/state_test.go

There are two core tests for consensus, `TestStateLock_POLSafety1` and `TestStateLock_POLSafety2`. There were flacky and changed a lot with the introduction of PBTS. This PR refactor them, in particular, from [this comment](https://github.com/cometbft/cometbft/pull/2149#discussion_r1467921598).
---

test(consensus): refactor TestStateLock_POLSafety tests

---

test/e2e/pkg/testnet.go
types/params_test.go

Contributes to #1731
After some troubleshooting, I realized that, for two `// nolint` added at the beginning of files in #2494, the `gofumpt` and the `golangci-lint-full` have contradictory rules. So the first one removes the space between `//` and `nolint` and the second adds it back 🤯. The problem has been to _find_ this, as, at the end no files where modified whereas both linters were saying they were modifying some files.
To work around this problem, I changed the way to fix the original lint issues.
---

fix: lint errors introduced with the latest merge

---

internal/blocksync/pool.go

`time.After` gets reset after each iteration of the `for` loop, which is not what we want. We want the timer to fire after 30 sec if both peers (first and second) don't respond.

fix(blocksync): use timer instead of time.After

---

RELEASES.md
go.mod
go.sum

The current `go.mod` points to CometBFT version `v1.0.0-alpha.1`. After merging `feature/pbts` onto `main` there are changes in protobufs that aren't included in that version.
This PR add a temporary fix that will work until:
* we tag a new `alpha` version of CometBFT
* we tag the final `api` version as part of the release process
---

fix: temporary fix for `api` dependency

---

test/e2e/generator/generate.go

Some nightly tests are failing because validators with clock skew and high stake are slowing down progress.
---

fix(e2e): Add clock skew only to processes that accumulate less than 1/3 of voting power

---

test/e2e/tests/app_test.go

Some nightly test scenarios are failing because the test that checks that new blocks are being created timeouts. This happens on larger networks with many perturbations, on a few heights. Currently the timeout is 5 seconds, but in some cases it takes the network more than 20 seconds to create a block, so this PR changes it to 30 seconds.
---

fix(e2e): Increase timeout when waiting for new block

---

proto/buf.lock

> [!IMPORTANT]
> These changes have already been committed into `v1.x` branch in commit 5a2e40fb. I mistakenly pushed those changes into `v1.x` without opening a PR as we usually do.
> The present PR brings those changes into `main`.
<details>
<summary>Process used to create this PR h/t Sergio</summary>
```sh
create a branch on top of `origin/main`
then, `git cherry-pick 5a2e40fb` (fix any conflicts)
then, open a PR (against `main`) asking to only review the changes and explain they have already been committed to v1.x
```
</details>
The branch contains updates we have pushed to buf following the recent changes in protos on the `v1.x` branch, specifically the updates in commit: https://buf.build/cometbft/cometbft/activity/commit/4a62c99d422068a5165429b62a7eb824df46cca9
which includes tag …

fix(protos): new buf tag aligned with v1-alpha.2 release

---

test/monitoring/config-grafana/provisioning/dashboards-data/storage.json

fix(monitoring): Do not convert ms to ms

---

spec/abci/abci++_app_requirements.md

close: #901 
- Added missing information about the consensus Feature Params `vote_extensions_enable_height` and `pbts_enable_height`.
- Verified that the `List of Parameters` matches what is defined in `api/cometbft/types/v1/params.pb.go` file
- Cleaned up some old information that was hidden and not relevant and could cause rendering issues on the docs website.
- Removed the section for ABCI Params (deprecated).

spec: Add missing Feature Params information in ABCI spec and some other clean-up

---

internal/consensus/state.go

Follow-up from #2713.
- Separate the two validity checks `Proposal == nil` and `ProposalBlock == nil`
- Improved the comments on related methods.
---

refactor(consensus): defaultDoPrevote validity checks

---

spec/abci/abci++_basic_concepts.md

Related to #2760
A couple of typos I found when comparing the ABCI spec on `main` with the one on `v0.36.x`.
---

docs: fixed typos in ABCI spec

---

.changelog/unreleased/breaking-changes/2775-deprecate-boltdb-cleveldb.md
config/config.go
config/toml.go
docs/references/config/config.toml.md
go.mod
go.sum
node/node.go

`v0.12.0` deprecates `boltdb` and `cleveldb`. Once merged to v1, both will be removed. If you're using one of those, please get in touch.
---

build(deps): Bump github.com/cometbft/cometbft-db from 0.11.0 to 0.12.0

---

.changelog/unreleased/improvements/2788-move-ws-info-log-to-debug
rpc/jsonrpc/server/ws_handler.go

This log is extreme noise in our current setup for all RPC's. I moved to Debug, but should be deleted imo.
This logging of requests/responses should come at a higher proxy level IMO, or have the request + response written elsewhere asynchronously.
---

fix(rpc): Make websocket's log on success be in Debug, not info

---

node/node.go

The cosmos-sdk 0.50 genesis doc marshalling not being compatible with the cometbft default one (see https://github.com/cosmos/cosmos-sdk/issues/18477), so we need to support custom genesis doc provider in this public API as well, it's called by the `bootstrap-state` command in cosmos-sdk.
Please backport to 0.38, the SDK 0.50 `bootstrap-state` command is already broken.
---

fix: BootstrapState use custom genesis doc provider

---

.github/workflows/e2e-nightly-34x.yml
.github/workflows/e2e-nightly-main.yml
README.md
UPGRADING.md
docs/guides/go-built-in.md
docs/guides/go.md
go.mod
scripts/proto-gen.sh
test/docker/Dockerfile

NOTE: v0.37 was tested with Go 1.21, but had Go 1.20 in `go.mod` file.

deps: bump Go version from 1.20 to 1.21 in go.mod (v0.37.x)

---

.changelog/unreleased/improvements/2846-speedup-json-encoding.md
libs/json/encoder.go
libs/json/encoder_test.go

---
Many RPC methods require JSON marshalled responses. We saw this taking a notable amount of heap allocation in query serving full nodes. This PR removes some extra heap allocations that were being done. We avoided using the more efficient encoder.Encode before, because it added a newline. This PR changes the function signature for these private methods to be using *bytes.Buffer, and then uses the in-buffer methods (rather than a second copy). We then just truncate the final byte after each such call, which does not waste any allocations.
I added a benchmark for the most complex test case. 
OLD:
```
BenchmarkJsonMarshalStruct-12              78992             15542 ns/op            4487 B/op        191 allocs/op
```
New:
```
BenchmarkJsonMarshalStruct-12              93346 …
```

perf(libs/json): Lower heap overhead of JSON encoding

---

p2p/metrics.go
p2p/peer.go
p2p/switch.go

Addresses #2840.
The same approach taken for the `send()` method is also adopted for the `onReceive()` method. 
---

feat(p2p): pre-allocate static labels used to produce metrics

---

.changelog/unreleased/improvements/2839-tx_index-lower-heap-allocation.md
state/txindex/kv/kv.go

In Osmosis we see massive amounts of heap pressure/allocations coming from txIndex matchRange. (Screenshot below from ~1 hour of heap profiling)
This PR is expected to fully compatibly drop this down by a factor of 3. It:
- Does not get Key() twice (160GB allocation saved)
- Uses no heap allocations for isTagKey (120GB saved)
- Does not string cast or do strings.Split in parsing the value (~400GB expected saved)
- Reuses the big.Int (24GB saved)
The remaining RAM overhead from .Key() needs a cometbft-db API change. The remaining RAM overhead from extracting the value can be saved with an unsafe call for casting the output to string with no heap allocation, but we can do that in a separate PR.
---

perf(txindex): Lower allocation overhead of txIndex matchRange

---

.changelog/unreleased/improvements/2841-speedup-bits-pick-random.md
internal/bits/bit_array.go
internal/bits/bit_array_test.go

This PR significantly speeds up bitArray.PickRandom which is used in VoteGossip and BlockPart gossip. We saw for a query serving full node, over an hour, this was a very large amount of RAM allocations. (75GB of RAM!)
This PR drops it down to 0 allocations, and makes the routine 10x faster on my machine.
OLD:
```
BenchmarkPickRandomBitArray-12           1545199               846.1 ns/op          1280 B/op          1 allocs/op
```
NEW:
```
BenchmarkPickRandomBitArray-12          22192857                75.39 ns/op            0 B/op          0 allocs/op
```
I think the new tests I wrote make this more tested than the old code that was here tbh, but pls let me know if theres more tests we'd like to see!
---

perf(internal/bits): Significantly speedup bitArray.PickRandom

---

.changelog/unreleased/bug-fixes/2225-fix-checktx-request-returns-error.md
mempool/clist_mempool.go
mempool/clist_mempool_test.go
mempool/errors.go

Closes #2225
If the app returns an error on an ABCI call (in particular CheckTx), CometBFT should stop, because the error is unrecoverable.
---

fix(mempool): panic when the app returns error on CheckTx request

---

.changelog/unreleased/improvements/2911-remove-event-bus-debug-logs.md
types/event_bus.go

Component of #2869 
This on its own is an expected 1% speedup to blocksync on osmosis mainnet right now.
I originally considered keeping the log lines but with only creating the logger cost if there is an error, but these are debug logs I've never seen. I think its better to just remove these debug logs directly, rather than worry about maintaining them. These aren't even that concerning scenarios I feel like, as more of the stack moves away from these. 
---

perf(event bus): Remove expensive Logger debug call in PublishEventTx

---

.changelog/unreleased/improvements/2928-remove-redundant-verifyblock-call-in-finalize-commit.md
internal/consensus/state.go

Simplest component of #2854 
We already run ValidateBlock in finalizeCommit, so this PR removes one extra redundant call by using ApplyVerifiedBlock. (The other call is also redundant, but that likely requires a more complex caching strategy as noted in #2854 to remedy)
From my understanding of these benchmarks, at Osmosis 150 validators, this should be saving ~13ms of execution time per block. 
---

perf(consensus/state): Change finalizeCommit to use applyVerifiedBlock

---

internal/consensus/state.go

Small refactor to simplify the calls to "is timely"
---

refactor(state): reuse method `proposalIsTimely`

---

.changelog/unreleased/improvements/2949-reduce-protoio-writer-creation-time.md
internal/protoio/writer.go

Speeds up 5% of the non-IO time overhead from `channel.WritePacketMsgTo`. The CPU time overhead in this function is quite significant, CPU time is more than 3 times the syscall time for writing to the net buffer. Working on a github issue for more substantial refactor / time eliminations, but this 3s is easy enough.
We don't even use this codepath, so this make slice is entirely wasted. However we should do things that reduce this overhead further.
---

perf(p2p/channel): Speedup NewDelimitedWriter

---

p2p/conn/connection.go

This PR is a driveby change. We were doing an atomic read here, but this is unnecessary. Nothing in the codebase modified this variable after instantiation.
Doesn't really feel changelog worthy, but I can add one if we want. Felt like a minor code nit

perf(p2p): Remove unnecessary atomic read

---

.changelog/unreleased/improvements/2952-lower-next-packet-msg-time.md
p2p/conn/connection.go

Somehow this minint call is appearing in CPU profiles. Its too large of an appearance to be declared as noise, but I really don't get why its there. Must be some weird system effect I don't get. (perhaps due to being the result of a function call for a slice index? idk)
This PR just removes the function call, since its not needed, as we already branch on the if statement.
Profile showing it:
Contributes a 3% improvement to #2951 
---

perf(p2p/conn): Remove a minint call that was appearing in write packet delays

---

.changelog/unreleased/improvements/2959-speedup-initialized-bitarray-construction.md
internal/bits/bit_array.go
internal/bits/bit_array_test.go
types/block.go

Speedup ExtendedCommit.BitArray() by making a direct constructor that does not go through mutexes. I expect this to be a 10x performance improvement. (It also removes the duffcopies and reduces setIndex proportion of time here)
This removes this time (which is mostly coming from mutex calls): 
Later on we should instead make an API that lets us randomly sample from a bit array with no bit array copying needed. (But that makes the interface messier) 
---

perf(internal/bits): Speedup extended commit.BitArray()

---

p2p/peer.go

In the metric `MessageReceiveBytesTotal`, the only value produced in the `message_type` label is `v1_Message`. This is because we are reading the `msg` variable before the message is unwrapped. This bug was recently introduced in #2851.
---

fix(metric): message type in metric `MessageReceiveBytesTotal` is wrong

---

.changelog/unreleased/improvements/2986-lower-memory-allocation-in-packet-writing.md
p2p/conn/connection.go

This PR makes sending packet messages re-use the protowriter for writing to the channel, rather than remaking it in `writePacketMsgTo`. 
In a 1 hour sync benchmark, this saves 10% of the time spent in the `sendRoutine` (6s), and saves 13GB of heap allocation.
This is a simple fix, so I think its worth doing. Later on, I think we should move this proto-marshalling to `mConnection.Send`, but that change will require more robust testing, as it would be a tradeoff of increasing the CPU time of gossipVotesRoutine and gossipBlockPartRoutine. (I personally think it will be worth it / were anyways lowering the CPU time of these routines in total) Will be writing this later direction idea into an issue.
---

perf(p2p/connection): Lower wasted re-allocations in sendRoutine

---

.changelog/unreleased/improvements/2964-skip-revalidation-of-blockstore-LoadBlockFromMeta-.md
store/store.go
types/block_meta.go
types/block_meta_test.go

Our gossip block parts routine calls `Blockstore.LoadBlockMeta` (as do things in blocksync). This currently takes some time due to ValidateBasic:
However note that we only save validated data to the blockstore. We only do it in:
- Commit: https://github.com/cometbft/cometbft/blob/main/internal/consensus/state.go#L1867
- Blocksync after validation: https://github.com/cometbft/cometbft/blob/main/internal/consensus/state.go#L1867
Hence the validate basic time is wasted.
This should eventually just go to an LRU cache to even avoid the proto unmarshalling (as should ~everything in blockstore) but we want this anyway to reduce the computational overhead,
WRT live consensus, in main this only helps with catchup for live syncing nodes, I haven't checked on v0.47.x, but the cpuprofile suggests it …

perf(consensus/blockstore): Remove validate basic call from LoadBlockMeta

---

rpc/jsonrpc/server/http_server.go

Related to #2867 
Quick fix for a comment in the code added about a default value for a config parameter. 
During backport to `v0.38.x`,  @melekes made a suggestion that the default value in a comment was inaccurate. Instead of updating the default value in the comment, I've decided to remove the comment about the default value. 
In my opinion, we should not have default value for config parameters in comments if it's clear specified in the configuration docs what are the default and possible values. Realized that having the default values in comments is not beneficial and updating in the comment might be a not as straightforward as changing it in code/config.

fix: remove comment about default value (#2867)

---

.changelog/unreleased/improvements/3019-reduce-allocations-in-packet-reads.md
libs/protoio/io.go
libs/protoio/reader.go

This PR is a slight optimization to save one allocation per packet. We have much more worthwhile performance improvements to pursue, just driveby noticed it as I was reading through the code. (Though I am surprised this did add up to 1 second in total -- 4% of the processing time) 
This re-uses the byte reader's allocation across all ReadMsg's. There is no concurrenct access possible under safe usage (also implied by the reader)
This is the cause of the 1s time on the far right: 
---

perf: Micro optimization to save one allocation per packet

---

.changelog/unreleased/improvements/3017-speedup-consensus-metrics.md
internal/consensus/metrics.go
types/signed_msg_type.go

Minor speedup to metrics MarkLateVote.
I saw the excess string allocation calls, so made a quick PR to remove it. This saves between .18s-25s from the consensus mutex across this one hour block sync. (Likely not at all consensus critical) It also appears in receiving votes
(Saves ToLower(), .String(), .TrimPrefix() and newObject calls. The new call has comparable complexity to .String())
---

perf: Minor speedup to consenus metrics MarkLateVote

---

internal/consensus/state.go
state/execution.go

~~This change is an implementation of the alignment of `ValidateBlock` to `ProcessProposal` explained [here](https://github.com/cometbft/cometbft/issues/2854#issuecomment-2088261899).~~
We need to:
* Check if that helps, perf-wise
* Carefully make we're not compromising algorithm's correctness
EDIT:
In the end, we are implementing this as agreed [here](https://github.com/cometbft/cometbft/issues/2854#issuecomment-2107159921)
EDIT2:
This PR will just deal with alignment of `ValidateBlock`, `ProcessProposal` and `isTimely` (so it's no longer closing #2854)
---

perf(consensus): align calls to `ValidateBlock`, `ProcessProposal` and `isTimely`

---

.changelog/unreleased/improvements/3003-use-lru-caches-in-blockstore.md
.golangci.yml
go.mod
go.sum
store/bench_test.go
store/store.go
store/store_test.go
types/block.go

Closes #2844
We are seeing that the blockstore loading operations get used in hot loops within gossip routines, and queryMaj23 routines. This PR reduces that overhead using an LRU cache.
The LRU cache does have a mutex on every get, but the time with the LRU cache is 9x faster than without (before even adding in DB overheads), due to the proto unmarshalling saved. We could imagine a setup where we avoided a lock there entirely. I don't think this is worth right now, since the new code is 9x faster, and these mostly appear in catchup code which should not be highly contended for across peers at the same time.
With the new benchmark I added:
OLD:
```
BenchmarkRepeatedLoadSeenCommit-12         24447             54691 ns/op           46495 B/op        319 allocs/op
```
NEW:
``` …
```

perf(blockstore): Add LRU caches to blockstore operations used in consensus

---

config/config.go

Minor code de-duplication for timeout calculation.
Not really important, was just a driveby change. Feel free to just hit close.
---

refactor: Minor code de-duplication in timeout calculation

---

docs/references/architecture/adr-113-mempool-lanes.md

Partially addresses #3110
Added subsection "Priority mempool" in "Alternative approaces" section.
I also added extra properties in the previous section: those properties are one of the core points in our current discussions with our users, and I wanted to relate it to the priority mempool.
---
- ~~[ ] Tests written/updated~~
- ~~[ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)~~

docs(mempool): added network consistency properties and Priority Mempool

---

.changelog/unreleased/improvements/3117-significantly-speedup-make-partset.md
crypto/merkle/bench_test.go
crypto/merkle/proof.go
crypto/merkle/proof_value.go
types/part_set.go
types/part_set_test.go

This PR adds some benchmarks, and significantly speeds up types.MakePartSet, and Partset.AddPart. (Used by the block proposer, and every consensus instance) It does so by doing two things:
- Saving mutexes on the newly created bit array, by defaulting every value to True (rather than setting it in a loop that goes through a mutex)
- Uses the same hash object throughout, and avoids an extra copy of every leaf. (main speedup)
I do the same hash optimization for proof.Verify, which is used in the add block part codepath for both the proposer and every full node.
New:
```
BenchmarkMakePartSet/nParts=1-12         	   38616	     29817 ns/op	     568 B/op	      12 allocs/op
BenchmarkMakePartSet/nParts=2-12         	   19888	     59866 ns/op	    1000 B/op	      22 allocs/op …
```

perf(types): 3x speedup MakePartSet

---

abci/client/client.go

replace `Sets` with `SetCallback` in the comment to keep the function name consistent.
---

chore: fix the function name in comments

---

docs/references/architecture/adr-113-mempool-lanes.md

Partially addresses #3110
Added subsection "Priority mempool" in "Alternative approaches" section with the description of Skip's block SDK and how it compares to the Mempool QoS design.
---
- ~~[ ] Tests written/updated~~
- ~~[ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)~~

docs(mempool): skip's Block SDK

---

rpc/core/mempool.go
rpc/openapi/openapi.yaml

This is related to the PR #3109 
The entry in the OpenAPI doc was missing for this new endpoint.
Also added a better response if the tx hash is not specified when querying the `/unconfirmed_tx` endpoint.
---

docs(rpc): added entry in OpenAPI doc for new endpoint `unconfirmed_tx`

---

.changelog/unreleased/improvements/3159-fix-taking-wlocks-instead-of-rlocks.md
internal/consensus/reactor.go

Some clear, read-only spots in receive routine took Write locks instead of read locks. Seems like a bug.
This PR fixes it.
---

perf(consensus): Fix some peer messages taking write locks on the cs mtx

---

.changelog/unreleased/improvements/3156-make-addvote-only-take-one-ps-mtx.md
internal/consensus/reactor.go

perf(consensus): Make one peer state mutex call in AddVote

---

.changelog/unreleased/improvements/3162-reuse-internal-buffer-for-block-building.md
internal/consensus/state.go
internal/consensus/state_test.go

Makes an internal buffer that we can re-use when building blocks. This seems to save on average 75 microseconds per block for osmosis blocks. (Ranging between 1-2 block parts in the relevant time range) This should be scaling roughly linear with block size.
This lets us remove one allocation cost per complete block coming in. We only need to re-allocate on the next "biggest ever seen" block we see. 
---

perf(consensus): Reuse an internal buffer for block building

---

rpc/core/mempool.go

This PR fixes a race condition generated when calling `broadcast_tx_sync` and `broadcast_tx_commit`. When closing the context, we want to also close the goroutine waiting for the response with `reqRes.Wait()`. We don't need to do `reqRes.Done()` because there is a chance it may become negative; instead, we just let the ABCI client to do it.
This bug was recently introduced by #3131.
---

fix(rpc): Race condition when waiting for response on `broadcast_tx_sync/commit`

---

UPGRADING.md
mempool/clist_mempool_test.go
rpc/core/mempool.go

On sync RPC endpoints `broadcast_tx_sync|commit`, it is wrong to call `reqRes.InvokeCallback()` because the callback was executed before. This PR removes these lines. 
The reason is that the callback was already executed, either inside the remote clients (socket or grpc) or when setting the callback on the local client.
- The socket client executes the callback explicitly [when receiving the response](https://github.com/cometbft/cometbft/blob/e731a3fdf9187fe07b2385463320669fcac569b6/abci/client/socket_client.go#L234C9-L234C15).
- The local client, on receiving the response, sets `reqRes.callbackInvoked = true`. Then it's the function `SetCallback` that actually executes the callback [outside of the client](https://github.com/cometbft/cometbft/blob/e731a3fdf9187fe07b2385463320669fcac569b6/m …

fix(mempool/rpc): remove duplicate invokeCallback

---

libs/pubsub/pubsub_test.go

test: avoid already subscribed error in benchmarkNClientsOneQuery

---

.github/workflows/e2e-manual-multiversion.yml
.github/workflows/e2e-manual.yml
.github/workflows/e2e-nightly-1x.yml
.github/workflows/e2e-nightly-38x.yml
.github/workflows/e2e-nightly-main.yml
test/e2e/generator/generate.go
test/e2e/networks/ci.toml
test/e2e/networks_regressions/evidence_fail.toml
test/e2e/pkg/testnet.go
test/e2e/runner/evidence.go

Closes #3233 
This PR is is to be interpreted commit by commit.
* Commit 1: Changes in `e2e runner to repro the problem (these changes will stay).
* Commit 2. Making the problem repro appear in this PR (look at the ❌ next to commit 2 below, and check the `e2e` logs)
* Commit 3: Fix. (look at the ✅ next to commit 3 below)
* Commit 4: Revert commit 2
* Commit 5: Adapt nightlies to start running all regression manifests in (newly introduced) `test/e2e/networks_regressions` directory. Also, adapt manifest generator to create testnets with more evidences.
* Further commits: fix e2e infra
The reproduction consists in coming up with a testnet where some evidences can be delayed in their transit to the next validator, long enough to become invalid (too old). The delay is achieved by having a …

fix(e2e): reproduction an fixing of missing evidence in `e2e` nightlies 

---

.changelog/unreleased/improvements/3180-lower-broadcasts-consensus-overhead.md
internal/consensus/reactor.go

Run broadcast routines out of process. Right now each broadcast routine blocks the consensus mutex for roughly `num_peers * process_creation_time`, which is genuinely notable! This PR reduces the consensus blocking overhead to just be `process_creation_time`. 
On the latest osmosis branch with improvements, thats 20s of blocking time out of 140s (over the course of 1 hour. This 140s includes block execution!) 
Note that WAL write time should go significantly down with open PR's. For `HasVote`, this is a meaningful increase to consensus mutex lock time, so its worth reducing.
---

perf(consensus): Run broadcast routines out of process

---

.changelog/unreleased/improvements/3211-make-cs-reactor-no-longer-takes-cs-locks.md
internal/consensus/reactor.go
internal/consensus/state.go

This PR reverts #3211 since it is making the e2e nightly to fail in reproducible ways. This PR was identified as the reason for the recent e2e nightly failure on `main` and doing a bi-sect test of all recent commits it was determined that this PR introduced a behavior that makes the tests to fail and indicate a bug or unknown behavior has been introduced. 
Even though we are reverting this logic for now, we'd be happy to consider it in the future again once more tests are performed and we can ensure it passes all tests.
---

test(e2e): reverting PR3211 since it is making e2e nightly to fail

---

.changelog/unreleased/improvements/3342-improve-blockstore-caches.md
store/store.go

We speedup the gossip routines by using caches for LoadBlockPart, and making LoadBlockCommit no longer call Clone, as the caller does read-only operations to it.
This is a followup to https://github.com/cometbft/cometbft/pull/3003
This results in a net performance improvement, based on a 2hr sync on latest osmosis release, of:
- 20% less RAM allocated over program lifetime. (76GB no longer allocated, 380 GB alloc total)
- 50% speedup to gossipDataRoutine
- ~10% speedup to gossipVotesRoutine
- 1% less overall system CPU usage. (If GC proportional to bytes allocated, then 5% less)
I have checked that every usage of `LoadBlockPart` and `LoadBlockCommit` do not modify the return value, so returning this underlying cache copy is safe for the current codebase
I used an `!` in the title, since …

perf(blockstore)!: Cache more in blockstore, which speedsup the gossip routines

---

.changelog/unreleased/improvements/1757-gen-validator.md
cmd/cometbft/commands/gen_validator.go
privval/file.go
spec/core/encoding.md

also better document secp256k1 keys in spec/core/encoding.md
Closes #1757
---

feat(cmd): add support for all key types in gen-validator

---

.changelog/unreleased/bug-fixes/3352-nil-pointer-tx-search.md
rpc/core/tx.go

when block is absent
Closes #3352
---

fix(rpc): fix nil pointer error in `/tx` and `/tx_search`

---

.changelog/breaking-changes/3361-mempool-preupdate.md
blocksync/reactor_test.go
consensus/replay_stubs.go
mempool/clist_mempool.go
mempool/clist_mempool_test.go
mempool/mempool.go
mempool/mocks/mempool.go
mempool/nop_mempool.go
mempool/reactor_test.go
state/execution.go
state/execution_test.go
state/validation_test.go

This PR partially reverts the backport of #3314 into the recently released `v0.38.8` (and `v0.37.7`). With this change the `Mempool` interface is the same as in previous versions.
The reason is that we do not want to break the public API. We still keep in the code the feature that #3314 introduced by moving it inside the existing `Lock` method. We also keep the `RecheckFull bool` field that we added to `ErrMempoolIsFull`.
---

refactor(mempool)!: remove PreUpdate from Mempool interface and move its logic to Lock

---

.changelog/unreleased/improvements/3353-e2e-runner-split-logs.md
test/e2e/README.md
test/e2e/runner/main.go

When conducting end-to-end testing, it can be difficult to effectively analyze or visualize the output of docker logs when all the containers are merged into a single log file.
To address this issue, I have introduced a new parameter (`--split`) to the runner `logs` command. When this parameter is used, the command will output the log for each container separately.
Having separate logs makes it much easier to troubleshoot individual containers, particularly when the log output is extensive and detailed. This feature boosts efficiency by simplifying the process of identifying the root cause of failures.
Usage:
```sh
./build/runner logs -f ./networks/simple.toml --split
```

test(e2e): add option to the 'runner logs' command to output logs separately

---

.changelog/unreleased/summary.md
CHANGELOG.md

Reference: #3255 
Updating CHANGELOG to cut RC1
---

chore: updating CHANGELOG for `v1.0.0-rc1`

---

RELEASES.md
proto/README.md

Close: #3388 
This PR adds detailed instructions to the `RELEASES.doc` related to the publishing of proto files to the Buf schema registry. 
~~- [ ] Tests written/updated~~
~~- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)~~

docs: update release doc to include Buf publish instructions

---

.changelog/unreleased/bug-fixes/486-p2p-max-outbound.md
p2p/pex/pex_reactor.go
p2p/pex/pex_reactor_test.go
spec/p2p/implementation/peer_manager.md

Closes #486.
Commits:
1. Make `TestConnectionSpeedForPeerReceivedFromSeed` to fail, as it will make the node to connect to more than the configured `MaxNumOutboundPeers`
2. Solve the issue by introducing a channel to wake up `ensurePeersRoutine()`. In this way, the node will not to wait until the next `defaultEnsurePeersPeriod` (30s) before attempting again to connect to new peers (`ensurePeers()` method) whose addresses were provide by the seed node.
---

fix(p2p/pex): respect MaxNumOutboundPeers limit while dialing peers provided by a seed node

---

.changelog/unreleased/improvements/3382-single-send-monitor-per-packet.md
p2p/conn/connection.go

Small optimization to outbound packet gossip, I expect this to be a 1-2% speedup to outbound packet gossip as is right now. Will test on mainnet soon
This is safe as outbound packet gossip is single threaded per peer as is right now. Technically makes the send monitor marginally less real time, but this is irrelevant as the send monitor works on 20ms sliding windows anyway
---

perf(p2p): Only update send monitor once per batch packet msg send

---

.changelog/unreleased/bug-fixes/3406-blocksync-dont-stall-if-blocking-chain.md
internal/blocksync/pool.go
internal/blocksync/reactor.go
internal/blocksync/reactor_test.go
node/node.go
node/setup.go
test/e2e/networks_regressions/blocksync_blocked.toml

Partially addresses #3415
The a node has no peers, blocksync gets stuck without switching to consesnus, because it needs info from other peers to have an idea of maximum height.
However, there is an edge case (mainly when testing) where a validator might have >2/3 of the voting power and other validators are not started. In this case, we know we are blocking the chain, so we don't need to stay in blockchain if the only condition is that we don't have peers.
Moreover, in order to block a chain, 1/3 of the voting power is enough, so the reasoning of this fix is the following:
* _I am a node and I am starting... shall I run blocksync?_
* _Well, looks like I have 1/3 of the voting power (or more) at my current height... so there's no way the chain could advance in my absence... so I don't …

fix(blocksync)!: don't block in blocksync if our voting power is blocking the chain

---

.changelog/unreleased/improvements/3419-buffer-secret-connection-reads.md
p2p/conn/evil_secret_connection_test.go
p2p/conn/secret_connection.go

Closes #3198 
Similar to #3346 , buffers the secret connection reads. This is a notable savings to CPU time. (25% of recvRoutine time, on Osmosis' version)
---

perf(p2p/conn): Use a read buffer on the secret connection

---

.changelog/unreleased/improvements/3430-mempool-get-peer-state-once.md
mempool/reactor.go

In each broadcast routine, before sending a transaction, we read the peer's state so we can compare the height of the transaction against the peer's height. So, for each transaction we want to send, we call `peer.Get(types.PeerStateKey).(PeerState)` that reads the (pointer to the) peer's state. This PR makes this call once, before starting the loop through the list of transactions. This is possible because `PeerState` is set once (on the consensus reactor) and never unset.
---

perf(mempool): get peer state once on broadcast routine

---

.changelog/unreleased/deprecations/3303-mempool-deprecate-txsfront-txswaitchan.md
.changelog/unreleased/improvements/3303-mempool-iterator.md
mempool/clist_mempool.go
mempool/clist_mempool_test.go
mempool/mempool.go
mempool/mempoolTx.go
mempool/reactor.go

Closes #3303 
This PR adds:
- the `Entry` interface, implemented by the existing `mempoolTx` data type, 
- the `Iterator` interface, with one method `WaitNextCh() <-chan Entry`.
On the routine that sends transactions to a peer, we can now use an `Iterator` to select the next mempool entry to send, instead of the methods `TxsFront` and `TxsWaitChan` in `CListMempool`. These two methods leak implementation details about the CList and are now marked as deprecated. Now all the logic needed to wait for and pick the next available entry is implemented in `CListMempool.WaitNextCh`.
---

refactor(mempool): Add `Iterator` to replace `TxsFront` and `TxsWaitChan` methods

---

.changelog/unreleased/improvements/3458-txindex-search-optimization.md
state/txindex/kv/kv.go
state/txindex/kv/kv_bench_test.go
state/txindex/kv/kv_test.go

This PR addresses several optimization points for TxIndex.Search:
1. Remove expensive map access from sorting function
2. Replace sort.Slice to sort.Sort with sorter approach
3. Reduce heap allocations from extractEventSeqFromKey
benchstat result:
```
goos: darwin
goarch: amd64
pkg: github.com/cometbft/cometbft/state/txindex/kv
cpu: Intel(R) Core(TM) i9-10910 CPU @ 3.60GHz
│   old.txt    │              new.txt               │
│    sec/op    │   sec/op     vs base               │
TxSearchBigResult-20   3236.1m ± 7%   945.9m ± 9%  -70.77% (p=0.002 n=6)
│   old.txt    │               new.txt               │
│     B/op     │     B/op      vs base               │
TxSearchBigResult-20   426.1Mi ± 0%   311.6Mi ± 0%  -26.86% (p=0.002 n=6)
│   old.txt   │              new.txt               │
│ …
```

perf(txindex): search optimization

---

.changelog/unreleased/bug-fixes/3497-fix-p2p-external-address.md
cmd/cometbft/commands/run_node.go

Closes https://github.com/cometbft/cometbft/issues/3460
for more info, https://github.com/cometbft/cometbft/blob/0cc1b6504c51d481ded95d431900a064533ad9b3/config/config.go#L757
---

fix(cmd): align `p2p.external_address` argument when set the node P2P external address

---

.changelog/unreleased/features/3472-p2p-has-channel-api.md
internal/consensus/reactor.go
internal/evidence/reactor.go
internal/evidence/reactor_test.go
mempool/reactor.go
p2p/mock/peer.go
p2p/mocks/peer.go
p2p/peer.go
p2p/peer_set_test.go
spec/p2p/reactor-api/p2p-api.md

Closes: #3472 
It also prevents reactors from starting routines intended to send messages to a peer that does not implement/support a given channel. Because all `Send()` or `TrySend()` calls from this routine will be useless, always returning `false` and possibly producing some busy-wait behavior (see https://github.com/cometbft/cometbft/issues/3414).
The changes are restricted to: mempool and evidence reactor, because they use a single channel and have a sending routine peer peer, and two of the consensus routines, for Data and Votes.
Block and State sync reactors have smarter ways to deal with unresponsive peers, so probably this check is not needed.
---

feat(p2p): render `HasChannel(chID)` is a public `p2p.Peer` method

---

.changelog/unreleased/bug-fixes/3525-3514-genesis-validation-pub-key.md
types/genesis.go
types/genesis_test.go

Closes #3514.
- Added unit test demonstrating the problem.
- Added code in `ValidateAndComplete` that, for each validator in the genesis doc, checks if their `PubKey.Type()` is present in the accepted `PubKeyTypes` of the chain.
---

fix(types): Genesis doc validation of validators Pubkey types.

---

.changelog/unreleased/bug-fixes/3528-evidence-missing-json-tags.md
.changelog/unreleased/bug-fixes/3543-evidence-missing-json-tags.md
types/evidence.go
types/evidence_test.go

Closes #3528 
Added missing JSON tags to `DuplicateVoteEvidence` and `LightClientAttackEvidence` types.
---
~- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments~

fix(types): Add missing JSON tags to `DuplicateVoteEvidence` and `LightClientAttackEvidence` types

---

Makefile

Running `make all` would cause an error: `make: *** No rule to make target 'check', needed by 'all'.  Stop.`
The `check` target has already removed, let's delete it

fix(ci): run `make all` error 'No rule to make target 'check''

---

.changelog/unreleased/bug-fixes/3544-indexer-break-statement.md
state/indexer/block/kv/kv.go

Closes #3544.
- Adds missing `for` loop labels in the kv indexer 
- Previously ineffective `break` statements now point to their enclosing `for` loop labels to exit upon reception on the `ctx.Done()` channel.
---
~- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments~

fix(indexer): Ineffective or missing break statements in kv package.

---

docs/explanation/core/running-in-production.md
docs/references/config/config.toml.md
spec/abci/abci++_methods.md

Also,  added reference to the new `FinalizeBlock` return value intended to replace the `timeout_commit` config flag.
---

docs: make description of `timeout_commit` more precise

---

p2p/pex/pex_reactor_test.go

Increased the timeout from 1 to 3 seconds.
Almost never fails locally, but fails on the GitHub CI (e.g., https://github.com/cometbft/cometbft/actions/runs/10111986972/job/27965072382?pr=3411).
---

test(p2p/pex): fix `TestConnectionSpeedForPeerReceivedFromSeed` flacky test

---

internal/blocksync/pool.go
internal/blocksync/reactor.go
internal/blocksync/reactor_test.go

This first moves the reactor logic for receiving a blockpart into its own function, mimicking what is done for sending requests. This simplifies the code, and makes it more testable. 
We then parallelize this, which prevents blocking behavior on any other message in the reactor. cref #3230 #3209
This becomes especially important if we go to do #3553 
This parallelization doesn't really come at any downside to us
---

perf(blocksync): Parallelize logic for receiving a block from a peer.

---

.changelog/unreleased/bug-fixes/3541-copy-iter-key-value.md
abci/example/kvstore/kvstore.go
light/store/db/db_key_layout.go
state/indexer/block/kv/kv.go
state/txindex/kv/kv.go
state/txindex/kv/utils.go

Related to cometbft/cometbft-db#168.
We recently updated cometbft-db `Iterator` type `Key()` and `Value()` APIs to return their values directly instead of a copy.
Therefore, this PR ensures that code in cometbft that modifies or stores references to the return value of those APIs creates a copy before continuing.
---

chore(state): Copy `Iterator` `Key()` and `Value()` APIs return values.

---

p2p/pex/pex_reactor_test.go

Follow-up from #3568, as the same test is still flaky.
Trying now with 10s timeout for the connections to happen.
---

test(p2p/pex): fix TestConnectionSpeedForPeerReceivedFromSeed flacky test

---

.changelog/unreleased/breaking-changes/3606-crypto-equals.md
crypto/bls12381/key.go
crypto/bls12381/key_bls12381.go
crypto/bls12381/key_test.go
crypto/crypto.go
crypto/doc.go
crypto/ed25519/ed25519.go
crypto/secp256k1/secp256k1.go
crypto/sr25519/privkey.go
crypto/sr25519/pubkey.go
internal/consensus/replay_test.go
p2p/conn/secret_connection_test.go
test/fuzz/tests/p2p_secretconnection_test.go

a) it's unused
b) Cosmos SDK folks suggested to remove it in one of the issues 
Refs https://github.com/cometbft/cometbft/issues/2426
---

feat(crypto)!: remove PubKey#Equals and PrivKey#Equals

---

test/e2e/docker/Dockerfile

when running:
`test/e2e/make docker` 
getting some warnings:
```
2 warnings found (use docker --debug to expand):
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 15)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 33)
```
this PR fixes the `Dockerfile` and prevent the warnings

test(e2e): fix docker file ENV command to prevent LegacyKeyValueFormat warning

---

mempool/clist_mempool.go
mempool/errors.go

Complements #3314
This PR adds a new error with a more clear error message when checking if the mempool is full while rechecking is in progress after a new block was committed.
---

feat(mempool): add error ErrRecheckFull

---

.changelog/unreleased/dependencies/3661-bump-cometbft-db-version.md
cmd/cometbft/commands/inspect.go
cmd/cometbft/commands/run_node.go
common.mk
config/config.go
config/config.toml.tpl
docs/references/config/config.toml.md
go.mod
node/node.go
test/e2e/Makefile
test/e2e/docker/Dockerfile
test/e2e/docker/Dockerfile.debug
test/e2e/generator/generate.go
test/e2e/pkg/manifest.go
test/e2e/pkg/testnet.go

chore: update cometbft-db dependency

---

api/cometbft/abci/v1/service.pb.go
api/cometbft/abci/v1beta1/types.pb.go
api/cometbft/abci/v1beta2/types.pb.go
api/cometbft/abci/v1beta3/types.pb.go
api/cometbft/rpc/grpc/v1beta1/types.pb.go
api/cometbft/rpc/grpc/v1beta2/types.pb.go
api/cometbft/rpc/grpc/v1beta3/types.pb.go
api/cometbft/services/block/v1/block_service.pb.go
api/cometbft/services/block_results/v1/block_results_service.pb.go
api/cometbft/services/pruning/v1/service.pb.go
api/cometbft/services/version/v1/version_service.pb.go

This PR fixes the protos in `v1.x` in order to make the `check proto` test to pass. 
Same idea as in #3650 but these files were generated in the `v1.x` branch as instead of trying to backport #3650 to `v1.x` since there might be changes to protos in `main` that are not in `v1.x` so this is the best approach to directly update the protos in `v1.x`

chore: update auto-generated proto files in `v1.x`

---

.changelog/v0.38.11/bug-fixes/3528-evidence-missing-json-tags.md
CHANGELOG.md
libs/os/os.go
types/evidence.go
types/evidence_test.go
types/validator_set_test.go

Given the discussion in #3528, we are reverting the changes made by #3543 in `v0.38.x` (backported with #3549).
Additionally, we are removing the changes made in #3543 from the CHANGELOG.
---
~- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)~
~- [] Updated relevant documentation (`docs/` or `spec/`) and code comments~

revert(types): Revert #3543 (backport #3549)

---

.changelog/v0.37.10/bug-fixes/3528-evidence-missing-json-tags.md
CHANGELOG.md
libs/os/os.go
types/evidence.go
types/evidence_test.go
types/validator_set_test.go

Given the discussion in #3528, we are reverting the changes made by #3543 in `v0.37.x` (backported with #3550).
Additionally, we are removing the changes made in #3543 from the CHANGELOG.
---
~- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)~
~- [] Updated relevant documentation (`docs/` or `spec/`) and code comments~

revert(types): Revert #3543 (backport #3550)

---

crypto/encoding/codec.go
crypto/encoding/codec_test.go
internal/keytypes/keytypes.go
types/validator.go
types/validator_test.go

Otherwise, we could panic in the light client upon receiving a Validator w/ a pubkey of unsupported type. Previous attempt https://github.com/cometbft/cometbft/pull/3702
Refs https://github.com/cometbft/cometbft/issues/3699
---

fix(types): validate `PubKey.Type` in `Validator`

---

.github/mergify.yml

If there's `manual-backport` label, Mergify won't merge the backport PRs automatically.

chore(mergify): rule for v0.34, `manual-backport` label

---

.changelog/unreleased/bug-fixes/3694-mempool-update-variables-atomically.md
mempool/clist_mempool.go
mempool/errors.go

Fixes #3694 
This PR replaces:
```
type CListMempool struct {
txsBytes atomic.Int64 // total size of mempool, in bytes
...
txs    *clist.CList
txsMap sync.Map
...
}
```
by
```
type CListMempool struct {
...
txsMtx   cmtsync.RWMutex
txs      *clist.CList                    // concurrent linked-list of valid txs
txsMap   map[types.TxKey]*clist.CElement // for quick access to txs
txsBytes int64                           // total size of mempool, in bytes
...
}
```
The new `txsMtx` mutex is used every time the variables `txs`, `txsMap`, and `txsBytes` are accessed.
---

fix(mempool): Update variables in `CListMempool` atomically

---

.github/PULL_REQUEST_TEMPLATE.md

We already have an automated task that checks that the title is formatted. We don't need to mark it manually.
---

ci: Remove Conventional Commits from PR checklist template

---

test/e2e/generator/generate.go

Part of #3720
With this change, the `e2e` generator no longer generates manifests with bls as key type, so bls is no longer tested in the nightlies.
This is temporary, to be reverted also as part of #3720 in a future PR
Manual nightly run: [here](https://github.com/cometbft/cometbft/actions/runs/10418554752/job/28854915428)
---

fix(e2e): remove bls from e2e generator

---

crypto/bls12381/key.go
crypto/bls12381/key_bls12381.go
crypto/bls12381/key_test.go
crypto/encoding/codec_test.go
test/e2e/generator/generate.go
test/e2e/generator/generate_test.go
test/e2e/pkg/testnet.go

Part of #3720
`e2e` tests _require_ a method that generates a private key deterministically (from a secret). Without such method, is it not possible for the "tests" step of the `e2e` runner to recreate the node structure as it exists within the runner itself.
Manual nightly runs:
- [1st try](https://github.com/cometbft/cometbft/actions/runs/10424046666)
- [2nd try](https://github.com/cometbft/cometbft/actions/runs/10424939531), after 53321d4
---

fix(e2e): fix BLS-related failures

---

mempool/clist_mempool.go
mempool/errors.go
mempool/mempoolTx.go

We don't need to store the lane in a separate map. We can just extend `mempoolTx` with a `lane` field.
---

feat(mempool/lanes): Store lane in `mempoolTx` and remove `txsLanes`

---

mempool/clist_mempool.go

There's a problem when rechecking reaches the end of a lane. It finishes the recheck process, and all subsequent recheck responses are discarded.

fix(lanes): revert changes to recheck mechanism

---

abci/example/kvstore/kvstore.go
abci/example/kvstore/kvstore_test.go
mempool/clist_mempool_test.go
test/e2e/app/app.go

Depends on #3833
Currently it computes a hash to assign a lane, which makes it impossible to easily reproduce in tests. With this change it will use the key in a "key=value" transaction.

feat(lanes): Change lane selection algorithm in kvstore app

---

.changelog/unreleased/improvements/3624-crypto-bls-sig-size.md
crypto/bls12381/const.go
crypto/bls12381/key_bls12381.go
state/tx_filter_test.go
types/block.go
types/block_test.go

because it's not Ethereum compatible and breaks Berachain
Reverts https://github.com/cometbft/cometbft/pull/3627
---

revert(crypto): revert BLS sig size downgrade

---

mempool/clist_mempool.go
mempool/clist_mempool_test.go

One iterator is for sending CheckTx requests. Another one is for traversing the list of entries to recheck, in `findNextEntryMatching`. Both need to generate the same sequence of entries.
---

fix(lanes): Use iterators for rechecking

---

test/e2e/tests/app_test.go

log the tx hash when `e2e` app test fails

test(e2e): log tx hash after failed e2e test

---

api/cometbft/types/v1/params.pb.go
proto/cometbft/types/v1/params.proto
spec/abci/abci++_app_requirements.md
spec/core/data_structures.md
types/params.go

Closes #3601
As per title. Added clarifications in some places, and reworded existing explanations in other places.
---

docs: clarifiy VE and PBTS enable height set to 0

---

.changelog/unreleased/improvements/3880-e2e-manual-debug-workflow.md
.github/workflows/e2e-manual-debug.yml
test/e2e/README.md

The `log_level` on the `e2e-manual-debug` was set incorrectly. This PR fixes it.
Realized after running a `e2e-manual-debug` workflow,[ all tests failed](https://github.com/cometbft/cometbft/actions/runs/10597473846) with:
```
validator01  | E[2024-08-28|13:20:29.330] failed to setup config: expected list in a form of "module:level" pairs, given pair debug, list [debug p2p:info] 
```
instead of using log level:
```
"debug,p2p:info"
```
this PR fixes it and uses the correct one:
```
"*:debug,p2p:info"
```
> NOTE: Also added a changelog entry for the new e2e workflow, previous PR only had a changelog entry for the generator new log level option

test(e2e): fix debug level on workflow

---

.changelog/unreleased/features/3963-e2e-load-internal-ip.md
test/e2e/pkg/testnet.go
test/e2e/runner/load.go
test/e2e/runner/main.go

The new flag `--internal-ip` will make the `runner load` command to use the nodes' internal IP addresses when sending the transaction load. This is needed when running `load` from a node in a DigitalOcean private network.
---

feat(e2e): Add `--internal-ip` flag to `load` command

---

crypto/secp256k1/secp256k1.go
crypto/secp256k1/secp256k1_test.go
spec/core/encoding.md

Also:
* assert ripemd160.Size == crypto.AddressSize
* write tests for PrivKeySize and PubKeySize
Closes #3727
---

docs(crypto/secp256k1): fix Address docs

---

.changelog/unreleased/bug-fixes/0016-abc-light-proposer-priorities.md
.changelog/unreleased/improvements/0016-abc-types-validator-set.md
light/client.go
light/client_test.go
light/detector.go
light/errors.go
types/validator_set.go
types/validator_set_test.go

The light client implementation compares the `ValidatorSet` instances received from different sources (the primary against one or more witnesses). In particular, the state of the proposer selection algorithm, represented by the  `ProposerPriority` field of each `Validator` present in the `ValidatorSet`, should be identical.
In order to compare those fields, we add  a`ProposerPriorityHash()` to the `ValidatorSet` type. This is needed because the  `Hash()` method of the same type does not include the `ProposerPriority` fields in its computation.
When the light client detects distinct states of the proposer selection algorithm, the `VerifyLightBlockAtHeight` method of the `light.Client` type, used for instance by the state sync protocol, returns an error.
---

fix(light): cross-check proposer priorities in retrieved validator sets

---

internal/consensus/common_test.go
internal/consensus/mempool_test.go

`TestReactorVotingPowerChange` was failing because (non-persistent) app was not properly initialised with lanes.

test(mempool/lanes): Initialise app with lanes in consensus tests (part 2)

---

test/e2e/runner/load.go

Currently `runner load` will log an error for every tx that it failed to send, which can hundreds of lines. With this change, every distinct error will be logged once every ~1 second, with the number of times it failed during that time.
---

test(e2e): Log multiple failed sent txs in one line

---

internal/consensus/errors.go
internal/consensus/state.go

in "Failed to process message" error log instead of a separate Info log.
Closes #2395
Before:
```
failed to process message err=error adding vote
```
After:
```
Failed to process message err=error adding vote: invalid signature
```
---

feat(consensus): print ErrAddingVote with a reason

---

.changelog/unreleased/dependencies/4053-update-python-requests-dep.md
scripts/qa/reporting/requirements.txt

The project has a dependency on an old version of the python module [requests](https://pypi.org/project/requests/2.32.3/), which is vulnerable to [CVE-2023-32681](https://nvd.nist.gov/vuln/detail/CVE-2023-32681) and [CVE-2024-35195](https://nvd.nist.gov/vuln/detail/CVE-2024-35195).
This PR updates the version of the python module `requests` to the latest unaffected by vulnerabilities.
---
~- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments~

build(deps): update python module `requests` to v2.32.3

---

mempool/clist_mempool.go

fix(mempool): encode tx.Hash() as %X in logs

---

go.mod

Helps with #4039 and to unblock merges to `v0.38.x`

chore: Bump go toolchain to `1.22.7` on `v0.38.x`

---

p2p/pex/addrbook.go
p2p/pex/addrbook_test.go
spec/abci/abci++_app_requirements.md
spec/p2p/legacy-docs/peer.md
statesync/snapshots.go

in statesync, adopt "rejectlist" instead
to match the wording used in that package

chore: rename whitelist->allowlist, blacklist->denylist

---

mempool/clist_mempool_test.go
mempool/iterators_test.go

Test multiple blocking iterators accessing the mempool while txs are being added.
---

test(lane): add test with concurrent blocking iterators

---

mempool/iterators.go

By making the `pickLane` function non blocking, the main goal of this refactoring is to remove the unlock/lock pattern of `addTxChMtx` in `pickLane`. This prepares the code to add a cancellable context to the blocking iterator (see #4107), which now we can add to `WaitNextCh` (around the line `<-addTxCh`), outside `pickLane`.

refactor(lanes): make `pickLane` non blocking

---

mempool/clist_mempool_test.go
mempool/iterators.go
mempool/iterators_test.go
mempool/reactor.go

Depends on #4106; merge that one first.
This is equivalent to #4058 on the `main` branch. It was made on a different PR because there are too many differences in the code to be ported to the feature branch.
Besides the context, the iterator now also has a name which is used for debugging with concurrent iterators.

fix(lanes): Pass cancellable context to blocking iterator

---

docs/guides/tools/proposer-based-timestamps-runbook.md

Description:
- Fix typos in the doc "proposer-based-timestamps-runbook.md"
- No test needed as only doc been changed

docs: fix typos

---

test/e2e/generator/generate.go
test/e2e/pkg/manifest.go
test/e2e/pkg/testnet.go
test/e2e/runner/setup.go
test/e2e/tests/validator_test.go

As per title.
It was like this before https://github.com/cometbft/cometbft/pull/3964, so restoring original name.
---

feat(e2e): `Manifest`, renamed `ValidatorsMap` -> `Validators`

---

test/e2e/generator/generate.go
test/e2e/pkg/manifest.go
test/e2e/pkg/testnet.go
test/e2e/runner/setup.go
test/e2e/tests/block_test.go
test/e2e/tests/validator_test.go

Partially addresses #2458
Change the `*Node` as keys of some maps in `e2e` and replace them by the node's name.
Having pointers as keys of a map brings about subtleties (how comparison is done) that we don't need. Code is much clearer with node names, even if it takes a bit longer to execute some loops (we need to look up the nodes). But this is test code, so clarity and robustness comes before performance of the testing code.
I decided to tackle this refactor in an different PR, rather than piggybacking it to #2283
---

refactor(e2e): change `*Node` to string in keys of some maps

---

node/setup.go

`GenesisDocProvider` is a function that users can implement and provide when creating a new `Node`. The function allows users to decide how the `GenesisDoc` should be provisioned to the chain. When called, it returns a [`ChecksummedGenesisDoc`](https://github.com/cometbft/cometbft/blob/87a8c8948bf9926aff37f344b4120163f12cb4ad/node/setup.go#L46), an object that stores both the `GenesisDoc` and its SHA256 checksum.
Our code does not verify the internal consistency of the `ChecksummedGenesisDoc`. Specifically, it does not check whether the `Sha256Checksum` field is actually the hash of the `GenesisDoc` field it contains. We rely on the `GenesisDocProvider` to ensure that `SHA256(GenesisDoc) == Sha256Checksum`. However, this critical assumption isn't explicitly documented in the …

docs(Node): Expand docs of `GenesisDocProvider`

---

abci/example/kvstore/kvstore.go
p2p/mocks/peer.go

Minor fix related to recent changes from Lanes: remove unused variable with array of lane priorities, plus some renaming and comments.
---

fix(kvstore): Remove unused lanes-related variable

---

.changelog/unreleased/improvements/4235-4234-environment-stores-one-genesis.md
node/node.go
p2p/mocks/peer.go
rpc/core/env.go
rpc/core/env_test.go
rpc/core/net.go
rpc/core/testdata/genesis_ci.json

Closes #4234.
The [`Environment`](https://github.com/cometbft/cometbft/blob/8273634cdefb2fb22765a14f9acb9fca608e9982/rpc/core/env.go#L72) type will:
- Store a pointer to a `GenesisDoc` if the genesis file size is below a threshold currently set to 16 MB.
- If the genesis file exceeds this threshold, it will split it into 16 MB chunks and store the hashes of each chunk in memory in a slice. In this case, the pointer to the `GenesisDoc` will be `nil`. 
Because the `InitGenesisChunks` method of `Environment` is responsible for creating the chunks, most of the changes of this PR focus on refactoring this method and adding unit tests for it.
---

chore(RPC): `Environment` stores only one in-memory copy of the Genesis

---

docs/guides/tools/proposer-based-timestamps-runbook.md
docs/guides/upgrades/v0.38-to-v1.0.md
types/params.go

Closes #4246
- `Precision` was set to `505ms`, because it should be greater than 0.5s, as in https://github.com/tendermint/tendermint/issues/7724
- `MessageDelay` was increased to `15s`, following the measurements reported in https://github.com/tendermint/tendermint/pull/7788, and considering some outputs of `e2e` tests
---

feat(types): increase default `SynchronyParams` consensus parameters values

---

.changelog/unreleased/improvements/4281-use-embed-pkg-for-template-string.md
config/config.toml.tpl

When writing `config.toml` via `config.WriteConfigFile` the `mempool.type` field is hardcoded to `flood`. This fixes it to populate it from provided config struct.

fix(config): Dynamic mempool type when writing config

---

node/node.go
node/node_test.go
rpc/client/local/local.go
rpc/core/env.go

Closes #4248.
The `Node` type will:
- create a singleton instance of `Environment` when setting up the RPC APIs.
- set the pointer to the `GenesisDoc` to `nil` once startup is complete so that the GC can collect the in-memory `GenesisDoc` object.
- store a `GenesisTime` field.
---

chore(Node): Node does not keep a pointer to a GenesisDoc after initialization

---

go.mod
go.sum
state/indexer/block/kv/kv.go
state/txindex/kv/kv.go
test/e2e/docker/Dockerfile

Because, in cometbft-db v0.13+, the iterator is being reused so we need to always copy key and value if we're storing them in a map or other in-memory structure.
Closes #4295

fix(state/indexer): copy value

---

config/config.go
internal/confix/data/v1.0.toml

fix(config): do not populate deprecated timeout_commit with non-zero value

---

.changelog/unreleased/breaking-changes/3878-statesync-max-discovery-time.md
config/config.go
config/config.toml.tpl
config/errors.go
docs/explanation/core/state-sync.md
docs/references/config/config.toml.md
internal/blocksync/reactor.go
node/setup.go
statesync/reactor.go
statesync/syncer.go
statesync/syncer_test.go
test/e2e/runner/setup.go

if the node can't discover snapshots for 2 min
(`statesync.max_discovery_time`), switch to blocksync. Remove
`statesync.discovery_time` from the configuration. If
`statesync.max_discovery_time` is zero, the node will be retrying
indefinitely.
Closes https://github.com/cometbft/cometbft/issues/3878

feat(statesync)!: replace discovery_time with max_discovery_time

---

.github/workflows/gobenchdata-base.yml
.github/workflows/gobenchdata-current.yml

Fixes "Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/"

ci: update upload-artifact version

---

.changelog/unreleased/improvements/4351-e2e-kill-perturbation-timeout.md
test/e2e/runner/perturb.go
test/e2e/runner/rpc.go

One reason some e2e tests are failing is that the kill perturbation has a short timeout value of 20 seconds, causing waitForNode to time out. Doubling this timeout improves test stability and helps ensure the tests pass
[test failure](https://github.com/cometbft/cometbft/actions/runs/11546210646/job/32134226559)

test(e2e): give the runner extra time to wait for a killed node

---

.changelog/unreleased/breaking-changes/4340-lazy-hash.md
internal/consensus/state.go
libs/log/lazy.go
libs/log/lazy_test.go
mempool/clist_mempool.go
test/e2e/tests/app_test.go
types/tx.go

Closes #4167 
Generalizes LazyBlockHash as LazyHash so now Txs and Blocks are hashed only on evaluation of the debug printf
#go-api-breaking

perf(log)!: `LazyHash` for producing txs and blocks debug hashes

---

state/store.go
state/store_test.go

The `BenchmarkLoadValidators` benchmark in the `state` package panics because it can't find the validators' information for the specified heights. The issue is caused by a missing `DBKeyLayout` in the test database configuration, which leads to the `LoadValidators` call failing.
- the benchmark now creates a new state `Store` by explicitly specifying the `DBKeyLayout` in the `StoreOptions`. 
- `store` constructor checks if `DBKeyLayout` is set; if not, it sets it to a default value.
---
- ~[] Updated relevant documentation (`docs/` or `spec/`) and code comments~

fix(store): `BenchmarkLoadValidators` no longer panics

---

tests.mk

Looks like PR https://github.com/cometbft/cometbft/pull/4088 broke [the integration tests](https://github.com/cometbft/cometbft/actions/runs/11625455423/job/32390983977?pr=4377) and it's blocking the other PRs. This should fix it.

fix: broken integration tests

---

docs/explanation/core/metrics.md

See https://docs.cometbft.com/v0.38/core/metrics :
> Listen address can be changed in the config file (see `instrumentation.prometheus\_listen\_addr`).

docs(metrics): Fix typo

---

go.mod

Part of #4444.
Retracts `v0.38.14`. 
---
~- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments~

Retract v0.38.14

---

.github/mergify.yml

in favor of manual merge once in a while. Manually solving conflicts upon each merge takes too much time and not worth it.

ci: remove backporting to v0.38.x-experimental

---

CONTRIBUTING.md

Part of https://github.com/cometbft/cometbft/issues/4444.

docs: add note about Go version bumps

---

test/e2e/pkg/testnet.go
test/e2e/run-multiple.sh

This issue was introduced by https://github.com/cometbft/cometbft/pull/2283.
I've sneaked in a minor change in the script, so that we can grep for "Testnet failed" and go directly to the right manifests.
---

fix(e2e): do not oscilate validator set when it contains a single validator

---

spec/abci/abci++_methods.md

This PR adds information about the extra fields used in ABCI to support lanes. 
---

feat(spec): Add lanes to abci spec

---

.changelog/unreleased/improvements/4484-v1keylayout-sprintf.md
state/store.go

The `v1LegacyLayout` type uses `fmt.Sprintf()` to create the DB keys. This PR substitutes `fmt.Sprintf` with string concatenation, which is 3-4 times faster for such a simple string.
In general, we shouldn't use `fmt.Sprintf()` to concatenate strings, because it's inefficient. 
Exceptions could be constructing error messages (but we should use `fmt.Errorf()` for that) or tests.
---

chore(state): `v1LegacyLayout` keys no longer use `fmt.Sprintf()`.

---

.changelog/unreleased/improvements/4489-blockstore-v1LegacyLayout-sprintf.md
store/db_key_layout.go
store/db_key_layout_test.go

The `v1LegacyLayout` type of pkg `store` uses `fmt.Sprintf()` to create the DB keys. 
This PR refactors functions using `fmt.Sprintf` to improve their speed and memory usage.
---

chore(store): `store.v1LegacyLayout` no longer uses `fmt.Sprintf()` to create DB keys.

---

.golangci.yml
internal/storage/db.go
internal/storage/pebbledb.go

CometBFT will stop importing [cometbft-db](https://github.com/cometbft/cometbft-db) as a dependency to support multiple database backends. Instead, it will use [pebble](https://github.com/cockroachdb/pebble) by default.
This PR adds package `storage` to the `internal` packages: 
- it exports the `DB`, `Batch`, and `Iterator` interfaces that database backends must implement to work with CometBFT. Previously, they were offered by cometbft-db.
- it exports the pebbledb implementation of the above interfaces.
Users can provide their own implementation of these interfaces using a different database under the hood. However, we will support and maintain only the pebble implementation that CometBFT will use.
**Note**: this PR ports the code currently provided by …

feat(storage): Add package `internal/storage`

---

.golangci.yml
internal/storage/pebbledb.go
internal/storage/pebbledb_test.go

CometBFT will stop importing [cometbft-db](https://github.com/cometbft/cometbft-db) as a dependency to support multiple database backends. Instead, it will use [pebble](https://github.com/cockroachdb/pebble) by default.
This PR adds unit tests to the pebble implementation of the `DB` interface that CometBFT will use once we remove cometbft-db.
---

feat(storage): Add unit tests for pebble implementation of `DB` interface.

---

internal/storage/pebbledb.go
internal/storage/pebbledb_test.go

CometBFT will stop importing [cometbft-db](https://github.com/cometbft/cometbft-db) as a dependency to support multiple database backends. Instead, it will use [pebble](https://github.com/cockroachdb/pebble) by default.
This PR adds unit tests to the pebble implementation of the `Batch` interface that CometBFT will use once we remove cometbft-db.
---

feat(storage): Add unit tests for pebble implementation of `Batch` interface.

---

.github/workflows/e2e-long-37x.yml
.github/workflows/fuzz-nightly.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml

This PR fixes the Slack Notifications in GitHub Actions that got broken after this [PR](https://github.com/cometbft/cometbft/pull/4500) got merged.

fix: Slack notifications Templates for GitHub Actions workflows (`v0.37.x`)

---

.github/workflows/e2e-long-main.yml
.github/workflows/e2e-nightly-1x.yml
.github/workflows/e2e-nightly-34x.yml
.github/workflows/e2e-nightly-37x.yml
.github/workflows/e2e-nightly-38x.yml
.github/workflows/e2e-nightly-main.yml
.github/workflows/fuzz-nightly.yml
.github/workflows/notify-about-breaking-changes.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
.github/workflows/test-slack-notification.yml

This PR fixes the Slack Notifications in GitHub Actions that got broken after this [PR](https://github.com/cometbft/cometbft/pull/4505) got merged.

fix: Slack notifications Templates for GitHub Actions workflows (`main` | `v1.x` backport)

---

internal/storage/pebbledb.go
internal/storage/pebbledb_test.go

CometBFT will stop importing [cometbft-db](https://github.com/cometbft/cometbft-db) as a dependency to support multiple database backends. Instead, it will use [pebble](https://github.com/cockroachdb/pebble) by default.
This PR adds unit tests to the pebble implementation of the `Iterator` interface that CometBFT will use once we remove cometbft-db.
---

feat(storage): Add unit tests for pebble implementation of `Iterator` interface.

---

test/e2e/app/app.go

Follow-up of #4475.
The e2e application by default produces a colorized output. This should not be the case for the same reasons explained in https://github.com/cometbft/cometbft/issues/4452.
---

fix(e2e): application logger does not use colors

---

.changelog/unreleased/breaking-changes/4550-mempool-err-invalid-tx.md
mempool/clist_mempool.go
mempool/errors.go

When calling the RPC endpoints `broadcast_tx_*`, the mempool returns a `reqRes` object with a potential error. Before #4040, `reqRes` didn't have an error. An error on the ABCI CheckTx call would be returned encoded in the fields Code, Log, etc, of `ResultBroadcastTx`. Any other internal error of the mempool would be discarded.
The problem is that now when the transaction is invalid, `broadcast_tx_*` return `ErrTxBroadcast{Source: ErrCheckTxFailed, ErrReason: err}` where `err`  is simply `ErrInvalidTx`, without any other information. This PR adds all the fields in `ResultBroadcastTx` (Code, Data, Log, Codespace, and Hash) to `ErrInvalidTx`, so that this information is available gain to the `broadcast_tx_*` caller.
---

fix(mempool): Extend `ErrInvalidTx` with `CheckTxResponse` info

---

test/e2e/pkg/manifest.go
test/e2e/pkg/testnet.go
test/e2e/runner/load.go
test/e2e/runner/main.go

Solves #4430
by fixing #4513
This solution creates multiple transaction channels, one per node in the testnet. On each transaction generated, it will send the transaction to  `LoadNumNodesPerTx` random channels.
---

feat(e2e): for loading with num-nodes-per-tx, use one channel per node

---

.changelog/unreleased/dependencies/4605-fix-mockery-version.md
scripts/mockery_generate.sh

Using `latest` for `mockery` causes changes in the mocks with almost every new release, which in turn makes our CI fail. By fixing `mockery`'s version, we can prevent this issue. Additionally, `mockery`'s documentation suggests not to use `latest` anyway, so we were doing it incorrectly from the start.
This PR pins the `mockery` version to `v2.49.2` (the latest release). The `main` branch already uses mocks generated with this version, so using any other version of `mockery` would alter the mocks again. At least we get the benefit from the latest bug fixes.
---

build(deps): Mock generation no longer uses the `latest` tag on `mockery`.

---

.changelog/unreleased/improvements/4639-remove-sync-once.md
node/node.go

Because `rpc.Environment` does not store a `GenesisDoc` in memory anymore, (see #1290), we don't need to create it as a singleton. The risk of storing multiple copies of the genesis in memory isn't there anymore, because we now load it from disk.
This PR removes the `sync.Once` construct that we put in place.
The change also ensures that [`TestProvider`](https://github.com/cometbft/cometbft/blob/b16c6fc2c8b2fc5a468fead32a8fe9057d6cce2f/light/provider/http/http_test.go#L36) in the `light/provider/http` package behaves as expected. In `main`, this test passes because it's set up using a [`MemDB`](https://github.com/cometbft/cometbft-db/blob/4cf60c715fe8daccb9dce3b24295575bd461d5d8/memdb.go#L52), which is a dummy in-memory store rather than a real database. Thus, database `Get` operations …

chore(node): `Node` no longer uses a singleton to create an `rpc.Environment`

---

internal/blocksync/pool.go
internal/blocksync/pool_test.go

follow up to #4633 
See https://github.com/cometbft/cometbft/actions/runs/12247740137/job/34188217504
<details>
<summary>DATA RACE</summary>
==================
WARNING: DATA RACE
Write at 0x00c00028f110 by goroutine 507:
runtime.mapassign_faststr()
/opt/hostedtoolcache/go/1.23.1/x64/src/runtime/map_faststr.go:223 +0x0
github.com/cometbft/cometbft/internal/blocksync.(*BlockPool).banPeer()
/home/runner/work/cometbft/cometbft/internal/blocksync/pool.go:433 +0x16f
github.com/cometbft/cometbft/internal/blocksync.(*BlockPool).RemovePeerAndRedoAllPeerRequests()
/home/runner/work/cometbft/cometbft/internal/blocksync/pool.go:266 +0x192
github.com/cometbft/cometbft/internal/blocksync.TestBlockPoolMaliciousNode.func4()
/home/runner/work/cometbft/cometbft/internal/blocksync/pool_test.go:353 +0x1ee …

fix(test): fix TestBlockPoolMaliciousNode DATA RACE

---

mempool/reactor_test.go

A mistake in the tests got merged with the  PR merging the DOG protocol into main. 
`TestDOGDisabledRoutes` was put asleep for 100s instead of 100ms. 
---

fix(mempool): Decreased the sleep in `TestDOGDisabledRoutes`

---

p2p/pex/pex_reactor.go

Solves #4620.
Fixes an issue introduced by https://github.com/cometbft/cometbft/pull/3360.
In short, when receiving addresses from a configured seed node, the peer immediately dials the received addresses, without waiting for the `defaultEnsurePeersPeriod` (30s). This is a desired behavior, the "fast dial mode" in the title.
However, for preventing abuse, a node only accepts PEX requests from a peer every `minReceiveRequestInterval()` time, set to `defaultEnsurePeersPeriod/3` (10s). When running this "fast dial mode", however, a PEX request can be send, in some unlucky setup, to the same peer without waiting for the full defaultEnsurePeersPeriod` (30s).
The problem is that at the receive side, a node keeps track of the latest PEX request received from each peer. If two requests are …

fix(p2p/pex): do not send PEX request in fast dial mode

---

.changelog/unreleased/dependencies/4650-update-build-process.md
.golangci.yml
test/e2e/Makefile
test/e2e/docker/Dockerfile
test/e2e/docker/Dockerfile.debug

This PR removes cometbft-db from cometbft build process:
- Dockerfiles
- Makefiles
- CI 
Please add in the discussion below any file that I have forgotten to update.
---

build(deps): Remove cometbft-db from cometbft build.

---

.changelog/unreleased/improvements/4667-broadcast-single-message-marshal
p2p/peer.go
p2p/switch.go
p2p/types.go
p2p/types_test.go

Closes #4615 
This avoids multiple marshals of the `Envelope` message when broadcasting.

perf(p2p): do not remarshal envelope message within broadcast

---

crypto/bls12381/key.go
crypto/bls12381/key_bls12381.go

- added func `NewPublicKeyFromCompressedBytes` to create a new BLS12-381 public key from a slice of bytes representing a compressed 48-bytes BLS12-381 key created elsewhere.
- added method `Compress` to type `PubKey` to return compress the BLS12-381 public key from 96 to 48 bytes.
- added a new exported error `ErrPubKeyDecompression`.

feat(crypto): update `bls12381` pkg

---

test/e2e/app/snapshots.go

when pruning. Suggested by GH copilot while nightly test failure debugging.

fix(e2e): skip missing snapshots

---

CHANGELOG.md

This PR fixes the links to ADRs in the .CHANGELOG.

docs(changelog): Fix broken links to ADRs in .CHANGELOG

---

.changelog/unreleased/bug-fixes/4721-nonrp-ext-e2e-fix.md
internal/consensus/state.go
test/e2e/app/app.go
test/e2e/generator/generate.go
test/e2e/runner/evidence.go

PR #4688 increased the size of vote extensions used in the e2e app which resulted in e2e tests failing because the messages were too  big. 
This PR does two things:
- Does not convert the Non replay-protected vote extensions to a Hex String (as this doubles their size). 
- Uses a lower value for the generated VEs because this value will in practice be doubled (if the configuration size is 256, we will have `VoteExtension` of size 256 and `NonRpExtension` of size 256). 
---

fix(e2e): Reduce size of generated vote extensions and don't convert to Hex

---

spec/core/data_structures.md

fix(spec): Update spec with info on signature size of  `secp256k1eth`

---

test/e2e/networks/ci.toml

key_type entry has no actual effect. The reason is that we never implemented the key_type at the node level in the e2e manifest, but rather at the testnet level.

chore(e2e): remove `key_type` from ci manifest

---

cmd/cometbft/commands/light.go
cmd/cometbft/commands/reindex_event.go
cmd/cometbft/commands/reindex_event_test.go
cmd/cometbft/commands/rollback.go

As part of the work in #4601, we want to allow users to use their own database if they don't like pebble. As CometBFT will use the same [DB interface](https://github.com/cometbft/cometbft-db/blob/8bd4531b5122530f39a90d385cb0b0523dbe881e/types.go#L21) that cometbft-db uses, users can provide their own implementation of the interface that uses a different database under the hood. They will, therefore, have to change the [`config.DefaultDBProvider` function](https://github.com/cometbft/cometbft/blob/b8df798fd85c68e289c595df0b233f37df5db616/config/db.go#L30) to return their implementation instead of our default.
To minimize the places in the code to change, we think that users should only change the `config.DefaultDBProvider` to user thei DB. Therefore, some places in the code must change to …

feat(storage): Top level commands create a new database using `config.DefaultDBProvider()`

---

.github/dependabot.yml

Remove EOL version from dependabot updates. Will close existing PRs merging into v0.37.x and v0.34.x branches.

chore: Remove EOL versions from dependabot

---

privval/signer_requestHandler.go

I don't see this on main branch, so this is just a patch for v0.38.x
---

fix: remove redundant error check for PubKeyToProto

---

.changelog/unreleased/breaking-changes/4951-dial-handshake-timeout.md
config/config.go
config/config.toml.tpl
docs/references/config/config.toml.md
p2p/peer_test.go
p2p/switch.go

- dial_timeout was only used in tests
- handshake_timeout does not need to be configurable and can be a const
Closes #4951

feat(config)!: remove dial_timeout and handshake_timeout

---

.changelog/unreleased/improvements/4986-restore-os-and-rand-packages.md
libs/os/os.go
libs/os/os_test.go
libs/rand/random.go
libs/rand/random_test.go

Closes #4986 
Summary
Restores libs/os and libs/rand from internal/ to temporarily maintain backward compatibility. Adds deprecation notices to indicate their removal in a future release.
Changes
- Restored libs/os and libs/rand from internal/ (just did a copy)
- Added Deprecated: comments to both packages (only added comments)

feat(libs): restore os and rand, add deprecation notices

---

.github/workflows/testapp-docker.yml

Previously, we would only push a single arm64 image. Evidence: https://hub.docker.com/r/cometbft/e2e-node/tags

ci(testapp-docker): release two images, not one

---

node/node.go

This was introduced in #2327, maybe by mistake with a double copy

fix(node): remove duplicate `WithDBKeyLayout` options

---

rpc/jsonrpc/jsonrpc_test.go

`err` has been checked before with `require.NoError(t, err)`, actually we are not aim to check `err` but `msg.Error` :)

fix(rpc/test): misuse wrong err variable

---

docs/explanation/core/proposer-based-timestamps.md
spec/consensus/proposer-based-timestamp/pbts-sysmodel.md
spec/core/data_structures.md

Closes #4893 
This PR updates the PBTS-related documentation to reflect the implementation constraints introduced in #4816.
- In `proposer-based-timestamps.md`, added notes under `Precision` and `MessageDelay` to document the hard-coded caps:
- `Precision` ≤ 30s
- `MessageDelay` ≤ 24h
- In `data_structures.md`, added a note below the SynchronyParams table to mention these limits as implementation constraints.
- In `pbts-sysmodel.md`, included a note after [PBTS-MSG-DELAY.0] explaining that although these parameters are bounded in the implementation, it has no impact on the formal model.
These updates ensure that readers are aware of the practical limitations applied in the implementation and help prevent misconfiguration or misunderstanding.

docs: document max values for PBTS Precision and MessageDelay

---

RELEASES.md

The link to Mergify's "backport" article is outdated so i replaced it with new one. 
---

docs(RELEASES.md): fix broken link

---

.changelog/unreleased/bug-fixes/4735-quick-start-docs.md
docs/tutorials/quick-start.md

Fixes https://github.com/cometbft/cometbft/issues/4735 and incorporates [CreeptoGengar](https://github.com/CreeptoGengar)'s changes in https://github.com/cometbft/cometbft/pull/5120.
Fixes the quick start transaction documentation:
- Removes broadcast `curl` command with only a key specified with no value
- Adds explanation of the two ways the key/value arguments can be formatted 
- Fixes the explanation of the response to correctly specify the value format as `base64` instead of `hex`

docs: Fix KVStore transaction argument and response format in quick-start tutorial

---

state/indexer/sink/psql/psql_test.go

---
Closes https://github.com/cometbft/cometbft/issues/5149
This fixes an issue where 5432 port is conflicting with a port already in use (presumably from another test)

fix(test): prevent "address already in use" error in dockertest

---

docs/explanation/core/state-sync.md

Fixed a broken link to the configuration page in docs/explanation/core/state-sync.md. The link now correctly points to the existing configuration.md file, allowing users to easily access additional configuration information.
---

docs: Fix broken link to configuration.md in state-sync documentation

---

go.mod
go.sum
test/e2e/docker/Dockerfile
test/e2e/docker/Dockerfile.debug

---
e2e tests are failing on main branch due to issue with image. Caused because I reverted the removal of the dependency on cometbft-db. Updating to latest version fixes this.

chore: upgrade cometbft-db

---

crypto/secp256k1/secp256k1.go
internal/blocksync/pool_test.go
internal/consensus/msgs.go
internal/consensus/msgs_test.go
internal/consensus/reactor.go
mempool/clist_mempool.go
mempool/mocks/mempool.go
mempool/reactor.go
node/setup.go
p2p/internal/nodeinfo/nodeinfo.go
p2p/internal/nodekey/nodekey.go
p2p/mocks/peer.go
p2p/netaddr/netaddr.go
p2p/peer.go
p2p/pex/addrbook.go
p2p/pex/addrbook_test.go
p2p/pex/pex_reactor.go
p2p/pex/pex_reactor_test.go
p2p/switch.go
p2p/switch_test.go
rpc/core/net.go
scripts/metricsgen/metricsgen.go
statesync/chunks_test.go
statesync/reactor_test.go
statesync/snapshots_test.go
statesync/syncer.go
statesync/syncer_test.go

---
Update `nodekey.ID` to be `type ID = string` instead of `type ID string`.
For some reason mockery attempts to use the internal path when regenerating mocks when the modules path is update to `github.com/cometbft/cometbft/v2`.
This change make mockery use string instead of the internal type. I am unsure why it uses the public type in the v1 implementation.
Long term solution is likely to update mockery, but this fixes it for now at the cost of reduction in type strictness.

fix: update nodekey.ID to use type alias instead of declaration

---

mempool/reactor.go
mempool/reactor_test.go

Duplicate Tx from RPC causes nil pointer exception in DOG protocol when sending HaveTx.
---
Closes https://github.com/cometbft/cometbft/issues/5159

fix: check for nil sender before sending DOG HaveTx message

---

.github/workflows/testapp-docker.yml

---
Since in a later step we are creating a multi arch build, my understanding is that tagging each build independently can cause a race condition on dockerhub's side.
Since we are seeing single architecture builds on dockerhub, this will hopefully fix it.

chore: remove tag from individual builds

---

.dockerignore
test/e2e/docker/Dockerfile
test/e2e/docker/Dockerfile.debug

---
I removed .git from the .dockerignore because it's used during building. Doing multistage builds should keep it out of the runtime build. Open to alternative ideas.

fix: do multistage builds for e2e-node

---

.changelog/unreleased/bug-fixes/5275-pruning-ext-commit-fix.md
store/store.go
store/store_test.go

Closes #5275 
This should be back ported all the way to 0.38. Note that in v1 and 0.38 there is no blockCommitCache so that part should be left out. 
---
- [ x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)

fix(store):  Properly prune extended commits

---

abci/server/socket_server.go
consensus/common_test.go
consensus/reactor.go
consensus/wal.go
docs/references/architecture/tendermint-core/adr-077-block-retention.md
libs/math/fraction.go
light/detector.go
mempool/clist_mempool_test.go
proxy/app_conn.go
types/evidence.go
types/validator.go

This PR fixes minor spelling errors across multiple files to improve code readability and consistency.
- **`abci/server/socket_server.go`**: Fixed "retying" → "retrying" in comment
- **`consensus/common_test.go`**: Fixed "didnt" → "didn't" in panic message  
- **`consensus/reactor.go`**: Fixed "wont" → "won't" in comment
- **`consensus/wal.go`**: Fixed "occures" → "occurs" in comment
- **`docs/references/architecture/tendermint-core/adr-077-block-retention.md`**: Fixed "rentention" → "retention"
- **`libs/math/fraction.go`**: Fixed "formating" → "formatting" in error message
- **`light/detector.go`**: Fixed "preforms" → "performs" in comment
- **`mempool/clist_mempool_test.go`**: Fixed "conensus" → "consensus" in comment
- **`proxy/app_conn.go`**: Fixed "ellapsed" → "elapsed" in comment
- …

fix: correct typos in comments and error messages

---

internal/indexer/indexer_utils.go

noticed that the function was returning `(false, err)` even though `err` is always `nil` at this point. this could give the impression that an error was possible here when it actually isn’t.
updated the code to return `(false, nil)` instead, which makes it clear that hitting the boundary is not an error case.

chore: misleading error return in boundary check

---

docs/references/architecture/tendermint-core/adr-042-state-sync.md
docs/references/rfc/rfc-100-abci-vote-extension-propag.md
proto/tendermint/state/types.proto
spec/light-client/accountability/Synopsis.md
spec/light-client/supervisor/supervisor_001_draft.md
spec/p2p/implementation/addressbook.md
state/store.go
test/loadtime/payload/payload.go
types/errors/sanity.go

- Corrects spelling and phrasing in Markdown specs and docs (e.g., “Parallelizable”, “snapshot”, “deterministic”, “submit”, “LastSuccess”).
- Updates proto comment note about `ResponseDeliverTx`.
- Fixes Go comments: pluralization of `ExecTxResults`, “payload”, “validity”.

Fix typos and wording across docs, specs, and comments
